import json
import os

keys = ["name", "scientificName", "nameMeaning", "timePeriod", "myaStart", "myaEnd", "dietType", "dietDetails", "locations", "taxonomicClassification", "genus", "family", "fossilFormation", "country", "reconstructionImageUrl", "fossilImageUrl", "discoveryHistory", "interestingFacts", "lengthM", "heightM", "weightKg", "sizeNotes"]

rows = [
    # Theropods
    ["Tyrannosaurus Rex", "Tyrannosaurus rex", "Tyrant lizard king", "Late Cretaceous", 68.0, 66.0, "Carnivore", "Apex predator", ["North America"], "Theropod", "Tyrannosaurus", "Tyrannosauridae", "Hell Creek", "USA", "t_rex.jpg", "t_rex_fossil.jpg", "Discovered 1902.", "Strongest bite force.", 12.3, 4.0, 8400, "Massive."],
    ["Velociraptor", "Velociraptor mongoliensis", "Swift seizer", "Late Cretaceous", 75.0, 71.0, "Carnivore", "Small prey", ["Asia"], "Theropod", "Velociraptor", "Dromaeosauridae", "Djadochta", "Mongolia", "velociraptor.jpg", "velociraptor_fossil.jpg", "Found 1923.", "Had feathers.", 2.0, 0.5, 15, "Turkey-sized."],
    ["Spinosaurus", "Spinosaurus aegyptiacus", "Spine lizard", "Late Cretaceous", 99.0, 93.5, "Carnivore", "Piscivore", ["Africa"], "Theropod", "Spinosaurus", "Spinosauridae", "Bahariya", "Egypt", "spinosaurus.jpg", "spinosaurus_fossil.jpg", "Found 1912.", "Semiaquatic.", 14.0, 4.5, 7400, "Largest theropod."],
    ["Giganotosaurus", "Giganotosaurus carolinii", "Giant southern lizard", "Late Cretaceous", 99.6, 97.0, "Carnivore", "Apex predator", ["South America"], "Theropod", "Giganotosaurus", "Carcharodontosauridae", "Candeleros", "Argentina", "giganotosaurus.jpg", "giga_fossil.jpg", "Found 1993.", "Hunted sauropods.", 13.2, 4.0, 8000, "Very large."],
    ["Carnotaurus", "Carnotaurus sastrei", "Meat-eating bull", "Late Cretaceous", 71.0, 69.0, "Carnivore", "Fast pursuit", ["South America"], "Theropod", "Carnotaurus", "Abelisauridae", "La Colonia", "Argentina", "carnotaurus.jpg", "carno_fossil.jpg", "Found 1984.", "Distinctive horns.", 7.8, 3.0, 1350, "Short snout."],
    ["Deinonychus", "Deinonychus antirrhopus", "Terrible claw", "Early Cretaceous", 115.0, 108.0, "Carnivore", "Pack hunter", ["North America"], "Theropod", "Deinonychus", "Dromaeosauridae", "Cloverly", "USA", "deinonychus.jpg", "deino_fossil.jpg", "Found 1931.", "Large sickle claw.", 3.4, 0.9, 73, "Agile."],
    ["Tarbosaurus", "Tarbosaurus bataar", "Alarming lizard", "Late Cretaceous", 70.0, 66.0, "Carnivore", "Apex predator", ["Asia"], "Theropod", "Tarbosaurus", "Tyrannosauridae", "Nemegt", "Mongolia", "tarbosaurus.jpg", "tarbo_fossil.jpg", "Found 1946.", "Asian T-rex cousin.", 10.0, 3.0, 4000, "Slightly smaller than T. rex."],
    ["Carcharodontosaurus", "Carcharodontosaurus saharicus", "Shark-toothed lizard", "Late Cretaceous", 100.0, 94.0, "Carnivore", "Large prey", ["Africa"], "Theropod", "Carcharodontosaurus", "Carcharodontosauridae", "Kem Kem", "Morocco", "carcharo.jpg", "carcharo_fossil.jpg", "Found 1924.", "Serrated teeth.", 12.0, 4.0, 6000, "Huge predator."],
    ["Albertosaurus", "Albertosaurus sarcophagus", "Alberta lizard", "Late Cretaceous", 71.0, 68.0, "Carnivore", "Apex predator", ["North America"], "Theropod", "Albertosaurus", "Tyrannosauridae", "Horseshoe Canyon", "Canada", "albertosaurus.jpg", "alberto_fossil.jpg", "Found 1884.", "Found in bonebeds.", 9.0, 3.0, 1700, "Slender tyrannosaurid."],
    ["Utahraptor", "Utahraptor ostrommaysi", "Utah's predator", "Early Cretaceous", 139.0, 134.6, "Carnivore", "Large prey", ["North America"], "Theropod", "Utahraptor", "Dromaeosauridae", "Cedar Mountain", "USA", "utahraptor.jpg", "utahraptor_fossil.jpg", "Found 1991.", "Largest dromaeosaurid.", 7.0, 2.0, 500, "Heavy build."],
    ["Therizinosaurus", "Therizinosaurus cheloniformis", "Scythe lizard", "Late Cretaceous", 70.0, 66.0, "Herbivore", "Browsing", ["Asia"], "Theropod", "Therizinosaurus", "Therizinosauridae", "Nemegt", "Mongolia", "therizino.jpg", "therizino_fossil.jpg", "Found 1948.", "Gigantic claws.", 10.0, 5.0, 5000, "Bizarre theropod."],
    ["Oviraptor", "Oviraptor philoceratops", "Egg thief", "Late Cretaceous", 75.0, 71.0, "Omnivore", "Opportunist", ["Asia"], "Theropod", "Oviraptor", "Oviraptoridae", "Djadochta", "Mongolia", "oviraptor.jpg", "ovi_fossil.jpg", "Found 1923.", "Likely brooded eggs.", 1.5, 1.0, 34, "Parrot-like beak."],
    ["Gallimimus", "Gallimimus bullatus", "Chicken mimic", "Late Cretaceous", 70.0, 66.0, "Omnivore", "Generalist", ["Asia"], "Theropod", "Gallimimus", "Ornithomimidae", "Nemegt", "Mongolia", "gallimimus.jpg", "galli_fossil.jpg", "Found 1965.", "Very fast runner.", 6.0, 2.0, 440, "Ostrich-like."],
    ["Majungasaurus", "Majungasaurus crenatissimus", "Mahajanga lizard", "Late Cretaceous", 70.0, 66.0, "Carnivore", "Apex predator", ["Africa"], "Theropod", "Majungasaurus", "Abelisauridae", "Maevarano", "Madagascar", "majungasaurus.jpg", "majunga_fossil.jpg", "Found 1896.", "Evidence of cannibalism.", 7.0, 2.0, 1100, "Top predator of Madagascar."],
    ["Baryonyx", "Baryonyx walkeri", "Heavy claw", "Early Cretaceous", 130.0, 125.0, "Carnivore", "Piscivore", ["Europe"], "Theropod", "Baryonyx", "Spinosauridae", "Wealden", "UK", "baryonyx.jpg", "baryonyx_fossil.jpg", "Found 1983.", "Crocodile-like snout.", 8.5, 2.5, 1200, "Fish eater."],
    ["Acrocanthosaurus", "Acrocanthosaurus atokensis", "High-spined lizard", "Early Cretaceous", 115.0, 105.0, "Carnivore", "Apex predator", ["North America"], "Theropod", "Acrocanthosaurus", "Carcharodontosauridae", "Antlers", "USA", "acrocantho.jpg", "acro_fossil.jpg", "Found 1940.", "Tall neural spines.", 11.5, 3.5, 6200, "Large predator."],
    ["Dromaeosaurus", "Dromaeosaurus albertensis", "Running lizard", "Late Cretaceous", 77.0, 74.0, "Carnivore", "Small prey", ["North America"], "Theropod", "Dromaeosaurus", "Dromaeosauridae", "Dinosaur Park", "Canada", "dromaeosaurus.jpg", "dromaeo_fossil.jpg", "Found 1914.", "Robust jaws.", 2.0, 0.6, 15, "Small but powerful."],
    ["Troodon", "Troodon formosus", "Wounding tooth", "Late Cretaceous", 77.0, 74.0, "Carnivore", "Small prey", ["North America"], "Theropod", "Troodon", "Troodontidae", "Judith River", "USA", "troodon.jpg", "troodon_fossil.jpg", "Found 1856.", "Large brain size.", 2.4, 0.9, 50, "Intelligent."],
    ["Gorgosaurus", "Gorgosaurus libratus", "Dreadful lizard", "Late Cretaceous", 76.6, 75.1, "Carnivore", "Apex predator", ["North America"], "Theropod", "Gorgosaurus", "Tyrannosauridae", "Dinosaur Park", "Canada", "gorgosaurus.jpg", "gorgo_fossil.jpg", "Found 1914.", "Lived alongside Daspletosaurus.", 9.0, 3.0, 2500, "Fast runner."],
    ["Daspletosaurus", "Daspletosaurus torosus", "Frightful lizard", "Late Cretaceous", 77.0, 74.0, "Carnivore", "Apex predator", ["North America"], "Theropod", "Daspletosaurus", "Tyrannosauridae", "Oldman", "Canada", "daspletosaurus.jpg", "daspleto_fossil.jpg", "Found 1921.", "Robust tyrannosaurid.", 9.0, 3.0, 2500, "Apex predator."],

    # Ceratopsians
    ["Triceratops", "Triceratops horridus", "Three-horned face", "Late Cretaceous", 68.0, 66.0, "Herbivore", "Low browser", ["North America"], "Ceratopsian", "Triceratops", "Ceratopsidae", "Hell Creek", "USA", "triceratops.jpg", "trike_fossil.jpg", "Found 1887.", "Fought T. rex.", 9.0, 3.0, 9000, "Very common fossil."],
    ["Protoceratops", "Protoceratops andrewsi", "First horned face", "Late Cretaceous", 75.0, 71.0, "Herbivore", "Low browser", ["Asia"], "Ceratopsian", "Protoceratops", "Protoceratopsidae", "Djadochta", "Mongolia", "protoceratops.jpg", "proto_fossil.jpg", "Found 1922.", "Found locked in combat with Velociraptor.", 1.8, 0.6, 180, "Sheep-sized."],
    ["Styracosaurus", "Styracosaurus albertensis", "Spiked lizard", "Late Cretaceous", 75.5, 75.0, "Herbivore", "Low browser", ["North America"], "Ceratopsian", "Styracosaurus", "Ceratopsidae", "Dinosaur Park", "Canada", "styracosaurus.jpg", "styraco_fossil.jpg", "Found 1913.", "Elaborate frill spikes.", 5.5, 1.8, 1800, "Spectacular frill."],
    ["Pachyrhinosaurus", "Pachyrhinosaurus lakustai", "Thick-nosed lizard", "Late Cretaceous", 73.5, 69.0, "Herbivore", "Low browser", ["North America"], "Ceratopsian", "Pachyrhinosaurus", "Ceratopsidae", "Wapiti", "Canada", "pachyrhino.jpg", "pachyrhino_fossil.jpg", "Found 1946.", "Boss on nose instead of horn.", 8.0, 2.0, 4000, "Herd animal."],
    ["Centrosaurus", "Centrosaurus apertus", "Pointed lizard", "Late Cretaceous", 76.5, 75.5, "Herbivore", "Low browser", ["North America"], "Ceratopsian", "Centrosaurus", "Ceratopsidae", "Dinosaur Park", "Canada", "centrosaurus.jpg", "centro_fossil.jpg", "Found 1904.", "Large bonebeds found.", 6.0, 2.0, 2000, "Single large nasal horn."],
    ["Chasmosaurus", "Chasmosaurus belli", "Opening lizard", "Late Cretaceous", 76.5, 75.5, "Herbivore", "Low browser", ["North America"], "Ceratopsian", "Chasmosaurus", "Ceratopsidae", "Dinosaur Park", "Canada", "chasmosaurus.jpg", "chasmo_fossil.jpg", "Found 1914.", "Very large frill fenestrae.", 4.8, 1.5, 1500, "Elongated frill."],
    ["Psittacosaurus", "Psittacosaurus mongoliensis", "Parrot lizard", "Early Cretaceous", 126.0, 101.0, "Herbivore", "Low browser", ["Asia"], "Ceratopsian", "Psittacosaurus", "Psittacosauridae", "Yixian", "China", "psittacosaurus.jpg", "psittaco_fossil.jpg", "Found 1922.", "Tail bristles.", 2.0, 0.6, 20, "Bipedal."],
    ["Pentaceratops", "Pentaceratops sternbergii", "Five-horned face", "Late Cretaceous", 76.0, 73.0, "Herbivore", "Low browser", ["North America"], "Ceratopsian", "Pentaceratops", "Ceratopsidae", "Kirtland", "USA", "pentaceratops.jpg", "penta_fossil.jpg", "Found 1921.", "Huge skull.", 6.0, 2.5, 4000, "Prominent cheek horns."],
    ["Diabloceratops", "Diabloceratops eatoni", "Devil horned face", "Late Cretaceous", 81.0, 79.0, "Herbivore", "Low browser", ["North America"], "Ceratopsian", "Diabloceratops", "Ceratopsidae", "Wahweap", "USA", "diabloceratops.jpg", "diablo_fossil.jpg", "Found 2002.", "Devilish horns.", 5.5, 2.0, 1500, "Basal centrosaurine."],
    ["Kosmoceratops", "Kosmoceratops richardsoni", "Ornate horned face", "Late Cretaceous", 76.0, 75.9, "Herbivore", "Low browser", ["North America"], "Ceratopsian", "Kosmoceratops", "Ceratopsidae", "Kaiparowits", "USA", "kosmoceratops.jpg", "kosmo_fossil.jpg", "Found 2006.", "15 horns on skull.", 4.5, 1.5, 1200, "Most ornate skull."],
    ["Zuniceratops", "Zuniceratops christopheri", "Zuni horned face", "Late Cretaceous", 92.0, 89.0, "Herbivore", "Low browser", ["North America"], "Ceratopsian", "Zuniceratops", "Ceratopsidae", "Moreno Hill", "USA", "zuniceratops.jpg", "zuni_fossil.jpg", "Found 1996.", "Earliest with brow horns.", 3.0, 1.0, 100, "Small and early."],
    ["Sinoceratops", "Sinoceratops zhuchengensis", "Chinese horned face", "Late Cretaceous", 73.5, 71.0, "Herbivore", "Low browser", ["Asia"], "Ceratopsian", "Sinoceratops", "Ceratopsidae", "Xingezhuang", "China", "sinoceratops.jpg", "sino_fossil.jpg", "Found 2010.", "Only known ceratopsid outside North America.", 6.0, 2.0, 2000, "Unique frill."],
    ["Einiosaurus", "Einiosaurus procurvicornis", "Buffalo lizard", "Late Cretaceous", 74.5, 74.0, "Herbivore", "Low browser", ["North America"], "Ceratopsian", "Einiosaurus", "Ceratopsidae", "Two Medicine", "USA", "einiosaurus.jpg", "einio_fossil.jpg", "Found 1985.", "Forward-curving nasal horn.", 4.5, 1.5, 1300, "Herd dweller."],
    ["Achelousaurus", "Achelousaurus horneri", "Achelous lizard", "Late Cretaceous", 74.2, 74.0, "Herbivore", "Low browser", ["North America"], "Ceratopsian", "Achelousaurus", "Ceratopsidae", "Two Medicine", "USA", "achelousaurus.jpg", "achelo_fossil.jpg", "Found 1987.", "Bosses instead of horns.", 6.0, 2.0, 1500, "Transitional form."],
    ["Nasutoceratops", "Nasutoceratops titusi", "Large-nosed horned face", "Late Cretaceous", 76.0, 75.5, "Herbivore", "Low browser", ["North America"], "Ceratopsian", "Nasutoceratops", "Ceratopsidae", "Kaiparowits", "USA", "nasutoceratops.jpg", "nasuto_fossil.jpg", "Found 2006.", "Bull-like horns.", 4.5, 1.5, 1500, "Short snout."],

    # Ornithopods / Hadrosaurs
    ["Parasaurolophus", "Parasaurolophus walkeri", "Near crested lizard", "Late Cretaceous", 76.5, 73.0, "Herbivore", "Browser", ["North America"], "Ornithopod", "Parasaurolophus", "Hadrosauridae", "Dinosaur Park", "Canada", "parasaurolophus.jpg", "para_fossil.jpg", "Found 1920.", "Long tubular crest.", 10.0, 3.0, 3000, "Iconic crest."],
    ["Iguanodon", "Iguanodon bernissartensis", "Iguana tooth", "Early Cretaceous", 126.0, 122.0, "Herbivore", "Browser", ["Europe"], "Ornithopod", "Iguanodon", "Iguanodontidae", "Sainte-Barbe Clays", "Belgium", "iguanodon.jpg", "iguano_fossil.jpg", "Found 1822.", "Thumb spike.", 10.0, 3.0, 3000, "One of the first dinosaurs named."],
    ["Edmontosaurus", "Edmontosaurus annectens", "Edmonton lizard", "Late Cretaceous", 73.0, 66.0, "Herbivore", "Browser", ["North America"], "Ornithopod", "Edmontosaurus", "Hadrosauridae", "Hell Creek", "USA", "edmontosaurus.jpg", "edmonto_fossil.jpg", "Found 1917.", "Mummified skin found.", 12.0, 3.0, 4000, "Very common."],
    ["Corythosaurus", "Corythosaurus casuarius", "Helmet lizard", "Late Cretaceous", 77.0, 75.7, "Herbivore", "Browser", ["North America"], "Ornithopod", "Corythosaurus", "Hadrosauridae", "Dinosaur Park", "Canada", "corythosaurus.jpg", "corytho_fossil.jpg", "Found 1912.", "Helmet-like crest.", 9.0, 3.0, 3000, "Cassowary-like crest."],
    ["Maiasaura", "Maiasaura peeblesorum", "Good mother lizard", "Late Cretaceous", 76.7, 76.7, "Herbivore", "Browser", ["North America"], "Ornithopod", "Maiasaura", "Hadrosauridae", "Two Medicine", "USA", "maiasaura.jpg", "maia_fossil.jpg", "Found 1978.", "Cared for its young.", 9.0, 3.0, 2500, "Egg Mountain site."],
    ["Tsintaosaurus", "Tsintaosaurus spinorhinus", "Qingdao lizard", "Late Cretaceous", 72.0, 70.0, "Herbivore", "Browser", ["Asia"], "Ornithopod", "Tsintaosaurus", "Hadrosauridae", "Wangshi", "China", "tsintaosaurus.jpg", "tsintao_fossil.jpg", "Found 1958.", "Unicorn-like crest.", 8.3, 3.0, 2500, "Distinctive crest."],
    ["Lambeosaurus", "Lambeosaurus lambei", "Lambe's lizard", "Late Cretaceous", 76.0, 75.0, "Herbivore", "Browser", ["North America"], "Ornithopod", "Lambeosaurus", "Hadrosauridae", "Dinosaur Park", "Canada", "lambeosaurus.jpg", "lambeo_fossil.jpg", "Found 1923.", "Hatchet-shaped crest.", 15.0, 4.0, 3300, "Large crest."],
    ["Muttaburrasaurus", "Muttaburrasaurus langdoni", "Muttaburra lizard", "Early Cretaceous", 105.0, 103.0, "Herbivore", "Browser", ["Australia"], "Ornithopod", "Muttaburrasaurus", "Rhabdodontomorpha", "Mackunda", "Australia", "muttaburra.jpg", "mutta_fossil.jpg", "Found 1963.", "Enlarged snout.", 8.0, 2.5, 2800, "Australian dinosaur."],
    ["Ouranosaurus", "Ouranosaurus nigeriensis", "Brave monitor lizard", "Early Cretaceous", 125.0, 112.0, "Herbivore", "Browser", ["Africa"], "Ornithopod", "Ouranosaurus", "Iguanodontia", "Echkar", "Niger", "ouranosaurus.jpg", "ourano_fossil.jpg", "Found 1965.", "Sail on back.", 7.0, 2.0, 2200, "Sail-backed ornithopod."],
    ["Saurolophus", "Saurolophus osborni", "Lizard crest", "Late Cretaceous", 70.0, 68.0, "Herbivore", "Browser", ["North America", "Asia"], "Ornithopod", "Saurolophus", "Hadrosauridae", "Horseshoe Canyon", "Canada", "saurolophus.jpg", "sauro_fossil.jpg", "Found 1912.", "Spike-like crest.", 9.8, 3.0, 2500, "Found in multiple continents."],
    ["Olorotitan", "Olorotitan arharensis", "Giant swan", "Late Cretaceous", 72.0, 66.0, "Herbivore", "Browser", ["Asia"], "Ornithopod", "Olorotitan", "Hadrosauridae", "Udurchukan", "Russia", "olorotitan.jpg", "oloro_fossil.jpg", "Found 2003.", "Fan-like crest.", 8.0, 3.0, 2500, "Long neck."],
    ["Shantungosaurus", "Shantungosaurus giganteus", "Shandong lizard", "Late Cretaceous", 78.0, 73.0, "Herbivore", "Browser", ["Asia"], "Ornithopod", "Shantungosaurus", "Hadrosauridae", "Wangshi", "China", "shantungosaurus.jpg", "shantungo_fossil.jpg", "Found 1973.", "Largest hadrosaur.", 16.6, 4.0, 16000, "Massive size."],
    ["Tenontosaurus", "Tenontosaurus tilletti", "Sinew lizard", "Early Cretaceous", 115.0, 108.0, "Herbivore", "Browser", ["North America"], "Ornithopod", "Tenontosaurus", "Iguanodontia", "Cloverly", "USA", "tenontosaurus.jpg", "tenonto_fossil.jpg", "Found 1970.", "Preyed upon by Deinonychus.", 6.5, 2.0, 1000, "Very long tail."],
    ["Hypsilophodon", "Hypsilophodon foxii", "High-crested tooth", "Early Cretaceous", 130.0, 125.0, "Herbivore", "Browser", ["Europe"], "Ornithopod", "Hypsilophodon", "Hypsilophodontidae", "Wessex", "UK", "hypsilophodon.jpg", "hypsi_fossil.jpg", "Found 1849.", "Agile runner.", 2.0, 0.6, 20, "Small and fast."],
    ["Thescelosaurus", "Thescelosaurus neglectus", "Wonderful lizard", "Late Cretaceous", 68.0, 66.0, "Herbivore", "Browser", ["North America"], "Ornithopod", "Thescelosaurus", "Thescelosauridae", "Hell Creek", "USA", "thescelosaurus.jpg", "thescelo_fossil.jpg", "Found 1891.", "Possible fossilized heart found.", 4.0, 1.0, 300, "Robust build."],

    # Ankylosaurs / Nodosaurs
    ["Ankylosaurus", "Ankylosaurus magniventris", "Fused lizard", "Late Cretaceous", 68.0, 66.0, "Herbivore", "Low browser", ["North America"], "Ankylosaur", "Ankylosaurus", "Ankylosauridae", "Hell Creek", "USA", "ankylosaurus.jpg", "ankylo_fossil.jpg", "Found 1906.", "Heavy tail club.", 8.0, 1.7, 6000, "Heavily armored."],
    ["Edmontonia", "Edmontonia longiceps", "From Edmonton", "Late Cretaceous", 76.5, 69.5, "Herbivore", "Low browser", ["North America"], "Ankylosaur", "Edmontonia", "Nodosauridae", "Horseshoe Canyon", "Canada", "edmontonia.jpg", "edmontonia_fossil.jpg", "Found 1928.", "Forward-pointing shoulder spikes.", 6.6, 2.0, 3000, "Lacked tail club."],
    ["Borealopelta", "Borealopelta markmitchelli", "Northern shield", "Early Cretaceous", 112.0, 110.0, "Herbivore", "Low browser", ["North America"], "Ankylosaur", "Borealopelta", "Nodosauridae", "Clearwater", "Canada", "borealopelta.jpg", "boreal_fossil.jpg", "Found 2011.", "Exceptional preservation.", 5.5, 1.5, 1300, "Countershading coloration."],
    ["Euoplocephalus", "Euoplocephalus tutus", "Well-armed head", "Late Cretaceous", 76.4, 75.6, "Herbivore", "Low browser", ["North America"], "Ankylosaur", "Euoplocephalus", "Ankylosauridae", "Dinosaur Park", "Canada", "euoplocephalus.jpg", "euoplo_fossil.jpg", "Found 1897.", "Armored eyelids.", 6.0, 2.0, 2500, "Common in Alberta."],
    ["Sauropelta", "Sauropelta edwardsorum", "Lizard shield", "Early Cretaceous", 115.0, 110.0, "Herbivore", "Low browser", ["North America"], "Ankylosaur", "Sauropelta", "Nodosauridae", "Cloverly", "USA", "sauropelta.jpg", "sauropelta_fossil.jpg", "Found 1970.", "Huge neck spines.", 5.2, 1.5, 1500, "Long tail."],
    ["Nodosaurus", "Nodosaurus textilis", "Knobbed lizard", "Late Cretaceous", 100.5, 93.9, "Herbivore", "Low browser", ["North America"], "Ankylosaur", "Nodosaurus", "Nodosauridae", "Frontier", "USA", "nodosaurus.jpg", "nodo_fossil.jpg", "Found 1889.", "Rows of bony knobs.", 5.0, 1.5, 1500, "First named nodosaur."],
    ["Pinacosaurus", "Pinacosaurus grangeri", "Plank lizard", "Late Cretaceous", 80.0, 75.0, "Herbivore", "Low browser", ["Asia"], "Ankylosaur", "Pinacosaurus", "Ankylosauridae", "Djadochta", "Mongolia", "pinacosaurus.jpg", "pinaco_fossil.jpg", "Found 1923.", "Lightly built for an ankylosaur.", 5.0, 1.5, 1900, "Found in groups."],
    ["Tarchia", "Tarchia kielanae", "Brainy one", "Late Cretaceous", 75.0, 70.0, "Herbivore", "Low browser", ["Asia"], "Ankylosaur", "Tarchia", "Ankylosauridae", "Barun Goyot", "Mongolia", "tarchia.jpg", "tarchia_fossil.jpg", "Found 1977.", "Large braincase.", 8.0, 2.0, 2500, "Asian ankylosaur."],
    ["Polacanthus", "Polacanthus foxii", "Many thorns", "Early Cretaceous", 130.0, 125.0, "Herbivore", "Low browser", ["Europe"], "Ankylosaur", "Polacanthus", "Nodosauridae", "Wessex", "UK", "polacanthus.jpg", "pola_fossil.jpg", "Found 1865.", "Large pelvic shield.", 5.0, 1.5, 1000, "Spiky armor."],
    ["Gastonia", "Gastonia burgei", "Gaston's lizard", "Early Cretaceous", 139.0, 125.0, "Herbivore", "Low browser", ["North America"], "Ankylosaur", "Gastonia", "Nodosauridae", "Cedar Mountain", "USA", "gastonia.jpg", "gastonia_fossil.jpg", "Found 1998.", "Sacral shield of armor.", 5.0, 1.5, 1900, "Very heavily armored."],

    # Pachycephalosaurs
    ["Pachycephalosaurus", "Pachycephalosaurus wyomingensis", "Thick-headed lizard", "Late Cretaceous", 68.0, 66.0, "Herbivore", "Browser", ["North America"], "Pachycephalosaur", "Pachycephalosaurus", "Pachycephalosauridae", "Hell Creek", "USA", "pachy.jpg", "pachy_fossil.jpg", "Found 1931.", "10-inch thick skull dome.", 4.5, 1.8, 450, "Headbutting is debated."],
    ["Stegoceras", "Stegoceras validum", "Horn roof", "Late Cretaceous", 77.5, 74.0, "Herbivore", "Browser", ["North America"], "Pachycephalosaur", "Stegoceras", "Pachycephalosauridae", "Dinosaur Park", "Canada", "stegoceras.jpg", "stego_fossil.jpg", "Found 1902.", "Well known dome.", 2.0, 0.8, 40, "Small dome-head."],
    ["Stygimoloch", "Stygimoloch spinifer", "Demon from the River Styx", "Late Cretaceous", 68.0, 66.0, "Herbivore", "Browser", ["North America"], "Pachycephalosaur", "Stygimoloch", "Pachycephalosauridae", "Hell Creek", "USA", "stygimoloch.jpg", "stygi_fossil.jpg", "Found 1983.", "Long spikes on head.", 3.0, 1.0, 78, "Possibly juvenile Pachycephalosaurus."],
    ["Dracorex", "Dracorex hogwartsia", "Dragon king of Hogwarts", "Late Cretaceous", 68.0, 66.0, "Herbivore", "Browser", ["North America"], "Pachycephalosaur", "Dracorex", "Pachycephalosauridae", "Hell Creek", "USA", "dracorex.jpg", "draco_fossil.jpg", "Found 2004.", "Flat skull with spikes.", 3.0, 1.0, 78, "Possibly juvenile Pachycephalosaurus."],
    ["Prenocephale", "Prenocephale prenes", "Sloping head", "Late Cretaceous", 70.0, 66.0, "Herbivore", "Browser", ["Asia"], "Pachycephalosaur", "Prenocephale", "Pachycephalosauridae", "Nemegt", "Mongolia", "prenocephale.jpg", "preno_fossil.jpg", "Found 1974.", "Prominent brow row of spikes.", 2.4, 1.0, 130, "Asian pachycephalosaur."],

    # Sauropods
    ["Argentinosaurus", "Argentinosaurus huinculensis", "Argentine lizard", "Late Cretaceous", 96.0, 92.0, "Herbivore", "High browser", ["South America"], "Sauropod", "Argentinosaurus", "Titanosauria", "Huincul", "Argentina", "argentinosaurus.jpg", "arg_fossil.jpg", "Found 1989.", "One of the largest land animals.", 30.0, 8.0, 75000, "Colossal size."],
    ["Alamosaurus", "Alamosaurus sanjuanensis", "Ojo Alamo lizard", "Late Cretaceous", 70.0, 66.0, "Herbivore", "High browser", ["North America"], "Sauropod", "Alamosaurus", "Titanosauria", "Ojo Alamo", "USA", "alamosaurus.jpg", "alamo_fossil.jpg", "Found 1922.", "Only late Cretaceous NA titanosaur.", 30.0, 8.0, 70000, "Massive North American sauropod."],
    ["Saltasaurus", "Saltasaurus loricatus", "Lizard from Salta", "Late Cretaceous", 70.0, 66.0, "Herbivore", "High browser", ["South America"], "Sauropod", "Saltasaurus", "Titanosauria", "Lecho", "Argentina", "saltasaurus.jpg", "salta_fossil.jpg", "Found 1980.", "First armored sauropod found.", 12.8, 3.0, 7000, "Osteoderms on back."],
    ["Amargasaurus", "Amargasaurus cazaui", "La Amarga lizard", "Early Cretaceous", 129.4, 122.46, "Herbivore", "Low browser", ["South America"], "Sauropod", "Amargasaurus", "Dicraeosauridae", "La Amarga", "Argentina", "amargasaurus.jpg", "amarga_fossil.jpg", "Found 1984.", "Double row of neck spines.", 10.0, 2.7, 2600, "Bizarre neck anatomy."],
    ["Dreadnoughtus", "Dreadnoughtus schrani", "Fears nothing", "Late Cretaceous", 76.0, 70.0, "Herbivore", "High browser", ["South America"], "Sauropod", "Dreadnoughtus", "Titanosauria", "Cerro Fortaleza", "Argentina", "dreadnoughtus.jpg", "dread_fossil.jpg", "Found 2005.", "Most complete giant titanosaur.", 26.0, 6.0, 59000, "Astounding weight."],
    ["Patagotitan", "Patagotitan mayorum", "Patagonian titan", "Early Cretaceous", 101.6, 95.0, "Herbivore", "High browser", ["South America"], "Sauropod", "Patagotitan", "Titanosauria", "Cerro Barcino", "Argentina", "patagotitan.jpg", "patago_fossil.jpg", "Found 2010.", "Competes for largest animal.", 37.0, 8.0, 69000, "Incredible length."],
    ["Paralititan", "Paralititan stromeri", "Tidal giant", "Late Cretaceous", 98.0, 93.0, "Herbivore", "High browser", ["Africa"], "Sauropod", "Paralititan", "Titanosauria", "Bahariya", "Egypt", "paralititan.jpg", "parali_fossil.jpg", "Found 2001.", "Lived in mangrove swamps.", 26.0, 7.0, 59000, "Massive African titanosaur."],
    ["Rapetosaurus", "Rapetosaurus krausei", "Giant mischief maker", "Late Cretaceous", 70.0, 66.0, "Herbivore", "High browser", ["Africa"], "Sauropod", "Rapetosaurus", "Titanosauria", "Maevarano", "Madagascar", "rapetosaurus.jpg", "rapeto_fossil.jpg", "Found 2001.", "Most complete titanosaur skull.", 15.0, 4.0, 12000, "Madagascar native."],
    ["Isisaurus", "Isisaurus colberti", "ISI lizard", "Late Cretaceous", 70.0, 66.0, "Herbivore", "High browser", ["Asia"], "Sauropod", "Isisaurus", "Titanosauria", "Lameta", "India", "isisaurus.jpg", "isi_fossil.jpg", "Found 1997.", "Coprolites suggest varied diet.", 18.0, 5.0, 14000, "Indian titanosaur."],
    ["Magyarosaurus", "Magyarosaurus dacus", "Magyar lizard", "Late Cretaceous", 72.0, 66.0, "Herbivore", "High browser", ["Europe"], "Sauropod", "Magyarosaurus", "Titanosauria", "Sânpetru", "Romania", "magyarosaurus.jpg", "magyaro_fossil.jpg", "Found 1915.", "Insular dwarfism.", 6.0, 2.0, 1000, "Pony-sized sauropod."],

    # Pterosaurs
    ["Quetzalcoatlus", "Quetzalcoatlus northropi", "Feathered serpent god", "Late Cretaceous", 68.0, 66.0, "Carnivore", "Small animals", ["North America"], "Pterosaur", "Quetzalcoatlus", "Azhdarchidae", "Javelina", "USA", "quetzalcoatlus.jpg", "quetz_fossil.jpg", "Found 1971.", "One of the largest flying animals.", 11.0, 5.0, 250, "Giraffe-sized."],
    ["Pteranodon", "Pteranodon longiceps", "Toothless wing", "Late Cretaceous", 88.0, 80.5, "Carnivore", "Piscivore", ["North America"], "Pterosaur", "Pteranodon", "Pteranodontidae", "Niobrara", "USA", "pteranodon.jpg", "pteranodon_fossil.jpg", "Found 1870.", "Distinctive head crest.", 6.0, 1.8, 36, "Flew over the Western Interior Seaway."],
    ["Tapejara", "Tapejara wellnhoferi", "Old being", "Early Cretaceous", 112.0, 108.0, "Omnivore", "Frugivore", ["South America"], "Pterosaur", "Tapejara", "Tapejaridae", "Santana", "Brazil", "tapejara.jpg", "tapejara_fossil.jpg", "Found 1989.", "Semicircular crest.", 3.0, 1.0, 5, "Colorful crest likely."],
    ["Tupandactylus", "Tupandactylus imperator", "Tupan finger", "Early Cretaceous", 112.0, 108.0, "Herbivore", "Frugivore", ["South America"], "Pterosaur", "Tupandactylus", "Tapejaridae", "Crato", "Brazil", "tupandactylus.jpg", "tupan_fossil.jpg", "Found 1997.", "Massive sail-like crest.", 5.0, 1.5, 10, "Huge soft-tissue crest."],
    ["Pterodaustro", "Pterodaustro guinazui", "Southern wing", "Early Cretaceous", 105.0, 105.0, "Carnivore", "Filter feeder", ["South America"], "Pterosaur", "Pterodaustro", "Ctenochasmatidae", "Lagarcito", "Argentina", "pterodaustro.jpg", "pterodaustro_fossil.jpg", "Found 1970.", "Flamingo-like filter bristles.", 2.5, 0.5, 3, "Strained plankton."],
    ["Nyctosaurus", "Nyctosaurus gracilis", "Night lizard", "Late Cretaceous", 85.0, 84.5, "Carnivore", "Piscivore", ["North America"], "Pterosaur", "Nyctosaurus", "Nyctosauridae", "Niobrara", "USA", "nyctosaurus.jpg", "nycto_fossil.jpg", "Found 1876.", "Lost its wing fingers.", 2.0, 0.5, 2, "Gigantic antler-like crest."],
    ["Ornithocheirus", "Ornithocheirus simus", "Bird hand", "Early Cretaceous", 110.0, 105.0, "Carnivore", "Piscivore", ["Europe"], "Pterosaur", "Ornithocheirus", "Ornithocheiridae", "Cambridge Greensand", "UK", "ornithocheirus.jpg", "ornitho_fossil.jpg", "Found 1869.", "Keel on upper jaw.", 5.0, 1.5, 20, "Soaring fisher."],
    ["Anhanguera", "Anhanguera blittersdorffi", "Old devil", "Early Cretaceous", 112.0, 108.0, "Carnivore", "Piscivore", ["South America"], "Pterosaur", "Anhanguera", "Anhangueridae", "Santana", "Brazil", "anhanguera.jpg", "anhang_fossil.jpg", "Found 1985.", "Rounded crests on jaw tips.", 4.5, 1.2, 15, "Fish-eating specialist."],
    ["Hatzegopteryx", "Hatzegopteryx thambema", "Hațeg basin wing", "Late Cretaceous", 72.0, 66.0, "Carnivore", "Apex predator", ["Europe"], "Pterosaur", "Hatzegopteryx", "Azhdarchidae", "Densuș-Ciula", "Romania", "hatzegopteryx.jpg", "hatzego_fossil.jpg", "Found 2002.", "Robust neck.", 11.0, 5.0, 250, "Top predator of its island."],
    ["Azhdarcho", "Azhdarcho lancicollis", "Dragon", "Late Cretaceous", 92.0, 90.0, "Carnivore", "Small animals", ["Asia"], "Pterosaur", "Azhdarcho", "Azhdarchidae", "Bissekty", "Uzbekistan", "azhdarcho.jpg", "azhdarcho_fossil.jpg", "Found 1984.", "Namesake of Azhdarchids.", 4.5, 2.0, 50, "Stork-like proportions."],

    # Marine Reptiles & Aquatic
    ["Mosasaurus", "Mosasaurus hoffmannii", "Meuse river lizard", "Late Cretaceous", 82.0, 66.0, "Carnivore", "Apex predator", ["Europe", "North America"], "Marine Reptile", "Mosasaurus", "Mosasauridae", "Maastricht", "Netherlands", "mosasaurus.jpg", "mosa_fossil.jpg", "Found 1764.", "First major marine reptile discovered.", 15.0, 2.0, 14000, "Apex marine predator."],
    ["Elasmosaurus", "Elasmosaurus platyurus", "Thin-plate lizard", "Late Cretaceous", 80.5, 80.5, "Carnivore", "Piscivore", ["North America"], "Marine Reptile", "Elasmosaurus", "Elasmosauridae", "Pierre Shale", "USA", "elasmosaurus.jpg", "elasmo_fossil.jpg", "Found 1868.", "Extremely long neck.", 10.3, 1.5, 2000, "71 neck vertebrae."],
    ["Kronosaurus", "Kronosaurus queenslandicus", "Kronos lizard", "Early Cretaceous", 120.0, 100.0, "Carnivore", "Apex predator", ["Australia"], "Marine Reptile", "Kronosaurus", "Pliosauridae", "Toolebuc", "Australia", "kronosaurus.jpg", "krono_fossil.jpg", "Found 1889.", "Massive jaws and teeth.", 10.0, 2.0, 11000, "Fierce pliosaur."],
    ["Tylosaurus", "Tylosaurus proriger", "Knob lizard", "Late Cretaceous", 86.0, 75.0, "Carnivore", "Apex predator", ["North America"], "Marine Reptile", "Tylosaurus", "Mosasauridae", "Niobrara", "USA", "tylosaurus.jpg", "tylo_fossil.jpg", "Found 1868.", "Long, cylindrical snout.", 14.0, 2.0, 8000, "Large mosasaur."],
    ["Aristonectes", "Aristonectes quiriquinensis", "Best swimmer", "Late Cretaceous", 70.0, 66.0, "Carnivore", "Filter feeder", ["South America"], "Marine Reptile", "Aristonectes", "Elasmosauridae", "Quiriquina", "Chile", "aristonectes.jpg", "aristo_fossil.jpg", "Found 1941.", "Filter-feeding plesiosaur.", 10.0, 2.0, 4000, "Dense tooth array."],
    ["Prognathodon", "Prognathodon solvayi", "Forejaw tooth", "Late Cretaceous", 83.6, 66.0, "Carnivore", "Hard-shelled prey", ["Europe"], "Marine Reptile", "Prognathodon", "Mosasauridae", "Maastricht", "Belgium", "prognathodon.jpg", "prog_fossil.jpg", "Found 1889.", "Crushing teeth.", 10.0, 1.5, 5000, "Ate ammonites."],
    ["Platecarpus", "Platecarpus tympaniticus", "Flat wrist", "Late Cretaceous", 84.0, 81.0, "Carnivore", "Piscivore", ["North America"], "Marine Reptile", "Platecarpus", "Mosasauridae", "Niobrara", "USA", "platecarpus.jpg", "plate_fossil.jpg", "Found 1869.", "Shark-like tail fluke.", 4.3, 1.0, 400, "Medium mosasaur."],
    ["Dolichorhynchops", "Dolichorhynchops osborni", "Long-snouted face", "Late Cretaceous", 93.5, 70.6, "Carnivore", "Piscivore", ["North America"], "Marine Reptile", "Dolichorhynchops", "Polycotylidae", "Niobrara", "USA", "dolicho.jpg", "dolicho_fossil.jpg", "Found 1902.", "Short-necked plesiosaur.", 3.0, 0.8, 1000, "Penguin-like underwater flight."],
    ["Archelon", "Archelon ischyros", "Ruler turtle", "Late Cretaceous", 80.2, 74.0, "Carnivore", "Jellyfish", ["North America"], "Marine Reptile", "Archelon", "Protostegidae", "Pierre Shale", "USA", "archelon.jpg", "archelon_fossil.jpg", "Found 1895.", "Largest turtle ever.", 4.0, 1.0, 2200, "Leathery shell."],
    ["Deinosuchus", "Deinosuchus riograndensis", "Terrible crocodile", "Late Cretaceous", 82.0, 73.0, "Carnivore", "Apex predator", ["North America"], "Reptile", "Deinosuchus", "Alligatoroidea", "Aguja", "USA", "deinosuchus.jpg", "deino_croc_fossil.jpg", "Found 1858.", "Preyed on dinosaurs.", 10.6, 1.5, 5000, "Massive crocodilian."],

    # Fish and Invertebrates
    ["Xiphactinus", "Xiphactinus audax", "Sword ray", "Late Cretaceous", 90.0, 66.0, "Carnivore", "Piscivore", ["North America"], "Fish", "Xiphactinus", "Ichthyodectidae", "Niobrara", "USA", "xiphactinus.jpg", "xiph_fossil.jpg", "Found 1850.", "Fossil found with whole fish in stomach.", 6.0, 1.5, 500, "Bulldog fish."],
    ["Cretoxyrhina", "Cretoxyrhina mantelli", "Cretaceous sharp-nose", "Late Cretaceous", 100.0, 82.0, "Carnivore", "Apex predator", ["North America"], "Fish", "Cretoxyrhina", "Cretoxyrhinidae", "Niobrara", "USA", "cretoxyrhina.jpg", "creto_fossil.jpg", "Found 1843.", "Ginsu shark.", 7.0, 1.5, 2000, "Preyed on marine reptiles."],
    ["Baculites", "Baculites compressus", "Walking stick rock", "Late Cretaceous", 99.0, 66.0, "Carnivore", "Plankton", ["Global"], "Invertebrate", "Baculites", "Baculitidae", "Pierre Shale", "USA", "baculites.jpg", "baculites_fossil.jpg", "Found 1820.", "Straight-shelled ammonite.", 2.0, 0.1, 5, "Very common."],
    ["Jeletzkytes", "Jeletzkytes nebrascensis", "Jeletzky's horn", "Late Cretaceous", 70.0, 66.0, "Carnivore", "Plankton", ["North America"], "Invertebrate", "Jeletzkytes", "Scaphitidae", "Fox Hills", "USA", "jeletzkytes.jpg", "jeletz_fossil.jpg", "Found 1965.", "Coiled ammonite.", 0.2, 0.2, 1, "Index fossil."],
    ["Tusoteuthis", "Tusoteuthis longa", "Crushed squid", "Late Cretaceous", 80.0, 70.0, "Carnivore", "Fish", ["North America"], "Invertebrate", "Tusoteuthis", "Tusoteuthididae", "Pierre Shale", "USA", "tusoteuthis.jpg", "tuso_fossil.jpg", "Found 1898.", "Giant squid relative.", 6.0, 0.5, 100, "Vampyromorph."],
    ["Enchodus", "Enchodus petrosus", "Spear tooth", "Late Cretaceous", 90.0, 66.0, "Carnivore", "Piscivore", ["Global"], "Fish", "Enchodus", "Enchodontidae", "Niobrara", "USA", "enchodus.jpg", "encho_fossil.jpg", "Found 1843.", "Saber-toothed herring.", 1.5, 0.3, 10, "Prominent fangs."],
    ["Ptychoceras", "Ptychoceras puzosianum", "Folded horn", "Early Cretaceous", 125.0, 112.0, "Carnivore", "Plankton", ["Europe"], "Invertebrate", "Ptychoceras", "Ptychoceratidae", "Aptian clays", "France", "ptychoceras.jpg", "ptycho_fossil.jpg", "Found 1842.", "Folded ammonite shell.", 0.2, 0.05, 0.5, "Odd U-shape."],

    # Early Mammals
    ["Repenomamus", "Repenomamus giganticus", "Reptile mammal", "Early Cretaceous", 125.0, 122.0, "Carnivore", "Small dinosaurs", ["Asia"], "Mammal", "Repenomamus", "Repenomamidae", "Yixian", "China", "repenomamus.jpg", "repeno_fossil.jpg", "Found 2000.", "Ate baby Psittacosaurus.", 1.0, 0.3, 14, "Largest Cretaceous mammal."],
    ["Didelphodon", "Didelphodon vorax", "Opossum tooth", "Late Cretaceous", 68.0, 66.0, "Carnivore", "Scavenger", ["North America"], "Mammal", "Didelphodon", "Stagodontidae", "Hell Creek", "USA", "didelphodon.jpg", "didelpho_fossil.jpg", "Found 1889.", "Badger-like marsupial relative.", 0.6, 0.2, 5, "Crushing teeth."],
    ["Eomaia", "Eomaia scansoria", "Dawn mother", "Early Cretaceous", 125.0, 125.0, "Insectivore", "Insects", ["Asia"], "Mammal", "Eomaia", "Eutheria", "Yixian", "China", "eomaia.jpg", "eomaia_fossil.jpg", "Found 2002.", "Early placental relative.", 0.1, 0.05, 0.02, "Tree climber."]
]

import os
os.makedirs(os.path.dirname("d:/My folders/AI 1.0/Prehistoric encylcopedia/backend/prisma/species_cretaceous.json"), exist_ok=True)

out = []
for row in rows[:100]:
    item = {keys[i]: row[i] for i in range(len(keys))}
    item["reconstructionImageUrl"] = "https://upload.wikimedia.org/wikipedia/commons/a/ab/" + item["reconstructionImageUrl"]
    item["fossilImageUrl"] = "https://upload.wikimedia.org/wikipedia/commons/a/ab/" + item["fossilImageUrl"]
    out.append(item)

with open("d:/My folders/AI 1.0/Prehistoric encylcopedia/backend/prisma/species_cretaceous.json", "w", encoding="utf-8") as f:
    json.dump(out, f, indent=2)
