const fs = require('fs');
const path = require('path');

const speciesJsonPath = path.join(__dirname, 'species.json');
const othersJsonPath = path.join(__dirname, 'species_others.json');

const rawData = fs.readFileSync(speciesJsonPath, 'utf8');
const originalSpecies = JSON.parse(rawData);

// Filter out Mesozoic species
const MesozoicEras = ['Triassic', 'Jurassic', 'Cretaceous', 'Late Triassic', 'Early Jurassic', 'Late Jurassic', 'Late Cretaceous'];
const nonMesozoic = originalSpecies.filter(s => {
  return !MesozoicEras.some(era => s.timePeriod.includes(era));
});

// Mapping of existing non-Mesozoic species to their new fields
const mapping = {
  "Anomalocaris canadensis": { genus: "Anomalocaris", family: "Anomalocarididae", fossilFormation: "Burgess Shale", country: "Canada" },
  "Hallucigenia sparsa": { genus: "Hallucigenia", family: "Hallucigeniidae", fossilFormation: "Burgess Shale", country: "Canada" },
  "Opabinia regalis": { genus: "Opabinia", family: "Opabiniidae", fossilFormation: "Burgess Shale", country: "Canada" },
  "Dunkleosteus terrelli": { genus: "Dunkleosteus", family: "Dunkleosteidae", fossilFormation: "Cleveland Shale", country: "United States" },
  "Tiktaalik roseae": { genus: "Tiktaalik", family: "Elpistostegidae", fossilFormation: "Fram Formation", country: "Canada" },
  "Ichthyostega stensioei": { genus: "Ichthyostega", family: "Ichthyostegidae", fossilFormation: "Britta Dal Formation", country: "Greenland" },
  "Arthropleura armata": { genus: "Arthropleura", family: "Arthropleuridae", fossilFormation: "Stellichte Formation", country: "Germany" },
  "Meganeura monyi": { genus: "Meganeura", family: "Meganeuridae", fossilFormation: "Commentry Shale", country: "France" },
  "Dimetrodon grandis": { genus: "Dimetrodon", family: "Sphenacodontidae", fossilFormation: "Red Beds of Texas", country: "United States" },
  "Edaphosaurus pogonias": { genus: "Edaphosaurus", family: "Edaphosauridae", fossilFormation: "Red Beds of Texas", country: "United States" },
  "Helicoprion bessonowi": { genus: "Helicoprion", family: "Helicoprionidae", fossilFormation: "Phosphoria Formation", country: "United States" },
  "Scutosaurus karpinskii": { genus: "Scutosaurus", family: "Pareiasauridae", fossilFormation: "Salarevo Formation", country: "Russia" },
  "Inostrancevia alexandri": { genus: "Inostrancevia", family: "Gorgonopsidae", fossilFormation: "Salarevo Formation", country: "Russia" },
  "Gastornis parisiensis": { genus: "Gastornis", family: "Gastornithidae", fossilFormation: "Meudon Marl", country: "France" },
  "Basilosaurus cetoides": { genus: "Basilosaurus", family: "Basilosauridae", fossilFormation: "Ocala Limestone", country: "United States" },
  "Megalodon": { genus: "Otodus", family: "Otodontidae", fossilFormation: "Yorktown Formation", country: "United States" },
  "Smilodon fatalis": { genus: "Smilodon", family: "Felidae", fossilFormation: "La Brea Tar Pits", country: "United States" },
  "Mammuthus primigenius": { genus: "Mammuthus", family: "Elephantidae", fossilFormation: "Permafrost deposits", country: "Russia" },
  "Megatherium americanum": { genus: "Megatherium", family: "Megatheriidae", fossilFormation: "Pampas Formation", country: "Argentina" },
  "Coelodonta antiquitatis": { genus: "Coelodonta", family: "Rhinocerotidae", fossilFormation: "Starunia deposits", country: "Ukraine" },
  "Doedicurus clavicaudatus": { genus: "Doedicurus", family: "Chlamyphoridae", fossilFormation: "Pampas Formation", country: "Argentina" },
  "Thylacoleo carnifex": { genus: "Thylacoleo", family: "Thylacoleonidae", fossilFormation: "Naracoorte Caves", country: "Australia" },
  "Diprotodon optatum": { genus: "Diprotodon", family: "Diprotodontidae", fossilFormation: "Lake Callabonna", country: "Australia" }
};

const updatedNonMesozoic = nonMesozoic.map(s => {
  const fields = mapping[s.name] || { genus: s.name.split(' ')[0], family: "Unknown", fossilFormation: null, country: null };
  return {
    ...s,
    ...fields
  };
});

// Add 13 new Paleozoic/Cenozoic species
const newSpecies = [
  {
    "name": "Pikaia gracilens",
    "scientificName": "Pikaia gracilens",
    "nameMeaning": "From Mount Pika",
    "timePeriod": "Middle Cambrian",
    "myaStart": 508.0,
    "myaEnd": 505.0,
    "dietType": "Omnivore",
    "dietDetails": "Likely fed on detritus and organic particles.",
    "locations": ["North America"],
    "taxonomicClassification": "Chordata -> Pikaia",
    "genus": "Pikaia",
    "family": "Pikaiidae",
    "fossilFormation": "Burgess Shale",
    "country": "Canada",
    "reconstructionImageUrl": "https://upload.wikimedia.org/wikipedia/commons/7/77/Pikaia_gracilens_reconstruction.jpg",
    "fossilImageUrl": "https://upload.wikimedia.org/wikipedia/commons/8/87/Pikaia_gracilens_fossil.jpg",
    "discoveryHistory": "Discovered by Charles Walcott in 1911 in the Burgess Shale.",
    "interestingFacts": ["One of the earliest known primitive chordates, a potential ancestor of all vertebrates.", "Possessed a proto-backbone called a notochord."],
    "lengthM": 0.05,
    "heightM": 0.01,
    "weightKg": 0.005,
    "sizeNotes": "Grew up to 5 centimeters in length.",
    "relatedSpeciesNames": []
  },
  {
    "name": "Wiwaxia corrugata",
    "scientificName": "Wiwaxia corrugata",
    "nameMeaning": "Corrugated Wiwaxia",
    "timePeriod": "Middle Cambrian",
    "myaStart": 508.0,
    "myaEnd": 505.0,
    "dietType": "Omnivore",
    "dietDetails": "Fed on detritus or micro-organisms on the seafloor.",
    "locations": ["North America"],
    "taxonomicClassification": "Lophotrochozoa -> Halwaxiida -> Wiwaxiidae -> Wiwaxia",
    "genus": "Wiwaxia",
    "family": "Wiwaxiidae",
    "fossilFormation": "Burgess Shale",
    "country": "Canada",
    "reconstructionImageUrl": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Wiwaxia_corrugata_reconstruction.jpg",
    "fossilImageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Wiwaxia_corrugata_fossil.jpg",
    "discoveryHistory": "First found in 1899 as a single spine; full specimens found by Walcott in 1911.",
    "interestingFacts": ["Body covered in scales (sclerites) and long defensive spines.", "Crept along the seafloor using a slug-like foot."],
    "lengthM": 0.05,
    "heightM": 0.02,
    "weightKg": 0.01,
    "sizeNotes": "Excluding spines, body length was around 5 cm.",
    "relatedSpeciesNames": []
  },
  {
    "name": "Bothriolepis canadensis",
    "scientificName": "Bothriolepis canadensis",
    "nameMeaning": "Trench scale from Canada",
    "timePeriod": "Late Devonian",
    "myaStart": 387.0,
    "myaEnd": 360.0,
    "dietType": "Omnivore",
    "dietDetails": "Mud-feeder, filtering organic detritus from bottom sediments.",
    "locations": ["North America"],
    "taxonomicClassification": "Placodermi -> Antiarchi -> Bothriolepididae -> Bothriolepis",
    "genus": "Bothriolepis",
    "family": "Bothriolepididae",
    "fossilFormation": "Escuminac Formation",
    "country": "Canada",
    "reconstructionImageUrl": "https://upload.wikimedia.org/wikipedia/commons/b/b3/Bothriolepis_canadensis_reconstruction.jpg",
    "fossilImageUrl": "https://upload.wikimedia.org/wikipedia/commons/2/23/Bothriolepis_canadensis_fossil.jpg",
    "discoveryHistory": "Discovered in Miguasha, Quebec, and described by Whiteaves in 1880.",
    "interestingFacts": ["Most widely distributed placoderm genus in the fossil record.", "Had heavily armored pectoral fins that could walk on muddy beds."],
    "lengthM": 0.3,
    "heightM": 0.1,
    "weightKg": 0.5,
    "sizeNotes": "Average length around 30 centimeters.",
    "relatedSpeciesNames": []
  },
  {
    "name": "Eusthenopteron foordi",
    "scientificName": "Eusthenopteron foordi",
    "nameMeaning": "Good stout fin",
    "timePeriod": "Late Devonian",
    "myaStart": 385.0,
    "myaEnd": 375.0,
    "dietType": "Carnivore",
    "dietDetails": "Hunted smaller fishes and invertebrates in shallow waters.",
    "locations": ["North America"],
    "taxonomicClassification": "Sarcopterygii -> Tetrapodomorpha -> Tristichopteridae -> Eusthenopteron",
    "genus": "Eusthenopteron",
    "family": "Tristichopteridae",
    "fossilFormation": "Escuminac Formation",
    "country": "Canada",
    "reconstructionImageUrl": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Eusthenopteron_foordi_reconstruction.jpg",
    "fossilImageUrl": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Eusthenopteron_foordi_fossil.jpg",
    "discoveryHistory": "Named by J.F. Whiteaves in 1881 based on Miguasha specimens.",
    "interestingFacts": ["A famous lobe-finned fish showing the transition from fish to land vertebrates.", "Internal fin bones directly correlate to limb bones of tetrapods."],
    "lengthM": 1.0,
    "heightM": 0.2,
    "weightKg": 3.0,
    "sizeNotes": "Standard length between 0.8 and 1.2 meters.",
    "relatedSpeciesNames": []
  },
  {
    "name": "Hylonomus lyelli",
    "scientificName": "Hylonomus lyelli",
    "nameMeaning": "Forest dweller",
    "timePeriod": "Carboniferous",
    "myaStart": 312.0,
    "myaEnd": 309.0,
    "dietType": "Carnivore",
    "dietDetails": "Fed on early insects, millipedes, and land snails.",
    "locations": ["North America"],
    "taxonomicClassification": "Reptilia -> Protorothyrididae -> Hylonomus",
    "genus": "Hylonomus",
    "family": "Protorothyrididae",
    "fossilFormation": "Joggins Formation",
    "country": "Canada",
    "reconstructionImageUrl": "https://upload.wikimedia.org/wikipedia/commons/f/ff/Hylonomus_lyelli_reconstruction.jpg",
    "fossilImageUrl": "https://upload.wikimedia.org/wikipedia/commons/b/b5/Hylonomus_lyelli_fossil.jpg",
    "discoveryHistory": "Discovered by John William Dawson in Nova Scotia inside fossilized tree trunks in 1852.",
    "interestingFacts": ["The earliest known undisputed reptile in Earth's history.", "Laid amniotic eggs on dry land, breaking dependency on water."],
    "lengthM": 0.2,
    "heightM": 0.05,
    "weightKg": 0.1,
    "sizeNotes": "Total length including tail was about 20 centimeters.",
    "relatedSpeciesNames": []
  },
  {
    "name": "Diplocaulus magnicornis",
    "scientificName": "Diplocaulus magnicornis",
    "nameMeaning": "Double stalk with large horns",
    "timePeriod": "Early Permian",
    "myaStart": 299.0,
    "myaEnd": 275.0,
    "dietType": "Carnivore",
    "dietDetails": "Preyed on fish, insects, and smaller amphibians.",
    "locations": ["North America"],
    "taxonomicClassification": "Amphibia -> Lepospondyli -> Diplocaulidae -> Diplocaulus",
    "genus": "Diplocaulus",
    "family": "Diplocaulidae",
    "fossilFormation": "Arroyo Formation",
    "country": "United States",
    "reconstructionImageUrl": "https://upload.wikimedia.org/wikipedia/commons/3/36/Diplocaulus_magnicornis_reconstruction.jpg",
    "fossilImageUrl": "https://upload.wikimedia.org/wikipedia/commons/2/2b/Diplocaulus_magnicornis_skeleton.jpg",
    "discoveryHistory": "Described by Edward Drinker Cope in 1877 from Texas.",
    "interestingFacts": ["Had a distinctive boomerang-shaped head created by massive bony horns.", "Crescent shape of head may have generated lift when swimming."],
    "lengthM": 1.0,
    "heightM": 0.15,
    "weightKg": 15.0,
    "sizeNotes": "Reached up to 1 meter in length; flat-bodied.",
    "relatedSpeciesNames": []
  },
  {
    "name": "Estemmenosuchus uralensis",
    "scientificName": "Estemmenosuchus uralensis",
    "nameMeaning": "Crowned crocodile from the Urals",
    "timePeriod": "Middle Permian",
    "myaStart": 267.0,
    "myaEnd": 264.0,
    "dietType": "Omnivore",
    "dietDetails": "Likely herbivore-leaning omnivore eating tough leaves, tubers, and carrion.",
    "locations": ["Europe"],
    "taxonomicClassification": "Synapsida -> Dinocephalia -> Estemmenosuchidae -> Estemmenosuchus",
    "genus": "Estemmenosuchus",
    "family": "Estemmenosuchidae",
    "fossilFormation": "Ocher Assembly",
    "country": "Russia",
    "reconstructionImageUrl": "https://upload.wikimedia.org/wikipedia/commons/d/df/Estemmenosuchus_uralensis_reconstruction.jpg",
    "fossilImageUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e3/Estemmenosuchus_uralensis_skull.jpg",
    "discoveryHistory": "Discovered in Perm Krai, Russia, in 1960.",
    "interestingFacts": ["Featured complex bony horns and antlers on its head for display.", "Mummified skin impressions suggest glandular, hairless skin."],
    "lengthM": 4.0,
    "heightM": 1.8,
    "weightKg": 1000.0,
    "sizeNotes": "Massive bull-like build up to 4 meters long.",
    "relatedSpeciesNames": []
  },
  {
    "name": "Andrewsarchus mongoliensis",
    "scientificName": "Andrewsarchus mongoliensis",
    "nameMeaning": "Andrews' leader of beasts",
    "timePeriod": "Eocene",
    "myaStart": 45.0,
    "myaEnd": 36.0,
    "dietType": "Omnivore",
    "dietDetails": "Likely scavenger and predator, crushing bones and eating turtles.",
    "locations": ["Asia"],
    "taxonomicClassification": "Mammalia -> Artiodactyla -> Cetancodontamorpha -> Andrewsarchus",
    "genus": "Andrewsarchus",
    "family": "Andrewsarchidae",
    "fossilFormation": "Irdin Manha Formation",
    "country": "Mongolia",
    "reconstructionImageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Andrewsarchus_mongoliensis_reconstruction.jpg",
    "fossilImageUrl": "https://upload.wikimedia.org/wikipedia/commons/7/7b/Andrewsarchus_mongoliensis_skull.jpg",
    "discoveryHistory": "Discovered by Kan Chuen Pao during Roy Chapman Andrews' Central Asiatic Expedition in 1923.",
    "interestingFacts": ["Only known from a single giant skull measuring 83 cm in length.", "More closely related to hippos and whales than modern wolves."],
    "lengthM": 3.4,
    "heightM": 1.5,
    "weightKg": 1000.0,
    "sizeNotes": "Estimated length 3.4m; height at shoulder 1.5m.",
    "relatedSpeciesNames": []
  },
  {
    "name": "Uintatherium anceps",
    "scientificName": "Uintatherium anceps",
    "nameMeaning": "Beast of the Uinta Mountains",
    "timePeriod": "Eocene",
    "myaStart": 48.0,
    "myaEnd": 43.0,
    "dietType": "Herbivore",
    "dietDetails": "Browsed on soft forest foliage and leaves.",
    "locations": ["North America"],
    "taxonomicClassification": "Mammalia -> Dinocerata -> Uintatheriidae -> Uintatherium",
    "genus": "Uintatherium",
    "family": "Uintatheriidae",
    "fossilFormation": "Bridger Formation",
    "country": "United States",
    "reconstructionImageUrl": "https://upload.wikimedia.org/wikipedia/commons/e/ee/Uintatherium_anceps_reconstruction.jpg",
    "fossilImageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/48/Uintatherium_anceps_skeleton.jpg",
    "discoveryHistory": "Discovered during the bone wars and described by Leidy, Marsh, and Cope.",
    "interestingFacts": ["Had six distinctive bony knobs (horns) on its flat skull.", "Males possessed large, saber-like canine teeth for defense."],
    "lengthM": 4.0,
    "heightM": 1.7,
    "weightKg": 2000.0,
    "sizeNotes": "Comparable in size to a modern white rhinoceros.",
    "relatedSpeciesNames": []
  },
  {
    "name": "Paraceratherium transouralicum",
    "scientificName": "Paraceratherium transouralicum",
    "nameMeaning": "Near hornless beast",
    "timePeriod": "Oligocene",
    "myaStart": 34.0,
    "myaEnd": 23.0,
    "dietType": "Herbivore",
    "dietDetails": "Browsed leaves and twigs from tree canopies.",
    "locations": ["Asia"],
    "taxonomicClassification": "Mammalia -> Perissodactyla -> Paraceratheriidae -> Paraceratherium",
    "genus": "Paraceratherium",
    "family": "Paraceratheriidae",
    "fossilFormation": "Hsanda Gol Formation",
    "country": "Mongolia",
    "reconstructionImageUrl": "https://upload.wikimedia.org/wikipedia/commons/5/53/Paraceratherium_transouralicum_reconstruction.jpg",
    "fossilImageUrl": "https://upload.wikimedia.org/wikipedia/commons/2/2b/Paraceratherium_transouralicum_skeleton.jpg",
    "discoveryHistory": "Discovered in Pakistan and described by Forster-Cooper in 1911.",
    "interestingFacts": ["The largest land mammal known to have ever lived on Earth.", "Had a long neck allowing it to browse canopies up to 8m high."],
    "lengthM": 7.4,
    "heightM": 4.8,
    "weightKg": 15000.0,
    "sizeNotes": "Shoulder height 4.8 meters; length 7.4 meters.",
    "relatedSpeciesNames": []
  },
  {
    "name": "Elasmotherium sibiricum",
    "scientificName": "Elasmotherium sibiricum",
    "nameMeaning": "Plated beast from Siberia",
    "timePeriod": "Pleistocene",
    "myaStart": 2.6,
    "myaEnd": 0.039,
    "dietType": "Herbivore",
    "dietDetails": "Grazer feeding on grasses, roots, and tough steppe vegetation.",
    "locations": ["Europe", "Asia"],
    "taxonomicClassification": "Mammalia -> Perissodactyla -> Rhinocerotidae -> Elasmotherium",
    "genus": "Elasmotherium",
    "family": "Rhinocerotidae",
    "fossilFormation": "Siberian Steppe deposits",
    "country": "Russia",
    "reconstructionImageUrl": "https://upload.wikimedia.org/wikipedia/commons/e/ec/Elasmotherium_sibiricum_reconstruction.jpg",
    "fossilImageUrl": "https://upload.wikimedia.org/wikipedia/commons/8/87/Elasmotherium_sibiricum_skull.jpg",
    "discoveryHistory": "First described by Gotthelf Fischer von Waldheim in 1808.",
    "interestingFacts": ["Popularly known as the Siberian Unicorn due to a massive horn dome on its forehead.", "Survived long enough to coexist with early human species."],
    "lengthM": 4.5,
    "heightM": 2.2,
    "weightKg": 4000.0,
    "sizeNotes": "Grew up to 4.5 meters in length and over 2 meters tall.",
    "relatedSpeciesNames": []
  },
  {
    "name": "Titanoboa cerrejonensis",
    "scientificName": "Titanoboa cerrejonensis",
    "nameMeaning": "Titanic boa from Cerrejon",
    "timePeriod": "Paleocene",
    "myaStart": 60.0,
    "myaEnd": 58.0,
    "dietType": "Carnivore",
    "dietDetails": "Preyed on giant crocodiles, turtles, and large fish.",
    "locations": ["South America"],
    "taxonomicClassification": "Reptilia -> Squamata -> Boidae -> Titanoboa",
    "genus": "Titanoboa",
    "family": "Boidae",
    "fossilFormation": "Cerrejon Formation",
    "country": "Colombia",
    "reconstructionImageUrl": "https://upload.wikimedia.org/wikipedia/commons/b/b5/Titanoboa_cerrejonensis_reconstruction.jpg",
    "fossilImageUrl": "https://upload.wikimedia.org/wikipedia/commons/2/23/Titanoboa_cerrejonensis_vertebra.jpg",
    "interestingFacts": ["The largest, longest, and heaviest snake ever discovered.", "Fossils show it lived in a tropical rainforest hotter than today's tropics."],
    "lengthM": 12.8,
    "heightM": 0.9,
    "weightKg": 1135.0,
    "sizeNotes": "Reached up to 12.8 meters (42 ft) in length and weighed 1.1 metric tons.",
    "relatedSpeciesNames": []
  },
  {
    "name": "Moeritherium lyonsi",
    "scientificName": "Moeritherium lyonsi",
    "nameMeaning": "Beast of Lake Moeris",
    "timePeriod": "Late Eocene",
    "myaStart": 37.0,
    "myaEnd": 35.0,
    "dietType": "Herbivore",
    "dietDetails": "Browsed aquatic plants and soft vegetation along lake margins.",
    "locations": ["Africa"],
    "taxonomicClassification": "Mammalia -> Proboscidea -> Moeritheriidae -> Moeritherium",
    "genus": "Moeritherium",
    "family": "Moeritheriidae",
    "fossilFormation": "Qasr el-Sagha Formation",
    "country": "Egypt",
    "reconstructionImageUrl": "https://upload.wikimedia.org/wikipedia/commons/e/ee/Moeritherium_lyonsi_reconstruction.jpg",
    "fossilImageUrl": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Moeritherium_lyonsi_skull.jpg",
    "discoveryHistory": "Discovered by Charles William Andrews in Egypt in 1901.",
    "interestingFacts": ["An early primitive relative of modern elephants, resembling a small tapir.", "Fossil evidence suggests semi-aquatic habits similar to a pygmy hippo."],
    "lengthM": 2.0,
    "heightM": 0.7,
    "weightKg": 235.0,
    "sizeNotes": "Stood about 70 cm tall at the shoulder.",
    "relatedSpeciesNames": []
  }
];

const allOthers = [...updatedNonMesozoic, ...newSpecies];

fs.writeFileSync(othersJsonPath, JSON.stringify(allOthers, null, 2), 'utf8');
console.log(`Successfully generated species_others.json with ${allOthers.length} species.`);
