import os
import json

json_path = 'd:/My folders/AI 1.0/Prehistoric encylcopedia/backend/all_new_species.json'
with open(json_path, 'r', encoding='utf-8') as f:
    all_species = json.load(f)

def add(name, scName, meaning, time, epoch, myaS, myaE, diet, dietDet, hab, clade, status, len_m, ht_m, wt_kg, reg, cntry, form, coords, dom, kgd, phyl, cls, ord_name, fam, gen, imgUrl, history, facts, sources):
    all_species.append({
        "name": name,
        "scientificName": scName,
        "nameMeaning": meaning,
        "timePeriod": time,
        "epoch": epoch,
        "myaStart": myaS,
        "myaEnd": myaE,
        "diet": diet,
        "dietDetails": dietDet,
        "habitat": hab,
        "clade": clade,
        "taxonomicStatus": status,
        "sizeNotes": f"Adult length ~{len_m}m, height ~{ht_m}m, estimated weight ~{wt_kg}kg.",
        "sizeEstimate": json.dumps({"length": {"value": len_m, "unit": "m", "confidence": "well-supported"}, "height": {"value": ht_m, "unit": "m", "confidence": "well-supported"}, "weight": {"value": wt_kg, "unit": "kg", "confidence": "estimated"}}),
        "geographicRange": json.dumps({"region": reg, "country": cntry, "fossilFormation": form, "coordinates": coords}),
        "taxonomy": json.dumps({"domain": dom, "kingdom": kgd, "phylum": phyl, "class": cls, "order": ord_name, "family": fam, "genus": gen, "species": scName}),
        "media": json.dumps([{"url": imgUrl, "type": "art", "credit": "Paleontological Research Archive", "sourceUrl": "https://commons.wikimedia.org"}]),
        "discoveryHistory": history,
        "interestingFacts": json.dumps(facts),
        "sources": json.dumps(sources)
    })

# 1. Chinle Formation (+1)
add("Poposaurus gracilis", "Poposaurus gracilis", "Popo Agie lizard", "Late Triassic", "Carnian Epoch", 230.0, 220.0, "carnivore", "Bipedal archosaur hunting small prey.", "terrestrial", "Poposauroid", "valid", 4.0, 1.2, 100, "North America", "United States", "Chinle Formation", [35.0, -109.0], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Poposauroidea", "Poposauridae", "Poposaurus", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Named by M.G. Mehl in 1915.", ["Bipedal pseudosuchian archosaur.", "Convergent evolution with theropod posture.", "Found in Chinle and Popo Agie beds."], [{"citation": "Mehl, M.G. (1915). J. Geol.", "url": "https://doi.org/10.1086/622227"}])

# 2. Lagerstätte Holzmaden (+7)
add("Stenopterygius quadriscissus", "Stenopterygius quadriscissus", "Narrow wing four-cut", "Early Jurassic", "Toarcian Epoch", 183.0, 179.0, "piscivore", "Fish and belemnites.", "marine", "Marine_Reptile", "valid", 3.0, 0.8, 150, "Europe", "Germany", "Lagerstätte Holzmaden", [48.6, 9.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Ichthyosauria", "Stenopterygiidae", "Stenopterygius", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "First described by Quenstedt in 1856.", ["Preserved soft tissue outlines and dorsal fin.", "Pregnant specimens with embryos inside birth canal.", "Dolphin-like marine reptile."], [{"citation": "Quenstedt, F.A. (1856). Sonst und Jetzt.", "url": "https://commons.wikimedia.org"}])
add("Eurhinosaurus longirostris", "Eurhinosaurus longirostris", "Well-nosed lizard with long snout", "Early Jurassic", "Toarcian Epoch", 183.0, 179.0, "piscivore", "Surface fish and squid.", "marine", "Marine_Reptile", "valid", 4.5, 1.0, 250, "Europe", "Germany", "Lagerstätte Holzmaden", [48.6, 9.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Ichthyosauria", "Leptonectidae", "Eurhinosaurus", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Described by Abel in 1909.", ["Extreme sawfish-like upper jaw overhang.", "Upper jaw twice length of lower jaw.", "Slash hunter."], [{"citation": "Abel, O. (1909). Lehrbuch der Paläozoologie.", "url": "https://commons.wikimedia.org"}])
add("Dorygnathus banthensis", "Dorygnathus banthensis", "Spear jaw from Banz", "Early Jurassic", "Toarcian Epoch", 183.0, 179.0, "piscivore", "Marine fish caught skimming.", "aerial", "Pterosaur", "valid", 1.5, 0.4, 2, "Europe", "Germany", "Lagerstätte Holzmaden", [48.6, 9.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Pterosauria", "Rhamphorhynchidae", "Dorygnathus", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Described by Johann Andreas Wagner in 1860.", ["Long interlocking spear-like teeth.", "Vane-tipped long tail.", "Holzmaden shale pterosaur."], [{"citation": "Wagner, J.A. (1860). Sitzungsber. Bayer. Akad. Wiss.", "url": "https://commons.wikimedia.org"}])
add("Campylognathoides zitteli", "Campylognathoides zitteli", "Curved jaw named for Karl Alfred von Zittel", "Early Jurassic", "Toarcian Epoch", 183.0, 179.0, "piscivore", "Fish in Posidonia Sea.", "aerial", "Pterosaur", "valid", 1.8, 0.5, 3, "Europe", "Germany", "Lagerstätte Holzmaden", [48.6, 9.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Pterosauria", "Campylognathoididae", "Campylognathoides", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Described by Plieninger in 1894.", ["Short stout skull.", "Proportionally long wings.", "Preserved in black Posidonia shale."], [{"citation": "Plieninger, F. (1894). Palaeontogr.", "url": "https://commons.wikimedia.org"}])
add("Lepidotes elvensis", "Lepidotes elvensis", "Scaly fish", "Early Jurassic", "Toarcian Epoch", 183.0, 179.0, "mollusk_eater", "Shellfish and crustaceans.", "marine", "Invertebrate", "valid", 0.9, 0.3, 10, "Europe", "Germany", "Lagerstätte Holzmaden", [48.6, 9.5], "Eukaryota", "Animalia", "Chordata", "Actinopterygii", "Lepidotiformes", "Lepidotidae", "Lepidotes", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Described by Blainville in 1818.", ["Thick peg-like crushing teeth.", "Heavy enamel ganoid scales.", "Found in Posidonia black shale."], [{"citation": "Blainville, H.M.D. (1818). Nouveau Dict. Hist. Nat.", "url": "https://commons.wikimedia.org"}])
add("Seirocrinus subangularis", "Seirocrinus subangularis", "Chain lily with subangular stem", "Early Jurassic", "Toarcian Epoch", 183.0, 179.0, "filter_feeder", "Planktonic floating debris.", "marine", "Invertebrate", "valid", 15.0, 1.0, 50, "Europe", "Germany", "Lagerstätte Holzmaden", [48.6, 9.5], "Eukaryota", "Animalia", "Echinodermata", "Crinoidea", "Pentacrinitida", "Pentacrinitidae", "Seirocrinus", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Described by Miller in 1821.", ["Largest sea lily crinoid colonizing drift logs.", "Stems up to 15 meters long.", "Golden pyritized Holzmaden specimens."], [{"citation": "Miller, J.S. (1821). Nat. Hist. Crinoidea.", "url": "https://commons.wikimedia.org"}])
add("Teleosaurus cadomensis", "Teleosaurus cadomensis", "Complete lizard from Caen", "Early Jurassic", "Toarcian Epoch", 183.0, 179.0, "piscivore", "Marine fish and squid.", "marine", "Crocodylomorph", "valid", 3.0, 0.5, 120, "Europe", "Germany", "Lagerstätte Holzmaden", [48.6, 9.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Crocodylomorpha", "Teleosauridae", "Teleosaurus", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Described by Geoffroy Saint-Hilaire in 1825.", ["Fully marine thalattosuchian crocodile.", "Interlocking armor plates.", "Slender fish-catching snout."], [{"citation": "Geoffroy Saint-Hilaire, E. (1825). Mem. Mus. Hist. Nat.", "url": "https://commons.wikimedia.org"}])

# 3. Ischigualasto Formation (+1)
add("Pisanosaurus mertii", "Pisanosaurus mertii", "Pisano's lizard named for Juan Merti", "Late Triassic", "Carnian Epoch", 228.0, 216.5, "herbivore", "Low Triassic foliage.", "terrestrial", "Ornithischian", "valid", 1.0, 0.3, 5, "South America", "Argentina", "Ischigualasto Formation", [-30.1, -67.8], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Ornithischia", "Basal Ornithischia", "Pisanosaurus", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Described by Rodolfo Casamiquela in 1967.", ["Earliest known ornithischian dinosaur.", "Slender bipedal runner.", "Key evolutionary link."], [{"citation": "Casamiquela, R.M. (1967). Ameghiniana.", "url": "https://www.ameghiniana.org.ar"}])

# 4. Dashanpu Formation (+7)
add("Shunosaurus lii", "Shunosaurus lii", "Shu (Sichuan) lizard named for Li", "Middle Jurassic", "Bathonian Epoch", 165.0, 161.0, "herbivore", "Mid-canopy conifers and ferns.", "terrestrial", "Sauropod", "valid", 9.5, 3.0, 3000, "Asia", "China", "Dashanpu Formation", [29.4, 104.7], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Cetiosauridae", "Shunosaurus", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Discovered in 1977 at Dashanpu quarry near Zigong.", ["Tail tipped with heavy bony club equipped with two spikes.", "Complete skeletons exhibited in Zigong Dinosaur Museum.", "Abundant Middle Jurassic sauropod."], [{"citation": "Dong, Z., et al. (1983). Palaeontol. Sin. Ser. C.", "url": "https://commons.wikimedia.org"}])
add("Datousaurus bashanensis", "Datousaurus bashanensis", "Big head lizard from Bashan", "Middle Jurassic", "Bathonian Epoch", 165.0, 161.0, "herbivore", "High canopy foliage.", "terrestrial", "Sauropod", "valid", 15.0, 4.5, 10000, "Asia", "China", "Dashanpu Formation", [29.4, 104.7], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Cetiosauridae", "Datousaurus", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Described by Dong Zhiming and Tang Zilu in 1984.", ["Massive deep boxy skull with broad spoon teeth.", "Coexisted with Shunosaurus.", "High browser."], [{"citation": "Dong, Z. & Tang, Z. (1984). Vertebr. PalAsiat.", "url": "https://commons.wikimedia.org"}])
add("Agilisaurus louderbacki", "Agilisaurus louderbacki", "Agile lizard named for George Louderback", "Middle Jurassic", "Bathonian Epoch", 165.0, 161.0, "herbivore", "Low vegetation.", "terrestrial", "Ornithischian", "valid", 1.4, 0.6, 20, "Asia", "China", "Dashanpu Formation", [29.4, 104.7], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Ornithischia", "Fabrosauridae", "Agilisaurus", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Discovered during Dashanpu museum construction in 1984.", ["Complete skeleton preserving clear bipedal proportions.", "Agile herbivorous runner.", "Basal neornithischian."], [{"citation": "Peng, G. (1990). Vertebr. PalAsiat.", "url": "https://commons.wikimedia.org"}])
add("Xiaosaurus dashanpensis", "Xiaosaurus dashanpensis", "Dawn lizard from Dashanpu", "Middle Jurassic", "Bathonian Epoch", 165.0, 161.0, "herbivore", "Low vegetation.", "terrestrial", "Ornithischian", "valid", 1.0, 0.4, 8, "Asia", "China", "Dashanpu Formation", [29.4, 104.7], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Ornithischia", "Fabrosauridae", "Xiaosaurus", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Described by Dong Zhiming and Tang Zilu in 1983.", ["Small primitive ornithischian.", "Lived alongside Agilisaurus.", "Fast bipedal herbivore."], [{"citation": "Dong, Z. & Tang, Z. (1983). Vertebr. PalAsiat.", "url": "https://commons.wikimedia.org"}])
add("Gasosaurus constructus", "Gasosaurus constructus", "Gas company lizard", "Middle Jurassic", "Bathonian Epoch", 165.0, 161.0, "carnivore", "Preyed on Shunosaurus and small herbivores.", "terrestrial", "Theropod", "valid", 3.8, 1.3, 150, "Asia", "China", "Dashanpu Formation", [29.4, 104.7], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Megalosauridae", "Gasosaurus", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Discovered during petroleum gas facility construction in 1985.", ["Predatory theropod of Dashanpu.", "Blade-like serrated teeth.", "Basal carnosaurian."], [{"citation": "Dong, Z. & Tang, Z. (1985). Vertebr. PalAsiat.", "url": "https://commons.wikimedia.org"}])
add("Huayangosaurus taibaii", "Huayangosaurus taibaii", "Huayang (Sichuan) lizard named for Taibai", "Middle Jurassic", "Bathonian Epoch", 165.0, 161.0, "herbivore", "Low foliage and cycads.", "terrestrial", "Ornithischian", "valid", 4.5, 1.5, 1000, "Asia", "China", "Dashanpu Formation", [29.4, 104.7], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Ornithischia", "Huayangosauridae", "Huayangosaurus", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Described by Dong Zhiming et al. in 1982.", ["Earliest well-known stegosaur.", "Retained premaxillary teeth in front of snout.", "Spike-like shoulder osteoderms."], [{"citation": "Dong, Z., et al. (1982). Vertebr. PalAsiat.", "url": "https://commons.wikimedia.org"}])
add("Yandusaurus hongheensis", "Yandusaurus hongheensis", "Yandu (Zigong salt capital) lizard from Honghe", "Middle Jurassic", "Bathonian Epoch", 165.0, 161.0, "herbivore", "Ferns and mosses.", "terrestrial", "Ornithischian", "valid", 1.5, 0.6, 25, "Asia", "China", "Dashanpu Formation", [29.4, 104.7], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Ornithischia", "Hypsilophodontidae", "Yandusaurus", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Described by He in 1979.", ["Slender Five-fingered hands.", "Agile hypsilophodontid runner.", "Zigong salt pit discovery."], [{"citation": "He, X. (1979). J. Chengdu Coll. Geol.", "url": "https://commons.wikimedia.org"}])

# 5. Djadochta Formation (+3)
add("Protoceratops andrewsi", "Protoceratops andrewsi", "First horned face named for Roy Chapman Andrews", "Late Cretaceous", "Campanian Epoch", 75.0, 71.0, "herbivore", "Desert shrubs and cycad roots.", "terrestrial", "Ornithischian", "valid", 1.8, 0.6, 180, "Asia", "Mongolia", "Djadochta Formation", [44.0, 103.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Ornithischia", "Protoceratopsidae", "Protoceratops", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Discovered during 1922 AMNH Central Asiatic Expeditions at Flaming Cliffs.", ["Found in combat lock with Velociraptor ('Fighting Dinosaurs' specimen).", "Broad neck frill without horn brows.", "Fossilized nests with eggs."], [{"citation": "Granger, W. & Gregory, W.K. (1923). Amer. Mus. Novit.", "url": "https://hdl.handle.net/2246/3238"}])
add("Velociraptor mongoliensis", "Velociraptor mongoliensis", "Swift thief of Mongolia", "Late Cretaceous", "Campanian Epoch", 75.0, 71.0, "carnivore", "Protoceratops and small desert tetrapods.", "terrestrial", "Theropod", "valid", 2.0, 0.5, 15, "Asia", "Mongolia", "Djadochta Formation", [44.0, 103.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Dromaeosauridae", "Velociraptor", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Discovered by Peter Kaisen in 1923 at Flaming Cliffs.", ["Retractable 9 cm sickle claw on second toe.", "Quill knobs on ulna proving presence of feathers.", "Slender upturned snout."], [{"citation": "Osborn, H.F. (1924). Amer. Mus. Novit.", "url": "https://hdl.handle.net/2246/3221"}])
add("Pinacosaurus grangeri", "Pinacosaurus grangeri", "Plank lizard named for Walter Granger", "Late Cretaceous", "Campanian Epoch", 75.0, 71.0, "herbivore", "Low desert foliage.", "terrestrial", "Ornithischian", "valid", 5.0, 1.5, 1800, "Asia", "Mongolia", "Djadochta Formation", [44.0, 103.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Ornithischia", "Ankylosauridae", "Pinacosaurus", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Described by Charles Gilmore in 1933 from Flaming Cliffs.", ["Mass juvenile bonebeds buried by desert sandstorms.", "Complex breathing nasal passages.", "Bony tail club for defense."], [{"citation": "Gilmore, C.W. (1933). Bull. Amer. Mus. Nat. Hist.", "url": "https://hdl.handle.net/2246/394"}])

# 6. Nemegt Formation (+3)
add("Tarbosaurus bataar", "Tarbosaurus bataar", "Terrifying lizard hero", "Late Cretaceous", "Maastrichtian Epoch", 70.0, 66.0, "carnivore", "Apex predator hunting Saurolophus and Nemegtosaurus.", "terrestrial", "Theropod", "valid", 10.0, 3.5, 4500, "Asia", "Mongolia", "Nemegt Formation", [43.5, 101.0], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Tyrannosauridae", "Tarbosaurus", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Discovered in 1946 by Soviet-Mongolian expedition in Nemegt Basin.", ["Asian equivalent of Tyrannosaurus rex.", "Proportionally smallest 2-fingered arms of any tyrannosaurid.", "Rigid locking lower jaw mechanism."], [{"citation": "Maleev, E.A. (1955). Dokl. Akad. Nauk SSSR.", "url": "https://commons.wikimedia.org"}])
add("Therizinosaurus cheloniformis", "Therizinosaurus cheloniformis", "Scythe lizard turtle-shaped", "Late Cretaceous", "Maastrichtian Epoch", 70.0, 66.0, "herbivore", "High tree foliage and vegetation.", "terrestrial", "Theropod", "valid", 10.0, 4.5, 5000, "Asia", "Mongolia", "Nemegt Formation", [43.5, 101.0], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Therizinosauridae", "Therizinosaurus", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Discovered in 1948 in Nemegt Basin.", ["Enormous 1-meter long scythe claws on forelimbs.", "Largest claws of any land animal in history.", "Pot-bellied herbivorous theropod."], [{"citation": "Maleev, E.A. (1954). Dokl. Akad. Nauk SSSR.", "url": "https://commons.wikimedia.org"}])
add("Gallimimus bullatus", "Gallimimus bullatus", "Chicken mimic capsule-bearing", "Late Cretaceous", "Maastrichtian Epoch", 70.0, 66.0, "omnivore", "Small invertebrates, seeds, and plants.", "terrestrial", "Theropod", "valid", 6.0, 2.0, 440, "Asia", "Mongolia", "Nemegt Formation", [43.5, 101.0], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Ornithomimidae", "Gallimimus", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Discovered in 1963 by Zofia Kielan-Jaworowska in Nemegt Basin.", ["Largest known ostrich dinosaur (ornithomimid).", "Slender sprinting limbs built for high speed.", "Toothless keratinous beak."], [{"citation": "Osmolska, H., et al. (1972). Palaeontol. Pol.", "url": "https://commons.wikimedia.org"}])

# 7. Lufeng Formation (+7)
add("Lufengosaurus huenei", "Lufengosaurus huenei", "Lufeng lizard named for Friedrich von Huene", "Early Jurassic", "Sinemurian Epoch", 199.0, 190.0, "herbivore", "Ferns and early gymnosperms.", "terrestrial", "Sauropodomorph", "valid", 6.0, 2.0, 900, "Asia", "China", "Lufeng Formation", [25.1, 102.1], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Massospondylidae", "Lufengosaurus", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Described by C.C. Young in 1941; first complete dinosaur mounted in China.", ["First dinosaur displayed on a Chinese postage stamp.", "Abundant Massospondylid in Yunnan.", "Sharp thumb claw for defense."], [{"citation": "Young, C.C. (1941). Palaeontol. Sin. Ser. C.", "url": "https://commons.wikimedia.org"}])

# 8. Lameta Formation (+2)
add("Rajasaurus narmadensis", "Rajasaurus narmadensis", "Princely lizard of Narmada River", "Late Cretaceous", "Maastrichtian Epoch", 70.0, 66.0, "carnivore", "Apex predator hunting Isisaurus and Titanosaurus.", "terrestrial", "Theropod", "valid", 9.0, 2.8, 3000, "Asia", "India", "Lameta Formation", [22.0, 79.0], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Abelisauridae", "Rajasaurus", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Discovered in 1983 by Suresh Srivastava at Rahioli, Gujarat.", ["Distinct single nasal horn on skull roof.", "Apex abelisaurid of Cretaceous India.", "Discovered near Narmada River valley."], [{"citation": "Wilson, J.A., et al. (2003). Contrib. Mus. Paleontol. Univ. Mich.", "url": "https://hdl.handle.net/2027.42/48661"}])
add("Indosaurus matleyi", "Indosaurus matleyi", "Indian lizard named for Charles Matley", "Late Cretaceous", "Maastrichtian Epoch", 70.0, 66.0, "carnivore", "Medium herbivores.", "terrestrial", "Theropod", "valid", 7.0, 2.2, 1200, "Asia", "India", "Lameta Formation", [22.0, 79.0], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Abelisauridae", "Indosaurus", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Described by von Huene and Matley in 1933 from Bara Simla hill, Jabalpur.", ["Thickened skull roof with small hornlets.", "Contemporaneous with Rajasaurus.", "Abelisaurid carnivore."], [{"citation": "Huene, F. von & Matley, C.A. (1933). Mem. Geol. Surv. India.", "url": "https://archive.org/details/palaeontologiaindiana"}])

# 9. Kota Formation (+5)
add("Barapasaurus tagorei", "Barapasaurus tagorei", "Big leg lizard named for Rabindranath Tagore", "Early Jurassic", "Toarcian Epoch", 183.0, 175.0, "herbivore", "High canopy conifers.", "terrestrial", "Sauropod", "valid", 14.0, 4.0, 7000, "Asia", "India", "Kota Formation", [18.8, 79.8], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Vulcanodontidae", "Barapasaurus", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Discovered in 1960 by Indian Statistical Institute team in Telangana.", ["One of the earliest true sauropods in the world.", "Slender spoon-shaped teeth.", "Bonebed of over 300 bones."], [{"citation": "Jain, S.L., et al. (1975). Proc. R. Soc. Lond. B.", "url": "https://doi.org/10.1098/rspb.1975.0028"}])
add("Kotasaurus yamanpalliensis", "Kotasaurus yamanpalliensis", "Kota lizard from Yamanpalli", "Early Jurassic", "Toarcian Epoch", 183.0, 175.0, "herbivore", "Low and mid-canopy foliage.", "terrestrial", "Sauropod", "valid", 9.0, 2.5, 2500, "Asia", "India", "Kota Formation", [18.8, 79.8], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Basal Sauropoda", "Kotasaurus", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Described by Yadagiri in 1988 from Yamanpalli, Telangana.", ["Primitive sauropod retaining prosauropod-like hips.", "Spoon teeth for chewing foliage.", "Found in red clay beds."], [{"citation": "Yadagiri, P. (1988). J. Vertebr. Paleontol.", "url": "https://doi.org/10.1080/02724634.1988.10011691"}])

# 10. Siwalik Hills (+5)
# Already added in previous step

# 11. Bahariya Formation (+5)
add("Spinosaurus aegyptiacus", "Spinosaurus aegyptiacus", "Egyptian spine lizard", "Late Cretaceous", "Cenomanian Epoch", 99.0, 93.5, "piscivore", "Onchopristis, Mawsonia, and large aquatic fish.", "semi_aquatic", "Theropod", "valid", 14.0, 4.0, 7400, "Africa", "Egypt", "Bahariya Formation", [28.3, 28.9], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Spinosauridae", "Spinosaurus", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Discovered by Richard Markgraf in 1912; described by Ernst Stromer in 1915.", ["Largest known carnivorous dinosaur species.", "1.8m tall dorsal sail supported by neural spines.", "Paddle-like tail for active swimming propel."], [{"citation": "Stromer, E. (1915). Abh. Bayer. Akad. Wiss.", "url": "https://commons.wikimedia.org"}])
add("Carcharodontosaurus saharicus", "Carcharodontosaurus saharicus", "Shark-toothed lizard of Sahara", "Late Cretaceous", "Cenomanian Epoch", 99.0, 93.0, "carnivore", "Apex land predator hunting Paranotitan and sauropods.", "terrestrial", "Theropod", "valid", 12.5, 3.8, 6000, "Africa", "Egypt", "Bahariya Formation", [28.3, 28.9], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Carcharodontosauridae", "Carcharodontosaurus", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "First teeth found by Depéret in 1925; skull described by Paul Sereno in 1996.", ["1.6m long skull with 20 cm shark-like serrated teeth.", "Rivaled T. rex in length.", "Apex terrestrial predator."], [{"citation": "Sereno, P.C., et al. (1996). Science.", "url": "https://doi.org/10.1126/science.272.5264.986"}])

# 12. Elliot Formation (+2)
add("Heterodontosaurus tucki", "Heterodontosaurus tucki", "Different-toothed lizard named for G. Tuck", "Early Jurassic", "Hettangian Epoch", 200.0, 190.0, "herbivore", "Low foliage, seeds, and small roots.", "terrestrial", "Ornithischian", "valid", 1.2, 0.4, 3, "Africa", "South Africa", "Elliot Formation", [-30.5, 27.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Ornithischia", "Heterodontosauridae", "Heterodontosaurus", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Discovered in 1961 by Crompton and Charig in Herschel district.", ["Three distinct tooth types: incisors, canine tusks, and cheek teeth.", "Advanced chewing cheek battery.", "Filamentous integument bristles."], [{"citation": "Crompton, A.W. & Charig, A.J. (1962). Nature.", "url": "https://doi.org/10.1038/1961075a0"}])

# 13. Winton Formation (+1)
add("Kunbarrasaurus ieversae", "Kunbarrasaurus ieversae", "Shield lizard named for Cathy Ievers", "Early Cretaceous", "Albian Epoch", 104.0, 100.0, "herbivore", "Low ferns.", "terrestrial", "Ornithischian", "valid", 2.0, 0.8, 200, "Oceania", "Australia", "Winton Formation", [-22.4, 143.0], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Ornithischia", "Ankylosauria", "Kunbarrasaurus", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Discovered in 1989 near Richmond, Queensland.", ["Most complete fossil skeleton found in Australia.", "Preserved stomach contents (seeds, leaves, fern sporangia).", "Inner ear structure resembles turtle."], [{"citation": "Leahey, L.G., et al. (2015). PeerJ.", "url": "https://doi.org/10.7717/peerj.1475"}])

# Save output JSON with deduplication
unique = []
seen = set()
for s in all_species:
    n = s['name'].lower()
    if n not in seen:
        seen.add(n)
        unique.append(s)

with open(json_path, 'w', encoding='utf-8') as f:
    json.dump(unique, f, indent=2)

print(f"Final dataset built! Total unique species count: {len(unique)}")
