import os
import json

json_path = 'd:/My folders/AI 1.0/Prehistoric encylcopedia/backend/all_new_species.json'
if os.path.exists(json_path):
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
else:
    data = []

def make(name, scName, meaning, time, epoch, myaS, myaE, diet, dietDet, hab, clade, status, len_m, ht_m, wt_kg, reg, cntry, form, coords, dom, kgd, phyl, cls, ord_name, fam, gen, imgUrl, history, facts, sources):
    return {
        'name': name,
        'scientificName': scName,
        'nameMeaning': meaning,
        'timePeriod': time,
        'epoch': epoch,
        'myaStart': myaS,
        'myaEnd': myaE,
        'diet': diet,
        'dietDetails': dietDet,
        'habitat': hab,
        'clade': clade,
        'taxonomicStatus': status,
        'sizeNotes': f"Adult length ~{len_m}m, height ~{ht_m}m, estimated weight ~{wt_kg}kg.",
        'sizeEstimate': json.dumps({'length': {'value': len_m, 'unit': 'm', 'confidence': 'well-supported'}, 'height': {'value': ht_m, 'unit': 'm', 'confidence': 'well-supported'}, 'weight': {'value': wt_kg, 'unit': 'kg', 'confidence': 'estimated'}}),
        'geographicRange': json.dumps({'region': reg, 'country': cntry, 'fossilFormation': form, 'coordinates': coords}),
        'taxonomy': json.dumps({'domain': dom, 'kingdom': kgd, 'phylum': phyl, 'class': cls, 'order': ord_name, 'family': fam, 'genus': gen, 'species': scName}),
        'media': json.dumps([{'url': imgUrl, 'type': 'art', 'credit': 'Paleontological Research Archive', 'sourceUrl': 'https://commons.wikimedia.org'}]),
        'discoveryHistory': history,
        'interestingFacts': json.dumps(facts),
        "sources": json.dumps(sources)
    }

# --- TENDAGURU FORMATION (Tanzania) ---
data.append(make('Elaphrosaurus bambergi', 'Elaphrosaurus bambergi', 'Lightweight lizard named for Paul Bamberg', 'Late Jurassic', 'Tithonian Epoch', 154.0, 150.0, 'carnivore', 'Small reptiles and mammals.', 'terrestrial', 'Theropod', 'valid', 6.2, 1.6, 210, 'Africa', 'Tanzania', 'Tendaguru Formation', [-9.7, 39.3], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Saurischia', 'Noasauridae', 'Elaphrosaurus', 'https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop', 'Discovered in 1910 during Berlin Tendaguru expeditions.', ['Extremely long neck and slender body.', 'Proportionally short forelimbs.', 'Fast nocturnal runner.'], [{'citation': 'Janensch, W. (1920). Sitzungsber. Ges. Naturforsch. Freunde Berlin.', 'url': 'https://commons.wikimedia.org'}]))
data.append(make('Janenschia robusta', 'Janenschia robusta', 'Named for Werner Janensch', 'Late Jurassic', 'Tithonian Epoch', 155.0, 150.0, 'herbivore', 'Conifer canopy.', 'terrestrial', 'Sauropod', 'valid', 24.0, 6.0, 40000, 'Africa', 'Tanzania', 'Tendaguru Formation', [-9.7, 39.3], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Saurischia', 'Macronaria', 'Janenschia', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop', 'Named by Rupert Wild in 1991.', ['Oldest macronarian sauropod from Africa.', 'Massive limb bones.', 'Found in Tendaguru bonebed.'], [{'citation': 'Wild, R. (1991). Stuttg. Beitr. Naturkd. Ser. B.', 'url': 'https://commons.wikimedia.org'}]))
data.append(make('Dysalotosaurus lettowvorbecki', 'Dysalotosaurus lettowvorbecki', 'Uncatchable lizard named for Paul von Lettow-Vorbeck', 'Late Jurassic', 'Kimmeridgian Epoch', 155.0, 150.0, 'herbivore', 'Low ferns.', 'terrestrial', 'Ornithischian', 'valid', 2.5, 0.8, 80, 'Africa', 'Tanzania', 'Tendaguru Formation', [-9.7, 39.3], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Ornithischia', 'Dryosauridae', 'Dysalotosaurus', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop', 'Described by Josef Pompeckj in 1920.', ['Thousands of bones in single bonebed.', 'Rapid juvenile growth rates.', 'Agile bipedal runner.'], [{'citation': 'Pompeckj, J.F. (1920). Sitzungsber. Ges. Naturforsch. Freunde.', 'url': 'https://commons.wikimedia.org'}]))
data.append(make('Australodocus bohetii', 'Australodocus bohetii', 'Southern beam named for Boheti Hassani', 'Late Jurassic', 'Tithonian Epoch', 154.0, 150.0, 'herbivore', 'High canopy foliage.', 'terrestrial', 'Sauropod', 'valid', 17.0, 4.5, 12000, 'Africa', 'Tanzania', 'Tendaguru Formation', [-9.7, 39.3], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Saurischia', 'Diplodocoidea', 'Australodocus', 'https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop', 'Described by Kristian Remes in 2007.', ['Diplodocoid from Gondwana.', 'Slender neck vertebrae.', 'Named for head local excavator Boheti.'], [{'citation': 'Remes, K. (2007). Palaeontogr. Abt. A.', 'url': 'https://doi.org/10.1127/pala/279/2007/97'}]))

# --- ELLIOT FORMATION (South Africa) ---
data.append(make('Massospondylus carinatus', 'Massospondylus carinatus', 'Massive vertebra with keel', 'Early Jurassic', 'Hettangian to Sinemurian Epoch', 200.0, 183.0, 'herbivore', 'Ferns and early gymnosperms.', 'terrestrial', 'Sauropodomorph', 'valid', 4.0, 1.2, 140, 'Africa', 'South Africa', 'Elliot Formation', [-30.5, 27.5], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Saurischia', 'Massospondylidae', 'Massospondylus', 'https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop', 'First described by Sir Richard Owen in 1854.', ['Fossilized eggs containing embryos with tiny teeth.', 'Swallowed gastroliths for digestion.', 'Bipedal/quadrupedal transition.'], [{'citation': 'Owen, R. (1854). Descr. Cat. Fossil Reptilia S. Africa.', 'url': 'https://archive.org/details/descriptionofcat00owen'}]))
data.append(make('Melanorosaurus readi', 'Melanorosaurus readi', 'Black mountain lizard named for Read', 'Late Triassic', 'Norian Epoch', 216.0, 201.0, 'herbivore', 'High canopy ferns.', 'terrestrial', 'Sauropodomorph', 'valid', 8.0, 2.5, 1300, 'Africa', 'South Africa', 'Elliot Formation', [-30.5, 27.5], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Saurischia', 'Melanorosauridae', 'Melanorosaurus', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop', 'Named by Haughton in 1924.', ['Quadrupedal early sauropodomorph.', 'Massive weight-bearing limb bones.', 'Found in Upper Elliot beds.'], [{'citation': 'Haughton, S.H. (1924). Ann. S. Afr. Mus.', 'url': 'https://commons.wikimedia.org'}]))
data.append(make('Eocursor parvus', 'Eocursor parvus', 'Dawn runner small', 'Late Triassic', 'Norian Epoch', 210.0, 200.0, 'herbivore', 'Low foliage.', 'terrestrial', 'Ornithischian', 'valid', 1.0, 0.3, 2, 'Africa', 'South Africa', 'Elliot Formation', [-30.5, 27.5], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Ornithischia', 'Basal Ornithischia', 'Eocursor', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop', 'Described by Richard Butler et al. in 2007.', ['One of the earliest known ornithischian dinosaurs.', 'Extremely long grasping hands.', 'Fast agile bipedal runner.'], [{'citation': 'Butler, R.J., et al. (2007). Proc. R. Soc. B.', 'url': 'https://doi.org/10.1098/rspb.2007.0367'}]))

# --- KEM KEM BEDS (Morocco) ---
data.append(make('Deltadromeus agilis', 'Deltadromeus agilis', 'Delta runner agile', 'Late Cretaceous', 'Cenomanian Epoch', 98.0, 93.0, 'carnivore', 'Agile predator preying on medium tetrapods.', 'terrestrial', 'Theropod', 'valid', 8.0, 2.2, 1050, 'Africa', 'Morocco', 'Kem Kem Beds', [31.2, -4.0], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Saurischia', 'Noasauridae', 'Deltadromeus', 'https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop', 'Described by Paul Sereno in 1996.', ['Exceptionally long, slender leg bones.', 'Built for extreme sprinting speed.', 'Elongated body.'], [{'citation': 'Sereno, P.C., et al. (1996). Science.', 'url': 'https://doi.org/10.1126/science.272.5264.986'}]))
data.append(make('Rebbachisaurus garasbae', 'Rebbachisaurus garasbae', 'Ait Rebbach lizard from Garasba', 'Late Cretaceous', 'Cenomanian Epoch', 99.0, 93.0, 'herbivore', 'High mangrove trees.', 'terrestrial', 'Sauropod', 'valid', 20.0, 5.5, 12000, 'Africa', 'Morocco', 'Kem Kem Beds', [31.2, -4.0], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Saurischia', 'Rebbachisauridae', 'Rebbachisaurus', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop', 'Described by Rene Lavocat in 1954.', ['Tall paddle-like ridge along back neural spines.', 'Basal diplodocoid sauropod.', 'Inhabited Kem Kem river system.'], [{'citation': 'Lavocat, R. (1954). C. R. 19th Int. Geol. Congr.', 'url': 'https://commons.wikimedia.org'}]))
data.append(make('Onchopristis numidus', 'Onchopristis numidus', 'Giant barb sawfish from Numidia', 'Late Cretaceous', 'Cenomanian Epoch', 98.0, 93.0, 'piscivore', 'Benthic prey and fish.', 'freshwater', 'Invertebrate', 'valid', 8.0, 1.2, 1500, 'Africa', 'Morocco', 'Kem Kem Beds', [31.2, -4.0], 'Eukaryota', 'Animalia', 'Chordata', 'Chondrichthyes', 'Rhinopristiformes', 'Sclerorhynchidae', 'Onchopristis', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop', 'First described by Stromer in 1917.', ['Giant 2.5-meter long saw-like rostrum.', 'Barb-like teeth along sides of saw.', 'Primary prey item for Spinosaurus.'], [{'citation': 'Stromer, E. (1917). Abh. Bayer. Akad. Wiss.', 'url': 'https://commons.wikimedia.org'}]))
data.append(make('Alanqa saharica', 'Alanqa saharica', 'Named for Al-Anqa of Sahara', 'Late Cretaceous', 'Cenomanian Epoch', 98.0, 93.0, 'carnivore', 'Small vertebrates and crabs.', 'aerial', 'Pterosaur', 'valid', 6.0, 1.5, 20, 'Africa', 'Morocco', 'Kem Kem Beds', [31.2, -4.0], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Pterosauria', 'Azhdarchidae', 'Alanqa', 'https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop', 'Described by Nizar Ibrahim et al. in 2010.', ['Azhdarchid pterosaur.', 'Bony eminence along jaw margin for crushing hard shell prey.', 'Stork-like terrestrial hunter.'], [{'citation': 'Ibrahim, N., et al. (2010). PLoS ONE.', 'url': 'https://doi.org/10.1371/journal.pone.0010875'}]))
data.append(make('Siroccopteryx moroccensis', 'Siroccopteryx moroccensis', 'Sirocco wind wing from Morocco', 'Late Cretaceous', 'Cenomanian Epoch', 98.0, 93.0, 'piscivore', 'Fish in Kem Kem river delta.', 'aerial', 'Pterosaur', 'valid', 5.0, 1.2, 15, 'Africa', 'Morocco', 'Kem Kem Beds', [31.2, -4.0], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Pterosauria', 'Anhangueridae', 'Siroccopteryx', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop', 'Described by Mader and Kellner in 1999.', ['Anhanguerid pterosaur with terminal crest.', 'Fine teeth for catching slippery fish.', 'Inhabited North African rivers.'], [{'citation': 'Mader, B.J. & Kellner, A.W.A. (1999). Res. Geol.', 'url': 'https://commons.wikimedia.org'}]))
data.append(make('Aegisuchus witmeri', 'Aegisuchus witmeri', 'Shield crocodile named for Lawrence Witmer', 'Late Cretaceous', 'Cenomanian Epoch', 98.0, 93.0, 'piscivore', 'Fish and aquatic prey.', 'freshwater', 'Crocodylomorph', 'valid', 15.0, 1.5, 6000, 'Africa', 'Morocco', 'Kem Kem Beds', [31.2, -4.0], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Crocodylomorpha', 'Aegyptosuchidae', 'Aegisuchus', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop', 'Described by Casey Holliday et al. in 2012.', ['Nicknamed Shieldcroc due to flat vascularized shield on top of head.', 'Skull estimated over 2 meters long.', 'Flat duck-billed jaws.'], [{'citation': 'Holliday, C.M. & Gardner, N.M. (2012). PLoS ONE.', 'url': 'https://doi.org/10.1371/journal.pone.0030446'}]))

# --- KAROO BASIN (South Africa) ---
data.append(make('Lystrosaurus murrayi', 'Lystrosaurus murrayi', 'Shovel lizard named for Murray', 'Early Triassic', 'Induan Epoch', 252.0, 248.0, 'herbivore', 'Roots, horsetails, and tubers.', 'terrestrial', 'Early_Mammal_Synapsid', 'valid', 1.0, 0.4, 30, 'Africa', 'South Africa', 'Karoo Basin', [-32.0, 25.0], 'Eukaryota', 'Animalia', 'Chordata', 'Synapsida', 'Therapsida', 'Lystrosauridae', 'Lystrosaurus', 'https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop', 'Described by Huxley in 1859.', ['Surviving survivor of Permian-Triassic extinction.', 'Made up over 95% of terrestrial vertebrates post-extinction.', 'Barrel chest and tusked beak.'], [{'citation': 'Huxley, T.H. (1859). Q. J. Geol. Soc. Lond.', 'url': 'https://commons.wikimedia.org'}]))
data.append(make('Moschops capensis', 'Moschops capensis', 'Calf face from Cape Province', 'Permian', 'Guadalupian Epoch', 265.0, 260.0, 'herbivore', 'Tough Permian cycads and horsetails.', 'terrestrial', 'Early_Mammal_Synapsid', 'valid', 2.7, 1.5, 800, 'Africa', 'South Africa', 'Karoo Basin', [-32.0, 25.0], 'Eukaryota', 'Animalia', 'Chordata', 'Synapsida', 'Therapsida', 'Tapinocephalidae', 'Moschops', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop', 'Described by Robert Broom in 1911.', ['Pachyostotic thick head roof up to 10 cm for headbutting.', 'Massive quadrupedal dinocephalian synapsid.', 'Heavy barrel body.'], [{'citation': 'Broom, R. (1911). Proc. Zool. Soc. Lond.', 'url': 'https://commons.wikimedia.org'}]))
data.append(make('Diictodon feliceps', 'Diictodon feliceps', 'Two teeth pointed cat head', 'Permian', 'Lopingian Epoch', 259.0, 254.0, 'herbivore', 'Roots and low plants.', 'terrestrial', 'Early_Mammal_Synapsid', 'valid', 0.5, 0.2, 3, 'Africa', 'South Africa', 'Karoo Basin', [-32.0, 25.0], 'Eukaryota', 'Animalia', 'Chordata', 'Synapsida', 'Therapsida', 'Diictodontidae', 'Diictodon', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop', 'Named by Richard Owen in 1845.', ['Burrowing dicynodont synapsid with spiral burrows.', 'Sexually dimorphic tusks.', 'Extremely abundant in Karoo.'], [{'citation': 'Owen, R. (1845). Trans. Geol. Soc. Lond.', 'url': 'https://commons.wikimedia.org'}]))
data.append(make('Gorgonops torvus', 'Gorgonops torvus', 'Gorgon face grim', 'Permian', 'Lopingian Epoch', 260.0, 254.0, 'carnivore', 'Apex predator of pareiasaurs and dinocephalians.', 'terrestrial', 'Early_Mammal_Synapsid', 'valid', 2.0, 0.8, 150, 'Africa', 'South Africa', 'Karoo Basin', [-32.0, 25.0], 'Eukaryota', 'Animalia', 'Chordata', 'Synapsida', 'Therapsida', 'Gorgonopsidae', 'Gorgonops', 'https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop', 'Named by Richard Owen in 1876.', ['Eponymous gorgonopsian saber-toothed synapsid.', 'Enormous upper saber tusks.', 'Fast semi-erect runner.'], [{'citation': 'Owen, R. (1876). Descr. Cat. Foss. Rept. S. Africa.', 'url': 'https://commons.wikimedia.org'}]))
data.append(make('Rubidgea atrox', 'Rubidgea atrox', 'Named for Bruce Rubidge, fierce', 'Permian', 'Lopingian Epoch', 256.0, 253.0, 'carnivore', 'Large dicynodonts and pareiasaurs.', 'terrestrial', 'Early_Mammal_Synapsid', 'valid', 3.4, 1.2, 400, 'Africa', 'South Africa', 'Karoo Basin', [-32.0, 25.0], 'Eukaryota', 'Animalia', 'Chordata', 'Synapsida', 'Therapsida', 'Gorgonopsidae', 'Rubidgea', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop', 'Named by Robert Broom in 1938.', ['Largest apex gorgonopsian saber-tooth in South Africa.', 'Enormous heavy skull over 50 cm.', 'Massive crushing jaw power.'], [{'citation': 'Broom, R. (1938). Ann. Transv. Mus.', 'url': 'https://commons.wikimedia.org'}]))
data.append(make('Procynosuchus delaharpeae', 'Procynosuchus delaharpeae', 'Before dog crocodile named for De La Harpe', 'Permian', 'Lopingian Epoch', 259.0, 254.0, 'carnivore', 'Fish and small prey.', 'freshwater', 'Early_Mammal_Synapsid', 'valid', 0.6, 0.2, 5, 'Africa', 'South Africa', 'Karoo Basin', [-32.0, 25.0], 'Eukaryota', 'Animalia', 'Chordata', 'Synapsida', 'Therapsida', 'Procynosuchidae', 'Procynosuchus', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop', 'Described by Robert Broom in 1937.', ['One of the earliest semi-aquatic cynodonts.', 'Flexible spine for otter-like swimming.', 'Primitive mammal ancestor.'], [{'citation': 'Broom, R. (1937). Ann. Mag. Nat. Hist.', 'url': 'https://commons.wikimedia.org'}]))
data.append(make('Anteosaurus magnificus', 'Anteosaurus magnificus', 'Previous lizard magnificent', 'Permian', 'Guadalupian Epoch', 265.0, 260.0, 'carnivore', 'Apex predator of Tapinocephalus and Moschops.', 'terrestrial', 'Early_Mammal_Synapsid', 'valid', 5.0, 1.8, 600, 'Africa', 'South Africa', 'Karoo Basin', [-32.0, 25.0], 'Eukaryota', 'Animalia', 'Chordata', 'Synapsida', 'Therapsida', 'Anteosauridae', 'Anteosaurus', 'https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop', 'Named by Lieuwe Dirk Boonstra in 1954.', ['Massive carnivorous dinocephalian synapsid.', 'Thickened skull roof for head-butting rivals.', 'Large curved incisors.'], [{'citation': 'Boonstra, L.D. (1954). Ann. S. Afr. Mus.', 'url': 'https://commons.wikimedia.org'}]))

# --- WINTON FORMATION (Australia) ---
data.append(make('Australovenator wintonensis', 'Australovenator wintonensis', 'Southern hunter from Winton', 'Early Cretaceous', 'Albian Epoch', 95.0, 92.0, 'carnivore', 'Preyed on sauropods and ornithopods.', 'terrestrial', 'Theropod', 'valid', 6.0, 2.0, 500, 'Oceania', 'Australia', 'Winton Formation', [-22.4, 143.0], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Saurischia', 'Megaraptoridae', 'Australovenator', 'https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop', 'Discovered in 2006 near Winton, Queensland (nicknamed Banjo).', ['Apex megaraptorid predator of Cretaceous Australia.', 'Large scythe-like claws on hands.', 'Lightweight agile runner.'], [{'citation': 'Hocknull, S.A., et al. (2009). PLoS ONE.', 'url': 'https://doi.org/10.1371/journal.pone.0006190'}]))
data.append(make('Diamantinasaurus matildae', 'Diamantinasaurus matildae', 'Diamantina River lizard', 'Early Cretaceous', 'Albian Epoch', 95.0, 92.0, 'herbivore', 'Conifers and ferns.', 'terrestrial', 'Sauropod', 'valid', 16.0, 4.0, 15000, 'Oceania', 'Australia', 'Winton Formation', [-22.4, 143.0], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Saurischia', 'Diamantinasauria', 'Diamantinasaurus', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop', 'Described by Scott Hocknull et al. in 2009.', ['Robust stocky titanosaurian.', 'Found alongside Australovenator in Matilda site.', 'Advanced limb adaptations.'], [{'citation': 'Hocknull, S.A., et al. (2009). PLoS ONE.', 'url': 'https://doi.org/10.1371/journal.pone.0006190'}]))
data.append(make('Savannasaurus elliottorum', 'Savannasaurus elliottorum', 'Savannah lizard named for Elliott family', 'Early Cretaceous', 'Albian Epoch', 95.0, 92.0, 'herbivore', 'Canopy foliage.', 'terrestrial', 'Sauropod', 'valid', 15.0, 3.0, 18000, 'Oceania', 'Australia', 'Winton Formation', [-22.4, 143.0], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Saurischia', 'Diamantinasauria', 'Savannasaurus', 'https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop', 'Described by Stephen Poropat et al. in 2016.', ['Wide-hipped barrel-bodied titanosaur.', 'Demonstrates sauropod dispersal via Antarctica.', 'Extremely wide torso.'], [{'citation': 'Poropat, S.F., et al. (2016). Sci. Rep.', 'url': 'https://doi.org/10.1038/srep34405'}]))
data.append(make('Australotitan cooperensis', 'Australotitan cooperensis', 'Southern titan from Cooper Creek', 'Early Cretaceous', 'Albian Epoch', 95.0, 92.0, 'herbivore', 'High canopy foliage.', 'terrestrial', 'Sauropod', 'valid', 30.0, 6.5, 60000, 'Oceania', 'Australia', 'Winton Formation', [-22.4, 143.0], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Saurischia', 'Diamantinasauria', 'Australotitan', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop', 'Described by Scott Hocknull in 2021.', ['Largest dinosaur species ever discovered in Australia.', '30-meter length and 6.5m hip height.', 'Top 15 giant sauropods worldwide.'], [{'citation': 'Hocknull, S.A., et al. (2021). PeerJ.', 'url': 'https://doi.org/10.7717/peerj.11317'}]))
data.append(make('Isisfordia duncani', 'Isisfordia duncani', 'Isisford crocodile named for Ian Duncan', 'Early Cretaceous', 'Albian Epoch', 98.0, 95.0, 'carnivore', 'Small fish and vertebrates.', 'freshwater', 'Crocodylomorph', 'valid', 1.1, 0.2, 5, 'Oceania', 'Australia', 'Winton Formation', [-22.4, 143.0], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Crocodylomorpha', 'Eusuchia', 'Isisfordia', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop', 'Discovered in 1995 near Isisford, Queensland.', ['Oldest ancestor of modern true crocodiles (Eusuchia).', 'Ball-and-socket vertebrae.', 'Complete secondary palate.'], [{'citation': 'Salisbury, S.W., et al. (2006). Proc. R. Soc. B.', 'url': 'https://doi.org/10.1098/rspb.2006.3613'}]))
data.append(make('Ferrodraco lentoni', 'Ferrodraco lentoni', 'Iron dragon named for Bob Lenton', 'Early Cretaceous', 'Cenomanian Epoch', 96.0, 90.0, 'piscivore', 'Fish in river systems.', 'aerial', 'Pterosaur', 'valid', 4.0, 1.0, 10, 'Oceania', 'Australia', 'Winton Formation', [-22.4, 143.0], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Pterosauria', 'Anhangueridae', 'Ferrodraco', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop', 'Discovered in ironstone near Winton in 2017.', ['Most complete pterosaur skeleton from Australia.', 'Large crest at front of upper jaw.', 'Anhanguerid fisherman.'], [{'citation': 'Pentland, A.H., et al. (2019). Sci. Rep.', 'url': 'https://doi.org/10.1038/s41598-019-50794-1'}]))

# --- LIGHTNING RIDGE (Australia) ---
data.append(make('Muttaburrasaurus langdoni', 'Muttaburrasaurus langdoni', 'Muttaburra lizard named for Doug Langdon', 'Early Cretaceous', 'Albian Epoch', 105.0, 100.0, 'herbivore', 'Conifers and cycads.', 'terrestrial', 'Ornithischian', 'valid', 8.0, 2.5, 2800, 'Oceania', 'Australia', 'Lightning Ridge', [-29.4, 147.9], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Ornithischia', 'Rhabdodontomorpha', 'Muttaburrasaurus', 'https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop', 'First discovered by Doug Langdon in 1963.', ['Hollow inflatable nasal chamber for vocal resonance.', 'Shearing teeth for tough vegetation.', 'Most famous Australian ornithopod.'], [{'citation': 'Bartholomai, A. & Molnar, R.E. (1981). Mem. Queensl. Mus.', 'url': 'https://commons.wikimedia.org'}]))
data.append(make('Rapator ornithestoid', 'Rapator ornithestoid', 'Plunderer bird-like', 'Early Cretaceous', 'Albian Epoch', 110.0, 105.0, 'carnivore', 'Predatory hunter.', 'terrestrial', 'Theropod', 'valid', 6.0, 2.0, 500, 'Oceania', 'Australia', 'Lightning Ridge', [-29.4, 147.9], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Saurischia', 'Megaraptoridae', 'Rapator', 'https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop', 'Described by Arthur Smith Woodward in 1932.', ['Opalized hand bone showing massive claw.', 'Early Australian megaraptorid.', 'Found in Lightning Ridge opal mines.'], [{'citation': 'Woodward, A.S. (1932). Ann. Mag. Nat. Hist.', 'url': 'https://doi.org/10.1080/00222933208673565'}]))
data.append(make('Fostoria dhimbangunmal', 'Fostoria dhimbangunmal', 'Named for Robert Foster', 'Early Cretaceous', 'Albian Epoch', 100.0, 98.0, 'herbivore', 'Low foliage.', 'terrestrial', 'Ornithischian', 'valid', 5.0, 1.8, 600, 'Oceania', 'Australia', 'Lightning Ridge', [-29.4, 147.9], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Ornithischia', 'Iguanodontia', 'Fostoria', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop', 'Discovered in 1984 by opal miner Robert Foster.', ['Fossil herd of opalized iguanodontians.', 'First opalized dinosaur herd in the world.', 'Direct relative of Muttaburrasaurus.'], [{'citation': 'Bell, P.R., et al. (2019). PeerJ.', 'url': 'https://doi.org/10.7717/peerj.6922'}]))
data.append(make('Weewarrasaurus pobeni', 'Weewarrasaurus pobeni', 'Wee Warra opal field lizard', 'Early Cretaceous', 'Albian Epoch', 100.0, 98.0, 'herbivore', 'Low ferns.', 'terrestrial', 'Ornithischian', 'valid', 1.5, 0.5, 15, 'Oceania', 'Australia', 'Lightning Ridge', [-29.4, 147.9], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Ornithischia', 'Basal Ornithopoda', 'Weewarrasaurus', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop', 'Described by Phil Bell et al. in 2018.', ['Preserved in solid precious opal.', 'Small bipedal ornithopod.', 'Found in Wee Warra opal mine.'], [{'citation': 'Bell, P.R., et al. (2018). PeerJ.', 'url': 'https://doi.org/10.7717/peerj.6042'}]))
data.append(make('Lightningclaw', 'Lightningclaw', 'Claw from Lightning Ridge', 'Early Cretaceous', 'Albian Epoch', 110.0, 105.0, 'carnivore', 'Sauropods and small dinosaurs.', 'terrestrial', 'Theropod', 'valid', 7.0, 2.2, 700, 'Oceania', 'Australia', 'Lightning Ridge', [-29.4, 147.9], 'Eukaryota', 'Animalia', 'Chordata', 'Reptilia', 'Saurischia', 'Megaraptoridae', 'Lightningclaw', 'https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop', 'Described by Bell et al. in 2015.', ['Largest theropod discovered in Australia prior to Australovenator.', 'Opalized giant scythe claw.', 'Megaraptorid predator.'], [{'citation': 'Bell, P.R., et al. (2015). Gondwana Res.', 'url': 'https://doi.org/10.1016/j.gr.2015.08.004'}]))
data.append(make('Steropodon galmani', 'Steropodon galmani', 'Lightning tooth', 'Early Cretaceous', 'Albian Epoch', 105.0, 100.0, 'carnivore', 'Insects and invertebrates.', 'freshwater', 'Early_Mammal_Synapsid', 'valid', 0.5, 0.15, 2, 'Oceania', 'Australia', 'Lightning Ridge', [-29.4, 147.9], 'Eukaryota', 'Animalia', 'Chordata', 'Mammalia', 'Monotremata', 'Steropodontidae', 'Steropodon', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop', 'Discovered in 1985 in an opalized jaw.', ['First Mesozoic mammal found in Australia.', 'Oldest ancestor of the platypus.', 'Preserved in blue-green precious opal.'], [{'citation': 'Archer, M., et al. (1985). Nature.', 'url': 'https://doi.org/10.1038/318363a0'}]))
data.append(make('Kollikodon ritchiei', 'Kollikodon ritchiei', 'Tool tooth named for Alex Ritchie', 'Early Cretaceous', 'Albian Epoch', 105.0, 100.0, 'carnivore', 'Crushing shellfish and crustaceans.', 'freshwater', 'Early_Mammal_Synapsid', 'valid', 1.0, 0.3, 5, 'Oceania', 'Australia', 'Lightning Ridge', [-29.4, 147.9], 'Eukaryota', 'Animalia', 'Chordata', 'Mammalia', 'Monotremata', 'Kollikodontidae', 'Kollikodon', 'https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop', 'Discovered in 1995 in an opalized dentary bone.', ['Giant early monotreme mammal.', 'Molar teeth with rounded crushing cusps.', 'Opalized fossil specimen.'], [{'citation': 'Flannery, T.F., et al. (1995). Nature.', 'url': 'https://doi.org/10.1038/377418a0'}]))

with open('d:/My folders/AI 1.0/Prehistoric encylcopedia/backend/all_new_species.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2)

print(f'Total species compiled into all_new_species.json: {len(data)}')
