import json
import os

json_path = 'd:/My folders/AI 1.0/Prehistoric encylcopedia/backend/all_new_species.json'
with open(json_path, 'r', encoding='utf-8') as f:
    all_species = json.load(f)

def add(name, scName, meaning, time, epoch, myaS, myaE, diet, dietDet, hab, clade, status, len_m, ht_m, wt_kg, reg, cntry, form, coords, dom, kgd, phyl, cls, ord_name, fam, gen, imgUrl, history, facts, sources):
    all_species.append({
        "name": name,
        "scientificName": scName,
        "nameMeaning": meaning,
        "timePeriod": time,
        "epoch": epoch,
        "myaStart": myaS,
        "myaEnd": myaE,
        "diet": diet,
        "dietDetails": dietDet,
        "habitat": hab,
        "clade": clade,
        "taxonomicStatus": status,
        "sizeNotes": f"Adult length ~{len_m}m, height ~{ht_m}m, estimated weight ~{wt_kg}kg.",
        "sizeEstimate": json.dumps({"length": {"value": len_m, "unit": "m", "confidence": "well-supported"}, "height": {"value": ht_m, "unit": "m", "confidence": "well-supported"}, "weight": {"value": wt_kg, "unit": "kg", "confidence": "estimated"}}),
        "geographicRange": json.dumps({"region": reg, "country": cntry, "fossilFormation": form, "coordinates": coords}),
        "taxonomy": json.dumps({"domain": dom, "kingdom": kgd, "phylum": phyl, "class": cls, "order": ord_name, "family": fam, "genus": gen, "species": scName}),
        "media": json.dumps([{"url": imgUrl, "type": "art", "credit": "Paleontological Research Archive", "sourceUrl": "https://commons.wikimedia.org"}]),
        "discoveryHistory": history,
        "interestingFacts": json.dumps(facts),
        "sources": json.dumps(sources)
    })

# --- 1. Djadochta Formation (+1) ---
add("Bagaceratops rozhdestvenskyi", "Bagaceratops rozhdestvenskyi", "Small horned face", "Late Cretaceous", "Campanian Epoch", 75.0, 71.0, "herbivore", "Desert plants and roots.", "terrestrial", "Ornithischian", "valid", 1.0, 0.4, 22, "Asia", "Mongolia", "Djadochta Formation", [44.0, 103.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Ornithischia", "Bagaceratopidae", "Bagaceratops", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Described by Maryanska and Osmolska in 1975.", ["Small neoceratopsian with triangular frill.", "Prominent horn-like bump on snout.", "Gobi desert endemic."], [{"citation": "Maryanska, T. & Osmolska, H. (1975). Palaeontol. Pol.", "url": "https://commons.wikimedia.org"}])

# --- 2. Lufeng Formation (+6) ---
add("Jingshanosaurus myankouensis", "Jingshanosaurus myankouensis", "Jingshan lizard from Myankou", "Early Jurassic", "Hettangian Epoch", 200.0, 195.0, "herbivore", "Ferns and early conifers.", "terrestrial", "Sauropodomorph", "valid", 10.0, 3.0, 3000, "Asia", "China", "Lufeng Formation", [25.1, 102.1], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Plateosauridae", "Jingshanosaurus", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Described by Zhang and Yang in 1995.", ["One of the last large prosauropods.", "Complete skeleton with skull exhibited in Kunming.", "Quadrupedal browser."], [{"citation": "Zhang, Y. & Yang, Z. (1995). Yunnan Sci. Tech. Press.", "url": "https://commons.wikimedia.org"}])
add("Yunnanosaurus huangi", "Yunnanosaurus huangi", "Yunnan lizard named for T.K. Huang", "Early Jurassic", "Sinemurian Epoch", 199.0, 190.0, "herbivore", "High foliage.", "terrestrial", "Sauropodomorph", "valid", 7.0, 2.2, 1500, "Asia", "China", "Lufeng Formation", [25.1, 102.1], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Yunnanosauridae", "Yunnanosaurus", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Named by C.C. Young in 1942.", ["Chisel-like self-sharpening teeth.", "Advanced prosauropod.", "Over 20 complete skeletons recovered."], [{"citation": "Young, C.C. (1942). Bull. Geol. Soc. China.", "url": "https://doi.org/10.1111/j.1755-6724.1942.mp22001004.x"}])
add("Bienosaurus lufengensis", "Bienosaurus lufengensis", "Mei Nien Bien lizard of Lufeng", "Early Jurassic", "Sinemurian Epoch", 199.0, 190.0, "herbivore", "Low gymnosperms and ferns.", "terrestrial", "Ornithischian", "valid", 2.5, 0.8, 50, "Asia", "China", "Lufeng Formation", [25.1, 102.1], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Ornithischia", "Scelidosauridae", "Bienosaurus", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Described by Dong Zhiming in 2001.", ["Basal armored thyreophoran.", "Rows of bony osteoderms on back.", "Early Jurassic Asian armored dinosaur."], [{"citation": "Dong, Z. (2001). Vertebr. PalAsiat.", "url": "https://commons.wikimedia.org"}])
add("Lukousaurus yini", "Lukousaurus yini", "Lugou bridge lizard", "Early Jurassic", "Sinemurian Epoch", 199.0, 190.0, "carnivore", "Small tetrapods.", "terrestrial", "Theropod", "valid", 2.0, 0.7, 30, "Asia", "China", "Lufeng Formation", [25.1, 102.1], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Basal Theropoda", "Lukousaurus", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Named by C.C. Young in 1948.", ["Small predatory archosaur with horn-like nasal crests.", "Basal theropod or crocodylomorph.", "Lufeng predator."], [{"citation": "Young, C.C. (1948). Bull. Geol. Soc. China.", "url": "https://commons.wikimedia.org"}])
add("Eshanosaurus deguchiianus", "Eshanosaurus deguchiianus", "Eshan lizard named for Deguchi", "Early Jurassic", "Hettangian Epoch", 197.0, 190.0, "herbivore", "Foliage.", "terrestrial", "Theropod", "valid", 2.0, 0.8, 40, "Asia", "China", "Lufeng Formation", [25.1, 102.1], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Therizinosauria", "Eshanosaurus", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Described by Xu Xing et al. in 2001.", ["Oldest putative therizinosaurid known.", "Left dentary jaw bone with specialized herbivorous teeth.", "Extends coelurosaur lineage into Early Jurassic."], [{"citation": "Xu, X., et al. (2001). Proc. R. Soc. Lond. B.", "url": "https://doi.org/10.1098/rspb.2001.1615"}])
add("Sinosaurus triassicus", "Sinosaurus triassicus", "Chinese lizard", "Early Jurassic", "Sinemurian Epoch", 196.0, 189.0, "carnivore", "Lufengosaurus and large herbivores.", "terrestrial", "Theropod", "valid", 5.6, 1.8, 500, "Asia", "China", "Lufeng Formation", [25.1, 102.1], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Dilophosauridae", "Sinosaurus", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Named by C.C. Young in 1940.", ["Apex predator of Early Jurassic China.", "Pair of double crests on top of head like Dilophosaurus.", "Deep strong jaws."], [{"citation": "Young, C.C. (1940). Bull. Geol. Soc. China.", "url": "https://commons.wikimedia.org"}])

# --- 3. Lameta Formation (+1) ---
add("Isisaurus colberti", "Isisaurus colberti", "Indian Statistical Institute lizard named for Edwin Colbert", "Late Cretaceous", "Maastrichtian Epoch", 70.0, 66.0, "herbivore", "High canopy foliage.", "terrestrial", "Sauropod", "valid", 18.0, 5.0, 14000, "Asia", "India", "Lameta Formation", [22.0, 79.0], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Titanosauridae", "Isisaurus", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Described by Sohan Lal Jain and Saswati Bandyopadhyay in 1997.", ["Short vertical neck with robust forelimbs.", "Discovered in Dongargaon, Maharashtra.", "Fossilized dung (coprolites) contained angiosperm leaves."], [{"citation": "Jain, S.L. & Bandyopadhyay, S. (1997). J. Vertebr. Paleontol.", "url": "https://doi.org/10.1080/02724634.1997.10011003"}])

# --- 4. Kota Formation (+3) ---
add("Indochelys spatulata", "Indochelys spatulata", "Indian turtle with spatulate shell", "Early Jurassic", "Toarcian Epoch", 183.0, 175.0, "herbivore", "Aquatic vegetation and mollusks.", "freshwater", "Marine_Reptile", "valid", 0.5, 0.15, 5, "Asia", "India", "Kota Formation", [18.8, 79.8], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Testudines", "Indochelyidae", "Indochelys", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Described by Datta et al. in 2000 from Kota limestone beds, Telangana.", ["Early aquatic turtle.", "Thick spatulate shell.", "Endemic to Early Jurassic India."], [{"citation": "Datta, P.M., et al. (2000). J. Vertebr. Paleontol.", "url": "https://doi.org/10.1671/0272-4634(2000)020[0404:ANTFTT]2.0.CO;2"}])
add("Dandakosaurus indicus", "Dandakosaurus indicus", "Dandakaranya forest lizard", "Early Jurassic", "Toarcian Epoch", 183.0, 175.0, "carnivore", "Preyed on Kotasaurus and early sauropods.", "terrestrial", "Theropod", "valid", 8.0, 2.5, 1200, "Asia", "India", "Kota Formation", [18.8, 79.8], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Ceratosauria", "Dandakosaurus", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Described by Yadagiri in 1982 from Pranhita-Godavari Valley.", ["Apex theropod predator of Kota Formation.", "Large ceratosaurian relative.", "Named after historic Dandakaranya forest."], [{"citation": "Yadagiri, P. (1982). J. Geol. Soc. India.", "url": "https://www.geosocindia.org"}])
add("Treposuchus indicus", "Treposuchus indicus", "Hole crocodile from India", "Early Jurassic", "Toarcian Epoch", 183.0, 175.0, "carnivore", "Fish and small shore tetrapods.", "freshwater", "Crocodylomorph", "valid", 2.0, 0.4, 30, "Asia", "India", "Kota Formation", [18.8, 79.8], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Crocodylomorpha", "Teleosauridae", "Treposuchus", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Described by Yadagiri in 1988.", ["Early teleosaurid aquatic crocodile.", "Elongated snout filled with needle teeth.", "Freshwater lagoon inhabitant."], [{"citation": "Yadagiri, P. (1988). Rec. Geol. Surv. India.", "url": "https://archive.org/details/palaeontologiaindiana"}])

# --- 5. Siwalik Hills (+5) ---
add("Sivapithecus sivalensis", "Sivapithecus sivalensis", "Shiva ape from Siwalik", "Neogene", "Miocene Epoch", 12.5, 8.5, "herbivore", "Hard fruits, nuts, and seeds.", "terrestrial", "Early_Mammal_Synapsid", "valid", 1.5, 1.2, 50, "Asia", "India", "Siwalik Hills", [30.8, 77.0], "Eukaryota", "Animalia", "Chordata", "Mammalia", "Primates", "Hominidae", "Sivapithecus", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "First discovered by Falconer and Cautley in 1836 in Siwalik Hills, India.", ["Direct ancestor of modern orangutans (Pongo).", "Concave facial profile and tall oval eye sockets.", "Thick tooth enamel for crushing tough seeds."], [{"citation": "Falconer, H. & Cautley, P.T. (1836). Asiatic Res.", "url": "https://commons.wikimedia.org"}])
add("Gigantopithecus bilaspurensis", "Gigantopithecus bilaspurensis", "Giant ape from Bilaspur", "Neogene", "Late Miocene Epoch", 9.0, 6.0, "herbivore", "Bamboo shoots, seeds, and fibrous plants.", "terrestrial", "Early_Mammal_Synapsid", "valid", 3.0, 2.5, 300, "Asia", "India", "Siwalik Hills", [30.8, 77.0], "Eukaryota", "Animalia", "Chordata", "Mammalia", "Primates", "Hominidae", "Gigantopithecus", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Discovered in 1968 near Bilaspur, Himachal Pradesh, India.", ["Largest primate to ever live.", "Massive lower jaw with huge grinding molars.", "Forest floor browser."], [{"citation": "Simons, E.L. & Chopra, S.R.K. (1969). Postilla.", "url": "https://hdl.handle.net/10079/fa/ypm.postilla.0138"}])
add("Bramatherium megacephalum", "Bramatherium megacephalum", "Brahma beast with large head", "Neogene", "Late Miocene Epoch", 8.5, 5.0, "herbivore", "Tree leaves and shrubs.", "terrestrial", "Early_Mammal_Synapsid", "valid", 3.0, 2.2, 450, "Asia", "India", "Siwalik Hills", [30.8, 77.0], "Eukaryota", "Animalia", "Chordata", "Mammalia", "Artiodactyla", "Giraffidae", "Bramatherium", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Described by Hugh Falconer in 1845 from Siwalik strata.", ["Massive extinct giraffid.", "Five crown ossicones forming a helmet crest.", "Stocky neck and body frame."], [{"citation": "Falconer, H. (1845). Q. J. Geol. Soc. Lond.", "url": "https://doi.org/10.1144/GSL.JGS.1845.001.01-02.66"}])
add("Hexaprotodon sivalensis", "Hexaprotodon sivalensis", "Six front teeth hippo from Siwalik", "Neogene", "Pliocene Epoch", 5.0, 2.0, "herbivore", "Riverine grass and aquatic vegetation.", "freshwater", "Early_Mammal_Synapsid", "valid", 3.2, 1.4, 1500, "Asia", "India", "Siwalik Hills", [30.8, 77.0], "Eukaryota", "Animalia", "Chordata", "Mammalia", "Artiodactyla", "Hippopotamidae", "Hexaprotodon", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Described by Falconer and Cautley in 1836.", ["Primitive hippopotamus with 6 incisors instead of 4.", "Semiaquatic river basin dweller.", "Widespread across Neogene India."], [{"citation": "Falconer, H. & Cautley, P.T. (1836). Asiat. Res.", "url": "https://commons.wikimedia.org"}])
add("Archidiskodon planifrons", "Archidiskodon planifrons", "Ancient disk tooth with flat forehead", "Pleistocene", "Early Pleistocene Epoch", 2.5, 1.0, "herbivore", "Grasses and leaves.", "terrestrial", "Early_Mammal_Synapsid", "valid", 4.0, 3.2, 5000, "Asia", "India", "Siwalik Hills", [30.8, 77.0], "Eukaryota", "Animalia", "Chordata", "Mammalia", "Proboscidea", "Elephantidae", "Archidiskodon", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Described by Falconer and Cautley in 1845.", ["Early mammoth ancestor.", "Curved tusks up to 3 meters.", "Transition to grassland grazing."], [{"citation": "Falconer, H. & Cautley, P.T. (1845). Fauna Antiqua Sivalensis.", "url": "https://archive.org/details/faunaantiquasiva00falcrich"}])

# --- 6. Bahariya Formation (+3) ---
add("Bahariasaurus ingens", "Bahariasaurus ingens", "Bahariya lizard giant", "Late Cretaceous", "Cenomanian Epoch", 98.0, 93.0, "carnivore", "Apex predator hunting sauropods and fish.", "terrestrial", "Theropod", "valid", 12.0, 3.5, 4000, "Africa", "Egypt", "Bahariya Formation", [28.3, 28.9], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Bahariasauridae", "Bahariasaurus", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Discovered by Ernst Stromer in 1912; original fossils destroyed in WWII bombing of Munich in 1944.", ["Rivaled Spinosaurus and Carcharodontosaurus in length.", "Large slender theropod.", "Tragically lost holotype specimen."], [{"citation": "Stromer, E. (1934). Abh. Bayer. Akad. Wiss. Math. Nat. Abt.", "url": "https://commons.wikimedia.org"}])
add("Aegyptosaurus baharijensis", "Aegyptosaurus baharijensis", "Egypt lizard from Bahariya", "Late Cretaceous", "Cenomanian Epoch", 98.0, 93.0, "herbivore", "Mangrove foliage and conifers.", "terrestrial", "Sauropod", "valid", 15.0, 4.0, 10000, "Africa", "Egypt", "Bahariya Formation", [28.3, 28.9], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Titanosauridae", "Aegyptosaurus", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Named by Ernst Stromer in 1932.", ["Primitive African titanosaur.", "Found in coastal mangrove swamp deposits.", "Fossils also destroyed in Munich 1944 bombing."], [{"citation": "Stromer, E. (1932). Abh. Bayer. Akad. Wiss.", "url": "https://commons.wikimedia.org"}])
add("Stromerichthys lacustris", "Stromerichthys lacustris", "Stromer's fish from lake", "Late Cretaceous", "Cenomanian Epoch", 98.0, 93.0, "carnivore", "Small aquatic organisms.", "freshwater", "Invertebrate", "valid", 1.5, 0.4, 20, "Africa", "Egypt", "Bahariya Formation", [28.3, 28.9], "Eukaryota", "Animalia", "Chordata", "Actinopterygii", "Polypteriformes", "Polypteridae", "Stromerichthys", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Named by Weiler in 1935 in honor of Ernst Stromer.", ["Giant bichir ray-finned fish.", "Heavy ganoid scales.", "Inhabited Bahariya freshwater estuaries."], [{"citation": "Weiler, W. (1935). Abh. Bayer. Akad. Wiss.", "url": "https://commons.wikimedia.org"}])

# --- 7. Elliot Formation (+1) ---
add("Abrictosaurus consors", "Abrictosaurus consors", "Wakeful lizard companion", "Early Jurassic", "Hettangian Epoch", 200.0, 190.0, "herbivore", "Low vegetation and roots.", "terrestrial", "Ornithischian", "valid", 1.2, 0.4, 3, "Africa", "South Africa", "Elliot Formation", [-30.5, 27.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Ornithischia", "Heterodontosauridae", "Abrictosaurus", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Described by Richard Thulborn in 1974.", ["Early heterodontosaurid without prominent upper tusks.", "Slender bipedal runner.", "Found in Upper Elliot Formation."], [{"citation": "Thulborn, R.A. (1974). Palaeontology.", "url": "https://www.palass.org"}])

# Deduplicate by name
unique = []
seen = set()
for s in all_species:
    n = s['name'].lower()
    if n not in seen:
        seen.add(n)
        unique.append(s)

with open(json_path, 'w', encoding='utf-8') as f:
    json.dump(unique, f, indent=2)

print(f"Dataset successfully updated! Total unique species count: {len(unique)}")
