import json

species_data = []

def add(name, scName, meaning, time, epoch, myaS, myaE, diet, dietDet, hab, clade, status, len_m, ht_m, wt_kg, reg, cntry, form, coords, dom, kgd, phyl, cls, ord_name, fam, gen, imgUrl, history, facts, sources):
    species_data.append({
        "name": name,
        "scientificName": scName,
        "nameMeaning": meaning,
        "timePeriod": time,
        "epoch": epoch,
        "myaStart": myaS,
        "myaEnd": myaE,
        "diet": diet,
        "dietDetails": dietDet,
        "habitat": hab,
        "clade": clade,
        "taxonomicStatus": status,
        "sizeNotes": f"Adult length ~{len_m}m, height ~{ht_m}m, estimated weight ~{wt_kg}kg.",
        "sizeEstimate": json.dumps({"length": {"value": len_m, "unit": "m", "confidence": "well-supported"}, "height": {"value": ht_m, "unit": "m", "confidence": "well-supported"}, "weight": {"value": wt_kg, "unit": "kg", "confidence": "estimated"}}),
        "geographicRange": json.dumps({"region": reg, "country": cntry, "fossilFormation": form, "coordinates": coords}),
        "taxonomy": json.dumps({"domain": dom, "kingdom": kgd, "phylum": phyl, "class": cls, "order": ord_name, "family": fam, "genus": gen, "species": scName}),
        "media": json.dumps([{"url": imgUrl, "type": "art", "credit": "Paleontological Research Archive", "sourceUrl": "https://commons.wikimedia.org"}]),
        "discoveryHistory": history,
        "interestingFacts": json.dumps(facts),
        "sources": json.dumps(sources)
    })

# --- 1. CHINLE FORMATION (USA) ---
add("Coelophysis bauri", "Coelophysis bauri", "Hollow form", "Late Triassic", "Norian Epoch", 228.0, 201.3, "carnivore", "Preyed on small reptiles and cynodonts.", "terrestrial", "Theropod", "valid", 3.0, 0.9, 25, "North America", "United States", "Chinle Formation", [35.0, -109.0], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Coelophysidae", "Coelophysis", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Discovered by E.D. Cope in 1887 in New Mexico.", ["Early agile theropod.", "Mass bonebeds at Ghost Ranch.", "Hollow thin-walled bones."], [{"citation": "Cope, E.D. (1887). Trans. Amer. Phil. Soc.", "url": "https://doi.org/10.2307/1005527"}])
add("Postosuchus kirkpatricki", "Postosuchus kirkpatricki", "Crocodile from Post Texas", "Late Triassic", "Norian Epoch", 228.0, 208.0, "carnivore", "Apex predator hunting dicynodonts.", "terrestrial", "Rauisuchian", "valid", 4.0, 1.2, 300, "North America", "United States", "Chinle Formation", [35.0, -109.0], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Rauisuchia", "Rauisuchidae", "Postosuchus", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Named by Sankar Chatterjee in 1985.", ["Apex rauisuchian predator.", "Deep skull with dagger teeth.", "Semi-bipedal posture."], [{"citation": "Chatterjee, S. (1985). Phil. Trans. R. Soc. Lond. B.", "url": "https://royalsocietypublishing.org/doi/10.1098/rstb.1985.0002"}])
add("Desmatosuchus haplocerus", "Desmatosuchus haplocerus", "Link crocodile with single horn", "Late Triassic", "Norian Epoch", 230.0, 210.0, "herbivore", "Rooted for ferns and cycads.", "terrestrial", "Aetosaur", "valid", 4.5, 1.0, 280, "North America", "United States", "Chinle Formation", [35.0, -109.0], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Aetosauria", "Stagonolepididae", "Desmatosuchus", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Described by E.C. Case in 1920.", ["Large 45 cm shoulder spines.", "Interlocking bony armor.", "Shovel snout for digging."], [{"citation": "Case, E.C. (1920). Occ. Pap. Mus. Zool.", "url": "https://hdl.handle.net/2027/spo.3523768.0001.001"}])
add("Placerias hesternus", "Placerias hesternus", "Broad body from the past", "Late Triassic", "Carnian Epoch", 230.0, 215.0, "herbivore", "Feeded on low vegetation and roots.", "terrestrial", "Early_Mammal_Synapsid", "valid", 3.5, 1.6, 1000, "North America", "United States", "Chinle Formation", [35.0, -109.0], "Eukaryota", "Animalia", "Chordata", "Synapsida", "Therapsida", "Stahleckeriidae", "Placerias", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Discovered in 1904 by F.A. Lucas in Arizona.", ["Giant 1-ton dicynodont synapsid.", "Downward-pointing tusks.", "Herding behavior."], [{"citation": "Lucas, F.A. (1904). Proc. U.S. Natl. Mus.", "url": "https://doi.org/10.5479/si.00963801.27-1353.193"}])
add("Typothorax coccinarum", "Typothorax coccinarum", "Type chest from Coccinar", "Late Triassic", "Norian Epoch", 228.0, 208.0, "herbivore", "Herbivorous diet of horsetails and ferns.", "terrestrial", "Aetosaur", "valid", 3.0, 0.7, 200, "North America", "United States", "Chinle Formation", [35.0, -109.0], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Aetosauria", "Stagonolepididae", "Typothorax", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Named by E.D. Cope in 1875.", ["Broad turtle-like armor plates.", "Heavy body defense.", "Index fossil for Late Triassic."], [{"citation": "Cope, E.D. (1875). US Geol. Surv.", "url": "https://doi.org/10.3138/9781442674394"}])
add("Rutiodon carolinensis", "Rutiodon carolinensis", "Wrinkled tooth from Carolina", "Late Triassic", "Norian Epoch", 225.0, 208.0, "piscivore", "Ambush aquatic predator preying on fish.", "freshwater", "Phytosaur", "valid", 6.0, 0.9, 500, "North America", "United States", "Chinle Formation", [35.0, -109.0], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Phytosauria", "Phytosauridae", "Rutiodon", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Described by Ebenezer Emmons in 1856.", ["6-meter aquatic archosaur.", "Raised nostril crest.", "Intermeshing fish-catching teeth."], [{"citation": "Emmons, E. (1856). Geol. Rep. N. Carolina.", "url": "https://archive.org/details/geologicalreport00emmo"}])

# --- 2. MALERI FORMATION (INDIA) ---
add("Alwalkeria maleriensis", "Alwalkeria maleriensis", "Named for Alick Walker", "Late Triassic", "Carnian Epoch", 235.0, 228.0, "omnivore", "Insects, small tetrapods, and plants.", "terrestrial", "Theropod", "valid", 1.5, 0.5, 4, "Asia", "India", "Maleri Formation", [19.0, 79.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Basal Saurischia", "Alwalkeria", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Described by Sankar Chatterjee in 1987 from Telangana, India.", ["One of oldest Indian dinosaurs.", "Heterogeneous teeth.", "Basal saurischian."], [{"citation": "Chatterjee, S. (1987). Novitates Museum.", "url": "https://hdl.handle.net/2246/3233"}])
add("Jaklapallisaurus asymmetrica", "Jaklapallisaurus asymmetrica", "Lizard from Jaklapalli village", "Late Triassic", "Norian Epoch", 220.0, 205.0, "herbivore", "Feeded on seed ferns and gymnosperms.", "terrestrial", "Sauropodomorph", "valid", 2.5, 0.8, 40, "Asia", "India", "Maleri Formation", [19.0, 79.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Plateosauridae", "Jaklapallisaurus", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Described by Fernando Novas et al. in 2011.", ["Unaysaurid plateosaurian.", "Asymmetric ankle bones.", "Gondwanan faunal interchange."], [{"citation": "Novas, F.E., et al. (2011). Zootaxa 3025.", "url": "https://doi.org/10.11646/zootaxa.3025.1.1"}])
add("Nambalia rohui", "Nambalia rohui", "Lizard from Nambal village", "Late Triassic", "Norian Epoch", 220.0, 205.0, "herbivore", "Low canopy foliage.", "terrestrial", "Sauropodomorph", "valid", 3.0, 1.0, 70, "Asia", "India", "Maleri Formation", [19.0, 79.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Guaibasauridae", "Nambalia", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Named by Novas et al. in 2011 from Pranhita-Godavari basin.", ["Guaibasaurid sauropodomorph.", "Red siltstone fossil beds.", "Evolutionary link to sauropods."], [{"citation": "Novas, F.E., et al. (2011). Zootaxa 3025.", "url": "https://doi.org/10.11646/zootaxa.3025.1.1"}])
add("Parasuchus hislopi", "Parasuchus hislopi", "Beside Crocodile named for Stephen Hislop", "Late Triassic", "Carnian Epoch", 230.0, 215.0, "piscivore", "Semiaquatic predator of fish and lungfish.", "freshwater", "Phytosaur", "valid", 4.0, 0.6, 250, "Asia", "India", "Maleri Formation", [19.0, 79.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Phytosauria", "Parasuchidae", "Parasuchus", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Named by T.H. Huxley in 1875.", ["Highly complete phytosaur.", "Exhibited at ISI Kolkata.", "Raised nasal crest."], [{"citation": "Huxley, T.H. (1875). Q. J. Geol. Soc. Lond.", "url": "https://doi.org/10.1144/GSL.JGS.1875.031.01-04.29"}])
add("Metoposaurus maleriensis", "Metoposaurus maleriensis", "Front lizard from Maleri", "Late Triassic", "Carnian Epoch", 230.0, 220.0, "carnivore", "Aquatic ambush carnivore of fish.", "freshwater", "Early_Tetrapod_Amphibian", "valid", 2.5, 0.3, 100, "Asia", "India", "Maleri Formation", [19.0, 79.5], "Eukaryota", "Animalia", "Chordata", "Amphibia", "Temnospondyli", "Metoposauridae", "Metoposaurus", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Described by D.H. Chowdhury in 1965.", ["Flat toilet-seat-shaped skull.", "Mass die-off drought deposits.", "Fully aquatic temnospondyl."], [{"citation": "Chowdhury, D.H. (1965). Phil. Trans. Roy. Soc. B.", "url": "https://doi.org/10.1098/rstb.1965.0019"}])
add("Exaeretodon statterneri", "Exaeretodon statterneri", "Outstanding tooth", "Late Triassic", "Carnian Epoch", 235.0, 225.0, "herbivore", "Tough foliage using grinding cheek teeth.", "terrestrial", "Early_Mammal_Synapsid", "valid", 1.8, 0.6, 80, "Asia", "India", "Maleri Formation", [19.0, 79.5], "Eukaryota", "Animalia", "Chordata", "Synapsida", "Therapsida", "Traversodontidae", "Exaeretodon", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Described by S. Chatterjee in 1982.", ["Traversodontid cynodont.", "Secondary palate for chewing.", "Maternal care evidence."], [{"citation": "Chatterjee, S. (1982). Palaeontology.", "url": "https://www.palass.org"}])
add("Hyperodapedon huxleyi", "Hyperodapedon huxleyi", "Pavement of teeth named for Huxley", "Late Triassic", "Carnian Epoch", 230.0, 220.0, "herbivore", "Seed ferns using scissor beak.", "terrestrial", "Archosauriform", "valid", 1.3, 0.4, 30, "Asia", "India", "Maleri Formation", [19.0, 79.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Rhynchosauria", "Hyperodapedontidae", "Hyperodapedon", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Described by R. Lydekker in 1881.", ["Beaked rhynchosaur.", "Multiple tooth rows.", "Abundant Carnian herbivore."], [{"citation": "Lydekker, R. (1881). Mem. Geol. Surv. India.", "url": "https://archive.org/details/palaeontologiaindiana"}])

# --- 11. DJADOCHTA FORMATION (MONGOLIA) ---
add("Citipati osmolskae", "Citipati osmolskae", "Funeral pyre lord (Sanskrit) named for Halszka Osmolska", "Late Cretaceous", "Campanian Epoch", 75.0, 71.0, "omnivore", "Eggs, small vertebrates, and plants.", "terrestrial", "Theropod", "valid", 2.9, 1.2, 80, "Asia", "Mongolia", "Djadochta Formation", [44.0, 103.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Oviraptoridae", "Citipati", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Discovered brooding over nests of eggs at Ukhaa Tolgod, Gobi Desert.", ["Preserved brooding on nest like modern birds.", "High crest on beak.", "Giant oviraptorid."], [{"citation": "Clark, J.M., et al. (1999). Amer. Mus. Novit.", "url": "https://hdl.handle.net/2246/3043"}])
add("Byronosaurus jaffei", "Byronosaurus jaffei", "Byron lizard named for Byron Jaffe", "Late Cretaceous", "Campanian Epoch", 75.0, 71.0, "carnivore", "Lizards and small mammals.", "terrestrial", "Theropod", "valid", 1.5, 0.5, 10, "Asia", "Mongolia", "Djadochta Formation", [44.0, 103.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Troodontidae", "Byronosaurus", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Described by Mark Norell et al. in 2000 from Ukhaa Tolgod.", ["Un-serrated needle-like teeth.", "Fossil nestlings found in oviraptorid nest.", "Slender desert hunter."], [{"citation": "Norell, M.A., et al. (2000). Amer. Mus. Novit.", "url": "https://hdl.handle.net/2246/2984"}])
add("Mahakala omnogovae", "Mahakala omnogovae", "Named after Mahakala (Tibetan Buddhist deity) of Omnogovi", "Late Cretaceous", "Campanian Epoch", 75.0, 71.0, "carnivore", "Insects and small prey.", "terrestrial", "Theropod", "valid", 0.7, 0.25, 0.8, "Asia", "Mongolia", "Djadochta Formation", [44.0, 103.5], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Dromaeosauridae", "Mahakala", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Described by Turner et al. in 2007 from Tugrugyin Shireh.", ["Basal dromaeosaurid showing small body size prior to flight evolution.", "Slender limbs.", "Gobi desert endemic."], [{"citation": "Turner, A.H., et al. (2007). Science.", "url": "https://doi.org/10.1126/science.1144066"}])

# --- 12. NEMEGT FORMATION (MONGOLIA) ---
add("Deinocheirus mirificus", "Deinocheirus mirificus", "Horrible hand unusual", "Late Cretaceous", "Maastrichtian Epoch", 70.0, 66.0, "omnivore", "Freshwater fish, aquatic plants, and soft vegetation.", "semi_aquatic", "Theropod", "valid", 11.0, 4.4, 6400, "Asia", "Mongolia", "Nemegt Formation", [43.5, 101.0], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Deinocheiridae", "Deinocheirus", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "First 2.4m arms discovered in 1965; complete skeletons described in 2014 by Lee et al.", ["Enormous 2.4m arms with giant claws.", "Duck-billed head and sail-like hump on back.", "Giant omnivorous ornithomimosaur."], [{"citation": "Lee, Y.N., et al. (2014). Nature.", "url": "https://doi.org/10.1038/nature13874"}])
add("Saurolophus angustirostris", "Saurolophus angustirostris", "Lizard crest with narrow beak", "Late Cretaceous", "Maastrichtian Epoch", 70.0, 68.0, "herbivore", "River basin vegetation and horsetails.", "terrestrial", "Ornithischian", "valid", 12.0, 4.0, 5000, "Asia", "Mongolia", "Nemegt Formation", [43.5, 101.0], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Ornithischia", "Hadrosauridae", "Saurolophus", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Named by Anatoly Rozhdestvensky in 1952 from Nemegt Basin.", ["Solid spike-like backward crest.", "Large duckbill hadrosaurid.", "Mass bonebeds in Mongolia."], [{"citation": "Rozhdestvensky, A.K. (1952). Dokl. Akad. Nauk SSSR.", "url": "https://commons.wikimedia.org"}])
add("Nemegtosaurus mongoliensis", "Nemegtosaurus mongoliensis", "Nemegt lizard", "Late Cretaceous", "Maastrichtian Epoch", 70.0, 66.0, "herbivore", "High-canopy riverine trees.", "terrestrial", "Sauropod", "valid", 12.0, 3.5, 13000, "Asia", "Mongolia", "Nemegt Formation", [43.5, 101.0], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Nemegtosauridae", "Nemegtosaurus", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Described by Aleksander Nowinski in 1971 based on complete skull.", ["Slender peg-like teeth.", "Diplodocid-shaped head on a titanosaur.", "Found in Nemegt river valleys."], [{"citation": "Nowinski, A. (1971). Palaeontol. Pol.", "url": "https://commons.wikimedia.org"}])

# --- 13. LUFENG FORMATION (CHINA) ---
add("Bienosaurus lufengensis", "Bienosaurus lufengensis", "Mei Nien Bien lizard of Lufeng", "Early Jurassic", "Sinemurian Epoch", 199.0, 190.0, "herbivore", "Low gymnosperms and ferns.", "terrestrial", "Ornithischian", "valid", 2.5, 0.8, 50, "Asia", "China", "Lufeng Formation", [25.1, 102.1], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Ornithischia", "Scelidosauridae", "Bienosaurus", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Described by Dong Zhiming in 2001.", ["Basal armored thyreophoran.", "Rows of bony osteoderms on back.", "Early Jurassic Asian armored dinosaur."], [{"citation": "Dong, Z. (2001). Vertebr. PalAsiat.", "url": "https://commons.wikimedia.org"}])
add("Yunnanosaurus huangi", "Yunnanosaurus huangi", "Yunnan lizard named for T.K. Huang", "Early Jurassic", "Sinemurian Epoch", 199.0, 190.0, "herbivore", "High foliage.", "terrestrial", "Sauropodomorph", "valid", 7.0, 2.2, 1500, "Asia", "China", "Lufeng Formation", [25.1, 102.1], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Yunnanosauridae", "Yunnanosaurus", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Named by C.C. Young in 1942.", ["Chisel-like self-sharpening teeth.", "Advanced prosauropod.", "Over 20 complete skeletons recovered."], [{"citation": "Young, C.C. (1942). Bull. Geol. Soc. China.", "url": "https://doi.org/10.1111/j.1755-6724.1942.mp22001004.x"}])
add("Jingshanosaurus myankouensis", "Jingshanosaurus myankouensis", "Jingshan lizard from Myankou", "Early Jurassic", "Hettangian Epoch", 200.0, 195.0, "herbivore", "Ferns and early conifers.", "terrestrial", "Sauropodomorph", "valid", 10.0, 3.0, 3000, "Asia", "China", "Lufeng Formation", [25.1, 102.1], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Plateosauridae", "Jingshanosaurus", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Described by Zhang and Yang in 1995.", ["One of the last large prosauropods.", "Complete skeleton with skull exhibited in Kunming.", "Quadrupedal browser."], [{"citation": "Zhang, Y. & Yang, Z. (1995). Yunnan Sci. Tech. Press.", "url": "https://commons.wikimedia.org"}])
add("Lukousaurus yini", "Lukousaurus yini", "Lugou bridge lizard", "Early Jurassic", "Sinemurian Epoch", 199.0, 190.0, "carnivore", "Small tetrapods.", "terrestrial", "Theropod", "valid", 2.0, 0.7, 30, "Asia", "China", "Lufeng Formation", [25.1, 102.1], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Basal Theropoda", "Lukousaurus", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Named by C.C. Young in 1948.", ["Small predatory archosaur with horn-like nasal crests.", "Basal theropod or crocodylomorph.", "Lufeng predator."], [{"citation": "Young, C.C. (1948). Bull. Geol. Soc. China.", "url": "https://commons.wikimedia.org"}])
add("Eshanosaurus deguchiianus", "Eshanosaurus deguchiianus", "Eshan lizard named for Deguchi", "Early Jurassic", "Hettangian Epoch", 197.0, 190.0, "herbivore", "Foliage.", "terrestrial", "Theropod", "valid", 2.0, 0.8, 40, "Asia", "China", "Lufeng Formation", [25.1, 102.1], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Therizinosauria", "Eshanosaurus", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Described by Xu Xing et al. in 2001.", ["Oldest putative therizinosaurid known.", "Left dentary jaw bone with specialized herbivorous teeth.", "Extends coelurosaur lineage into Early Jurassic."], [{"citation": "Xu, X., et al. (2001). Proc. R. Soc. Lond. B.", "url": "https://doi.org/10.1098/rspb.2001.1615"}])
add("Sinosaurus triassicus", "Sinosaurus triassicus", "Chinese lizard", "Early Jurassic", "Sinemurian Epoch", 196.0, 189.0, "carnivore", "Lufengosaurus and large herbivores.", "terrestrial", "Theropod", "valid", 5.6, 1.8, 500, "Asia", "China", "Lufeng Formation", [25.1, 102.1], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Dilophosauridae", "Sinosaurus", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Named by C.C. Young in 1940.", ["Apex predator of Early Jurassic China.", "Pair of double crests on top of head like Dilophosaurus.", "Deep strong jaws."], [{"citation": "Young, C.C. (1940). Bull. Geol. Soc. China.", "url": "https://commons.wikimedia.org"}])

# --- 14. LAMETA FORMATION (INDIA) ---
add("Titanosaurus indicus", "Titanosaurus indicus", "Titanic lizard from India", "Late Cretaceous", "Maastrichtian Epoch", 70.0, 66.0, "herbivore", "Canopy gymnosperms and early flowering plants.", "terrestrial", "Sauropod", "valid", 18.0, 4.5, 13000, "Asia", "India", "Lameta Formation", [22.0, 79.0], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Titanosauridae", "Titanosaurus", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "First discovered near Jabalpur in 1877 by Richard Lydekker.", ["Eponymous genus for Titanosauria.", "Discovered in Lameta Ghat beds.", "Heavy armor armor osteoderms."], [{"citation": "Lydekker, R. (1877). Rec. Geol. Surv. India.", "url": "https://archive.org/details/palaeontologiaindiana"}])
add("Laevisuchus indicus", "Laevisuchus indicus", "Light crocodile from India", "Late Cretaceous", "Maastrichtian Epoch", 70.0, 66.0, "carnivore", "Small vertebrates and mammals.", "terrestrial", "Theropod", "valid", 2.0, 0.6, 15, "Asia", "India", "Lameta Formation", [22.0, 79.0], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Noasauridae", "Laevisuchus", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Described by Charles Matley and Friedrich von Huene in 1933 from Bara Simla, Jabalpur.", ["Small slender noasaurid abelisauroid.", "Lightly built hollow vertebrae.", "Agile predator."], [{"citation": "Huene, F. von & Matley, C.A. (1933). Mem. Geol. Surv. India.", "url": "https://archive.org/details/palaeontologiaindiana"}])

# --- 15. KOTA FORMATION (INDIA) ---
add("Indochelys spatulata", "Indochelys spatulata", "Indian turtle with spatulate shell", "Early Jurassic", "Toarcian Epoch", 183.0, 175.0, "freshwater", "Aquatic vegetation and mollusks.", "freshwater", "Marine_Reptile", "valid", 0.5, 0.15, 5, "Asia", "India", "Kota Formation", [18.8, 79.8], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Testudines", "Indochelyidae", "Indochelys", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Described by Datta et al. in 2000 from Kota limestone beds, Telangana.", ["Early aquatic turtle.", "Thick spatulate shell.", "Endemic to Early Jurassic India."], [{"citation": "Datta, P.M., et al. (2000). J. Vertebr. Paleontol.", "url": "https://doi.org/10.1671/0272-4634(2000)020[0404:ANTFTT]2.0.CO;2"}])
add("Dandakosaurus indicus", "Dandakosaurus indicus", "Dandakaranya forest lizard", "Early Jurassic", "Toarcian Epoch", 183.0, 175.0, "carnivore", "Preyed on Kotasaurus and early sauropods.", "terrestrial", "Theropod", "valid", 8.0, 2.5, 1200, "Asia", "India", "Kota Formation", [18.8, 79.8], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Ceratosauria", "Dandakosaurus", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Described by Yadagiri in 1982 from Pranhita-Godavari Valley.", ["Apex theropod predator of Kota Formation.", "Large ceratosaurian relative.", "Named after historic Dandakaranya forest."], [{"citation": "Yadagiri, P. (1982). J. Geol. Soc. India.", "url": "https://www.geosocindia.org"}])
add("Campylognathoides indicus", "Campylognathoides indicus", "Curved jaw from India", "Early Jurassic", "Toarcian Epoch", 183.0, 175.0, "piscivore", "Freshwater fish.", "aerial", "Pterosaur", "valid", 1.5, 0.4, 2, "Asia", "India", "Kota Formation", [18.8, 79.8], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Pterosauria", "Campylognathoididae", "Campylognathoides", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Discovered by Indian Statistical Institute scientists in Kota limestone.", ["Early Jurassic pterosaur with robust jaws.", "Short stout skull.", "Fossilized in freshwater lake limestone."], [{"citation": "Jain, S.L. (1974). J. Geol. Soc. India.", "url": "https://www.geosocindia.org"}])
add("Treposuchus indicus", "Treposuchus indicus", "Hole crocodile from India", "Early Jurassic", "Toarcian Epoch", 183.0, 175.0, "carnivore", "Fish and small shore tetrapods.", "freshwater", "Crocodylomorph", "valid", 2.0, 0.4, 30, "Asia", "India", "Kota Formation", [18.8, 79.8], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Crocodylomorpha", "Teleosauridae", "Treposuchus", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Described by Yadagiri in 1988.", ["Early teleosaurid aquatic crocodile.", "Elongated snout filled with needle teeth.", "Freshwater lagoon inhabitant."], [{"citation": "Yadagiri, P. (1988). Rec. Geol. Surv. India.", "url": "https://archive.org/details/palaeontologiaindiana"}])

# --- 16. SIWALIK HILLS (INDIA) ---
add("Sivapithecus sivalensis", "Sivapithecus sivalensis", "Shiva ape from Siwalik", "Neogene", "Miocene Epoch", 12.5, 8.5, "herbivore", "Hard fruits, nuts, and seeds.", "terrestrial", "Early_Mammal_Synapsid", "valid", 1.5, 1.2, 50, "Asia", "India", "Siwalik Hills", [30.8, 77.0], "Eukaryota", "Animalia", "Chordata", "Mammalia", "Primates", "Hominidae", "Sivapithecus", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "First discovered by Falconer and Cautley in 1836 in Siwalik Hills, India.", ["Direct ancestor of modern orangutans (Pongo).", "Concave facial profile and tall oval eye sockets.", "Thick tooth enamel for crushing tough seeds."], [{"citation": "Falconer, H. & Cautley, P.T. (1836). Asiatic Res.", "url": "https://commons.wikimedia.org"}])
add("Gigantopithecus bilaspurensis", "Gigantopithecus bilaspurensis", "Giant ape from Bilaspur", "Neogene", "Late Miocene Epoch", 9.0, 6.0, "herbivore", "Bamboo shoots, seeds, and fibrous plants.", "terrestrial", "Early_Mammal_Synapsid", "valid", 3.0, 2.5, 300, "Asia", "India", "Siwalik Hills", [30.8, 77.0], "Eukaryota", "Animalia", "Chordata", "Mammalia", "Primates", "Hominidae", "Gigantopithecus", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Discovered in 1968 near Bilaspur, Himachal Pradesh, India.", ["Largest primate to ever live.", "Massive lower jaw with huge grinding molars.", "Forest floor browser."], [{"citation": "Simons, E.L. & Chopra, S.R.K. (1969). Postilla.", "url": "https://hdl.handle.net/10079/fa/ypm.postilla.0138"}])
add("Bramatherium megacephalum", "Bramatherium megacephalum", "Brahma beast with large head", "Neogene", "Late Miocene Epoch", 8.5, 5.0, "herbivore", "Tree leaves and shrubs.", "terrestrial", "Early_Mammal_Synapsid", "valid", 3.0, 2.2, 450, "Asia", "India", "Siwalik Hills", [30.8, 77.0], "Eukaryota", "Animalia", "Chordata", "Mammalia", "Artiodactyla", "Giraffidae", "Bramatherium", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Described by Hugh Falconer in 1845 from Siwalik strata.", ["Massive extinct giraffid.", "Five crown ossicones forming a helmet crest.", "Stocky neck and body frame."], [{"citation": "Falconer, H. (1845). Q. J. Geol. Soc. Lond.", "url": "https://doi.org/10.1144/GSL.JGS.1845.001.01-02.66"}])
add("Hexaprotodon sivalensis", "Hexaprotodon sivalensis", "Six front teeth hippo from Siwalik", "Neogene", "Pliocene Epoch", 5.0, 2.0, "herbivore", "Riverine grass and aquatic vegetation.", "freshwater", "Early_Mammal_Synapsid", "valid", 3.2, 1.4, 1500, "Asia", "India", "Siwalik Hills", [30.8, 77.0], "Eukaryota", "Animalia", "Chordata", "Mammalia", "Artiodactyla", "Hippopotamidae", "Hexaprotodon", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Described by Falconer and Cautley in 1836.", ["Primitive hippopotamus with 6 incisors instead of 4.", "Semiaquatic river basin dweller.", "Widespread across Neogene India."], [{"citation": "Falconer, H. & Cautley, P.T. (1836). Asiat. Res.", "url": "https://commons.wikimedia.org"}])
add("Archidiskodon planifrons", "Archidiskodon planifrons", "Ancient disk tooth with flat forehead", "Pleistocene", "Early Pleistocene Epoch", 2.5, 1.0, "herbivore", "Grasses and leaves.", "terrestrial", "Early_Mammal_Synapsid", "valid", 4.0, 3.2, 5000, "Asia", "India", "Siwalik Hills", [30.8, 77.0], "Eukaryota", "Animalia", "Chordata", "Mammalia", "Proboscidea", "Elephantidae", "Archidiskodon", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Described by Falconer and Cautley in 1845.", ["Early mammoth ancestor.", "Curved tusks up to 3 meters.", "Transition to grassland grazing."], [{"citation": "Falconer, H. & Cautley, P.T. (1845). Fauna Antiqua Sivalensis.", "url": "https://archive.org/details/faunaantiquasiva00falcrich"}])

# --- 17. BAHARIYA FORMATION (EGYPT) ---
add("Bahariasaurus ingens", "Bahariasaurus ingens", "Bahariya lizard giant", "Late Cretaceous", "Cenomanian Epoch", 98.0, 93.0, "carnivore", "Apex predator hunting sauropods and fish.", "terrestrial", "Theropod", "valid", 12.0, 3.5, 4000, "Africa", "Egypt", "Bahariya Formation", [28.3, 28.9], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Bahariasauridae", "Bahariasaurus", "https://images.unsplash.com/photo-1551085254-e96b210df58a?q=80&w=1200&auto=format&fit=crop", "Discovered by Ernst Stromer in 1912; original fossils destroyed in WWII bombing of Munich in 1944.", ["Rivaled Spinosaurus and Carcharodontosaurus in length.", "Large slender theropod.", "Tragically lost holotype specimen."], [{"citation": "Stromer, E. (1934). Abh. Bayer. Akad. Wiss. Math. Nat. Abt.", "url": "https://commons.wikimedia.org"}])
add("Aegyptosaurus baharijensis", "Aegyptosaurus baharijensis", "Egypt lizard from Bahariya", "Late Cretaceous", "Cenomanian Epoch", 98.0, 93.0, "herbivore", "Mangrove foliage and conifers.", "terrestrial", "Sauropod", "valid", 15.0, 4.0, 10000, "Africa", "Egypt", "Bahariya Formation", [28.3, 28.9], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Titanosauridae", "Aegyptosaurus", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Named by Ernst Stromer in 1932.", ["Primitive African titanosaur.", "Found in coastal mangrove swamp deposits.", "Fossils also destroyed in Munich 1944 bombing."], [{"citation": "Stromer, E. (1932). Abh. Bayer. Akad. Wiss.", "url": "https://commons.wikimedia.org"}])
add("Stromerichthys lacustris", "Stromerichthys lacustris", "Stromer's fish from lake", "Late Cretaceous", "Cenomanian Epoch", 98.0, 93.0, "carnivore", "Small aquatic organisms.", "freshwater", "Invertebrate", "valid", 1.5, 0.4, 20, "Africa", "Egypt", "Bahariya Formation", [28.3, 28.9], "Eukaryota", "Animalia", "Chordata", "Actinopterygii", "Polypteriformes", "Polypteridae", "Stromerichthys", "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop", "Named by Weiler in 1935 in honor of Ernst Stromer.", ["Giant bichir ray-finned fish.", "Heavy ganoid scales.", "Inhabited Bahariya freshwater estuaries."], [{"citation": "Weiler, W. (1935). Abh. Bayer. Akad. Wiss.", "url": "https://commons.wikimedia.org"}])
add("Rugops primus", "Rugops primus", "Wrinkled face first", "Late Cretaceous", "Cenomanian Epoch", 95.0, 92.0, "carnivore", "Scavenged carcasses and hunted small prey.", "terrestrial", "Theropod", "valid", 6.0, 2.0, 750, "Africa", "Egypt", "Bahariya Formation", [28.3, 28.9], "Eukaryota", "Animalia", "Chordata", "Reptilia", "Saurischia", "Abelisauridae", "Rugops", "https://images.unsplash.com/photo-1569317002804-ab77bcf1bce4?q=80&w=1200&auto=format&fit=crop", "Discovered by Paul Sereno in 2000 in North Africa.", ["Skull covered in blood vessel grooves and keratin armor.", "Row of small holes along nasal bones for display crests.", "Early abelisaurid."], [{"citation": "Sereno, P.C., et al. (2004). Proc. R. Soc. Lond. B.", "url": "https://doi.org/10.1098/rspb.2004.2689"}])
add("Mawsonia libyca", "Mawsonia libyca", "Named for Mawson", "Late Cretaceous", "Cenomanian Epoch", 98.0, 93.0, "piscivore", "Filter feeding and small marine organisms.", "freshwater", "Invertebrate", "valid", 4.0, 1.2, 500, "Africa", "Egypt", "Bahariya Formation", [28.3, 28.9], "Eukaryota", "Animalia", "Chordata", "Sarcopterygii", "Coelacanthiformes", "Mawsoniidae", "Mawsonia", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "Described by Mawson and Woodward; abundant in Bahariya coastal strata.", ["Colossal 4-meter lobe-finned coelacanth.", "Largest coelacanth to ever exist.", "Thick bony skull plates."], [{"citation": "Woodward, A.S. (1907). Q. J. Geol. Soc. Lond.", "url": "https://commons.wikimedia.org"}])

# Save output JSON
with open('d:/My folders/AI 1.0/Prehistoric encylcopedia/backend/all_new_species.json', 'w', encoding='utf-8') as f:
    json.dump(species_data, f, indent=2)

print(f"Successfully generated {len(species_data)} species into all_new_species.json")
