import { PrismaClient } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const prisma = new PrismaClient();

interface MediaItem {
  url: string;
  type: 'art' | 'photo' | 'scale_diagram' | 'taxonomy_diagram' | 'fossil_specimen' | 'skeletal_reconstruction' | 'comparative_anatomy' | 'scientific_figure';
  credit: string;
  sourceUrl: string;
}

const AI_KEYWORDS = [
  'midjourney', 'stable diffusion', 'dall-e', 'dalle', 'ai generated',
  'ai art', 'generated by ai', 'ai-generated', 'bing image creator',
  'novelai', 'firefly', 'deepmind', 'artbreeder'
];

const NON_SINGLE_SUBJECT = [
  'skeletal', 'skeleton', 'fossil', 'skull', 'mount', 'map', 'diagram',
  'cladogram', 'phylogeny', 'size_comparison', 'holotype', 'paratype',
  'specimen', 'quarry', 'matrix', 'teeth', 'tooth', 'vertebra', 'bone',
  'plate', 'figure', 'collage', 'panel', 'chart', 'vs', 'versus',
  'ecosystem', 'biota', 'fauna', 'scene', 'multi', 'comparison'
];

async function isUrlLive(url: string): Promise<boolean> {
  if (!url || !url.startsWith('http')) return false;
  try {
    const res = await fetch(url, {
      method: 'HEAD',
      headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) PrehistoricaBot/2.0' }
    });
    if (res.status >= 200 && res.status < 400) return true;
    const getRes = await fetch(url, {
      method: 'GET',
      headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) PrehistoricaBot/2.0', 'Range': 'bytes=0-200' }
    });
    return getRes.status >= 200 && getRes.status < 400;
  } catch {
    return false;
  }
}

async function findSingleSubjectPaleoart(genus: string, scientificName: string): Promise<MediaItem | null> {
  const queries = [
    `${genus} BW.jpg`,
    `${genus} 1DB.jpg`,
    `${genus} DB.jpg`,
    `${scientificName} life restoration`,
    `${genus} life restoration`,
    `${scientificName} reconstruction`,
    `${genus} reconstruction`,
    `${genus}`
  ];

  for (const q of queries) {
    const apiUrl = `https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(q)}&gsrnamespace=6&gsrlimit=15&prop=imageinfo&iiprop=url|mime|extmetadata|user|size&format=json`;

    try {
      const res = await fetch(apiUrl, {
        headers: { 'User-Agent': 'PrehistoricaBot/2.0 (Single Subject Paleoart Audit)' }
      });
      const json: any = await res.json();
      if (!json.query || !json.query.pages) continue;

      const pages = Object.values(json.query.pages) as any[];

      for (const p of pages) {
        if (!p.imageinfo || !p.imageinfo[0]) continue;
        const info = p.imageinfo[0];
        const mime = info.mime || '';
        if (!mime.startsWith('image/')) continue;

        const title = p.title || '';
        const rawUrl = info.url || '';
        const cleanUrl = rawUrl.split('?')[0];

        const ext = info.extmetadata || {};
        const description = String(ext.ImageDescription?.value || '').toLowerCase();
        const categories = String(ext.Categories?.value || '').toLowerCase();
        const rawArtist = ext.Artist?.value || info.user || 'Wikimedia Commons Contributor';
        const artistClean = String(rawArtist).replace(/<[^>]*>?/gm, '').trim();
        const rawLicense = ext.LicenseShortName?.value || ext.UsageTerms?.value || 'CC BY-SA';
        const licenseClean = String(rawLicense).replace(/<[^>]*>?/gm, '').trim();

        const lowerTitle = title.toLowerCase();
        const lowerDesc = description.toLowerCase();
        const lowerCats = categories.toLowerCase();
        const lowerArtist = artistClean.toLowerCase();

        // 1. REJECT AI ART
        if (AI_KEYWORDS.some(k => lowerTitle.includes(k) || lowerDesc.includes(k) || lowerCats.includes(k) || lowerArtist.includes(k))) {
          continue;
        }

        // 2. REJECT NON-SINGLE-SUBJECT (SKELETALS, FOSSIL PLATES, CLADOGRAMS, MULTI-SPECIES COLLAGES)
        if (NON_SINGLE_SUBJECT.some(k => lowerTitle.includes(k) || lowerCats.includes(k) || lowerDesc.includes(k))) {
          // Exception: if it's explicitly Nobu Tamura's or Dmitry Bogdanov's single-subject DB/BW file like "Tyrannosaurus_BW.jpg"
          const isSingleSubjectArtistFile = (lowerTitle.endsWith('_bw.jpg') || lowerTitle.endsWith('_1db.jpg') || lowerTitle.endsWith('_db.jpg')) && lowerTitle.includes(genus.toLowerCase());
          if (!isSingleSubjectArtistFile) continue;
        }

        // 3. VERIFY LIVE URL
        const live = await isUrlLive(cleanUrl);
        if (!live) continue;

        const sourcePage = `https://commons.wikimedia.org/wiki/${encodeURIComponent(title.replace(/ /g, '_'))}`;
        const credit = `${artistClean || 'Wikimedia Contributor'} (${licenseClean || 'CC BY-SA'})`;

        return {
          url: cleanUrl,
          type: 'art',
          credit,
          sourceUrl: sourcePage
        };
      }
    } catch {
      // Continue next query
    }
  }

  return null;
}

async function auditAndEnforceSingleSubject() {
  console.log('Starting Single-Subject Paleoart Enforcement Audit across all 502 species...');

  const allSpecies = await prisma.species.findMany({
    orderBy: { id: 'asc' },
    select: { id: true, name: true, scientificName: true, media: true }
  });

  console.log(`Loaded ${allSpecies.length} species from Supabase DB.`);

  let singleSubjectCount = 0;
  let reclassifiedCount = 0;

  for (let i = 0; i < allSpecies.length; i++) {
    const s = allSpecies[i];
    let mediaArr: MediaItem[] = [];
    try {
      mediaArr = typeof s.media === 'string' ? JSON.parse(s.media) : (s.media || []);
    } catch (e) {}

    const primaryItem = mediaArr.find(m => m.type === 'art') || mediaArr[0];
    let needsReclassification = false;
    let newType: MediaItem['type'] = 'art';

    if (primaryItem) {
      const urlLower = (primaryItem.url || '').toLowerCase();
      const creditLower = (primaryItem.credit || '').toLowerCase();
      const sourceLower = (primaryItem.sourceUrl || '').toLowerCase();

      if (urlLower.includes('cladogram') || sourceLower.includes('cladogram') || creditLower.includes('cladogram')) {
        needsReclassification = true;
        newType = 'taxonomy_diagram';
      } else if (urlLower.includes('skeletal') || sourceLower.includes('skeletal') || creditLower.includes('skeletal')) {
        needsReclassification = true;
        newType = 'skeletal_reconstruction';
      } else if (urlLower.includes('fossil') || sourceLower.includes('fossil') || creditLower.includes('fossil') || urlLower.includes('skull')) {
        needsReclassification = true;
        newType = 'fossil_specimen';
      } else if (urlLower.includes('comparison') || urlLower.includes('anatomy')) {
        needsReclassification = true;
        newType = 'comparative_anatomy';
      } else if (urlLower.includes('figure') || urlLower.includes('diagram')) {
        needsReclassification = true;
        newType = 'scientific_figure';
      }
    }

    if (needsReclassification && primaryItem) {
      console.log(`\n[${i + 1}/${allSpecies.length}] Reclassifying primary item for #${s.id} ${s.name} to '${newType}'`);
      
      const genus = s.name.split(' ')[0];
      const singleArt = await findSingleSubjectPaleoart(genus, s.scientificName || s.name);

      // Reclassify existing primary item to appropriate secondary type
      const secondaryItem: MediaItem = {
        ...primaryItem,
        type: newType
      };

      let updatedMedia: MediaItem[] = [];

      if (singleArt) {
        updatedMedia = [singleArt, secondaryItem];
        console.log(`  ✓ Assigned single-subject life restoration: ${singleArt.url}`);
      } else {
        // Keep secondary item and retain existing fallback
        updatedMedia = [secondaryItem];
      }

      // Preserve any other existing secondary media items
      mediaArr.forEach(m => {
        if (m !== primaryItem) updatedMedia.push(m);
      });

      await prisma.species.update({
        where: { id: s.id },
        data: { media: JSON.stringify(updatedMedia) }
      });

      reclassifiedCount++;
    } else {
      singleSubjectCount++;
    }

    if ((i + 1) % 100 === 0) {
      console.log(`Progress: [${i + 1}/${allSpecies.length}] evaluated...`);
    }
  }

  console.log('\n==========================================');
  console.log('SINGLE-SUBJECT AUDIT COMPLETE');
  console.log(`Total species evaluated: ${allSpecies.length}`);
  console.log(`Valid Single-Subject Primary Art: ${singleSubjectCount}`);
  console.log(`Reclassified / Replaced: ${reclassifiedCount}`);
  console.log('==========================================');

  // Export full updated database to JSON files
  const exportPath = path.join(__dirname, '..', 'prisma', 'species_full_export.json');
  const dbSpecies = await prisma.species.findMany({ orderBy: { id: 'asc' } });
  fs.writeFileSync(exportPath, JSON.stringify(dbSpecies, null, 2), 'utf8');

  const triassic = dbSpecies.filter(s => s.timePeriod?.toLowerCase().includes('triassic'));
  const jurassic = dbSpecies.filter(s => s.timePeriod?.toLowerCase().includes('jurassic'));
  const cretaceous = dbSpecies.filter(s => s.timePeriod?.toLowerCase().includes('cretaceous'));
  const others = dbSpecies.filter(s =>
    !s.timePeriod?.toLowerCase().includes('triassic') &&
    !s.timePeriod?.toLowerCase().includes('jurassic') &&
    !s.timePeriod?.toLowerCase().includes('cretaceous')
  );

  fs.writeFileSync(path.join(__dirname, '..', 'prisma', 'species_triassic.json'), JSON.stringify(triassic, null, 2), 'utf8');
  fs.writeFileSync(path.join(__dirname, '..', 'prisma', 'species_jurassic.json'), JSON.stringify(jurassic, null, 2), 'utf8');
  fs.writeFileSync(path.join(__dirname, '..', 'prisma', 'species_cretaceous.json'), JSON.stringify(cretaceous, null, 2), 'utf8');
  fs.writeFileSync(path.join(__dirname, '..', 'prisma', 'species_others.json'), JSON.stringify(others, null, 2), 'utf8');

  console.log('✓ Synced updated database records to local JSON files.');
}

auditAndEnforceSingleSubject()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
