import { PrismaClient } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const prisma = new PrismaClient();

interface MediaItem {
  url: string;
  type: 'art' | 'photo' | 'scale_diagram';
  credit: string;
  sourceUrl: string;
}

// Well-known reputable paleoartists on Wikimedia Commons
const KNOWN_PALEOARTISTS = [
  'nobu tamura', 'dmitry bogdanov', 'emily willoughby', 'gabriel lio',
  'fred wierum', 'julio lacerda', 'gabriel ugueto', 'steveoc86',
  'charles r. knight', 'heinrich harder', 'zdenek burian', 'joseph smit',
  'marta zaher', 'alain beneteau', 't. michael keesey', 'scott hartman',
  'mathew wedel', 'mark witton', 'paleo-neolitic', 'dbcls', 'geological society'
];

async function fetchPaleoartFromWikimedia(speciesName: string, scientificName: string): Promise<MediaItem | null> {
  const genus = speciesName.split(' ')[0];
  const searchQueries = [
    `${speciesName} life restoration`,
    `${genus} life restoration`,
    `${scientificName} reconstruction`,
    `${genus} reconstruction`,
    `${speciesName}`,
    `${genus}`
  ];

  for (const q of searchQueries) {
    const url = `https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(q)}&gsrnamespace=6&gsrlimit=12&prop=imageinfo&iiprop=url|mime|extmetadata|user|size&format=json`;

    try {
      const res = await fetch(url, {
        headers: { 'User-Agent': 'PrehistoricaEncyclopedia/2.0 (Educational Paleontology Museum App)' }
      });
      const json: any = await res.json();

      if (!json.query || !json.query.pages) continue;

      const pages = Object.values(json.query.pages) as any[];

      for (const p of pages) {
        if (!p.imageinfo || !p.imageinfo[0]) continue;
        const info = p.imageinfo[0];
        const mime = info.mime || '';
        if (!mime.startsWith('image/')) continue;

        const title = p.title || '';
        const rawUrl = info.url || '';
        // Strip tracking params for clean image URL
        const cleanUrl = rawUrl.split('?')[0];

        const ext = info.extmetadata || {};
        const description = String(ext.ImageDescription?.value || '').toLowerCase();
        const categories = String(ext.Categories?.value || '').toLowerCase();
        const rawArtist = ext.Artist?.value || info.user || 'Wikimedia Commons Contributor';
        const artistClean = String(rawArtist).replace(/<[^>]*>?/gm, '').trim();
        const rawLicense = ext.LicenseShortName?.value || ext.UsageTerms?.value || 'CC BY-SA';
        const licenseClean = String(rawLicense).replace(/<[^>]*>?/gm, '').trim();

        const lowerTitle = title.toLowerCase();
        const lowerDesc = description.toLowerCase();
        const lowerCats = categories.toLowerCase();
        const lowerArtist = artistClean.toLowerCase();

        // 1. STRICT FILTER: NO AI GENERATED ART
        const aiKeywords = [
          'midjourney', 'stable diffusion', 'dall-e', 'dalle', 'ai generated',
          'ai art', 'generated by ai', 'ai-generated', 'bing image creator',
          'novelai', 'firefly', 'deepmind', 'artbreeder'
        ];
        const isAI = aiKeywords.some(k =>
          lowerTitle.includes(k) || lowerDesc.includes(k) || lowerCats.includes(k) || lowerArtist.includes(k)
        );
        if (isAI) {
          console.log(`  [Skipping AI Art] ${title}`);
          continue;
        }

        // 2. STRICT FILTER: EXCLUDE FOSSIL PHOTOS, SKELETONS, SKULLS, MAPS, CLADOGRAMS
        const excludeKeywords = [
          'skeletal', 'skeleton', 'fossil', 'skull', 'mount', 'map', 'diagram',
          'cladogram', 'phylogeny', 'size_comparison', 'holotype', 'paratype',
          'specimen', 'quarry', 'matrix', 'teeth', 'tooth', 'vertebra', 'bone'
        ];
        const isExcludedType = excludeKeywords.some(k => lowerTitle.includes(k) || lowerCats.includes(k));
        if (isExcludedType) continue;

        // 3. CONFIRMATION: Check if it's life restoration / reconstruction or by known paleoartist
        const isRestoration = [
          'life restoration', 'reconstruction', 'restoration', 'paleoart', 'life_restoration',
          'model', 'painting', 'drawing', 'illustration', 'art'
        ].some(k => lowerTitle.includes(k) || lowerDesc.includes(k) || lowerCats.includes(k));

        const isKnownArtist = KNOWN_PALEOARTISTS.some(a => lowerArtist.includes(a));

        if (!isRestoration && !isKnownArtist && !lowerTitle.includes(genus.toLowerCase())) {
          continue;
        }

        const commonsFilePage = `https://commons.wikimedia.org/wiki/${encodeURIComponent(title.replace(/ /g, '_'))}`;
        const creditString = `${artistClean || 'Wikimedia Contributor'} (${licenseClean || 'CC BY-SA'})`;

        return {
          url: cleanUrl,
          type: 'art',
          credit: creditString,
          sourceUrl: commonsFilePage
        };
      }
    } catch (err) {
      // Ignore network errors and continue next query
    }
  }

  return null;
}

async function runAuditAndFix() {
  console.log('Starting Paleoart Audit & Verification across 502 species...');

  const allSpecies = await prisma.species.findMany({
    select: {
      id: true,
      name: true,
      scientificName: true,
      media: true
    }
  });

  console.log(`Loaded ${allSpecies.length} species from Supabase Postgres.`);

  let updatedCount = 0;
  let skippedCount = 0;
  let failedCount = 0;

  for (let i = 0; i < allSpecies.length; i++) {
    const s = allSpecies[i];
    let mediaArr: MediaItem[] = [];
    try {
      mediaArr = typeof s.media === 'string' ? JSON.parse(s.media) : (s.media || []);
    } catch (e) {}

    const artItem = mediaArr.find(m => m.type === 'art');
    const photoItem = mediaArr.find(m => m.type === 'photo');

    // Determine if current media needs fixing:
    // - No art item
    // - Art URL is Unsplash stock photo
    // - Art URL is missing or broken
    let needsFix = false;
    if (!artItem) {
      needsFix = true;
    } else if (artItem.url.includes('unsplash')) {
      needsFix = true;
    } else if (!artItem.url.startsWith('http')) {
      needsFix = true;
    }

    if (!needsFix) {
      skippedCount++;
      continue;
    }

    console.log(`[${i + 1}/${allSpecies.length}] Needs Paleoart Fix: #${s.id} ${s.name} (${s.scientificName})`);

    const newArt = await fetchPaleoartFromWikimedia(s.name, s.scientificName);

    if (newArt) {
      // Maintain secondary fossil photo if present
      const updatedMedia: MediaItem[] = [newArt];
      if (photoItem) {
        updatedMedia.push(photoItem);
      }

      const mediaJson = JSON.stringify(updatedMedia);

      await prisma.species.update({
        where: { id: s.id },
        data: { media: mediaJson }
      });

      console.log(`  ✓ Updated DB for #${s.id} ${s.name}: ${newArt.url}`);
      console.log(`    Credit: ${newArt.credit}`);
      updatedCount++;
    } else {
      console.log(`  ⚠️ Could not find verified Paleoart for ${s.name}`);
      failedCount++;
    }

    // Small delay to be polite to Wikimedia API
    await new Promise(r => setTimeout(r, 150));
  }

  console.log('\n==========================================');
  console.log('PALEOART AUDIT & SYNC COMPLETE');
  console.log(`Total species evaluated: ${allSpecies.length}`);
  console.log(`Already Valid Paleoart: ${skippedCount}`);
  console.log(`Successfully Updated & Pushed: ${updatedCount}`);
  console.log(`Unresolved: ${failedCount}`);
  console.log('==========================================');
}

runAuditAndFix()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
