import { PrismaClient } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const prisma = new PrismaClient();

interface MediaItem {
  url: string;
  type: 'art' | 'photo' | 'scale_diagram';
  credit: string;
  sourceUrl: string;
}

const AI_KEYWORDS = [
  'midjourney', 'stable diffusion', 'dall-e', 'dalle', 'ai generated',
  'ai art', 'generated by ai', 'ai-generated', 'bing image creator',
  'novelai', 'firefly', 'deepmind', 'artbreeder'
];

const EXCLUDE_KEYWORDS = [
  'skeletal', 'skeleton', 'fossil', 'skull', 'mount', 'map', 'diagram',
  'cladogram', 'phylogeny', 'size_comparison', 'holotype', 'paratype',
  'specimen', 'quarry', 'matrix', 'teeth', 'tooth', 'vertebra', 'bone',
  'city', 'canal', 'building', 'street', 'park', 'car', 'landscape'
];

async function checkUrlLive(url: string): Promise<boolean> {
  if (!url || !url.startsWith('http')) return false;
  try {
    const res = await fetch(url, { method: 'HEAD', headers: { 'User-Agent': 'PrehistoricaBot/2.0' } });
    if (res.status >= 200 && res.status < 400) return true;
    // Fallback to GET with Range header if HEAD is blocked
    const getRes = await fetch(url, { method: 'GET', headers: { 'User-Agent': 'PrehistoricaBot/2.0', 'Range': 'bytes=0-100' } });
    return getRes.status >= 200 && getRes.status < 400;
  } catch {
    return false;
  }
}

async function findVerifiedWikimediaPaleoart(genus: string, fullSpeciesName: string): Promise<MediaItem | null> {
  const cleanGenus = genus.split(' ')[0];
  const queries = [
    `${fullSpeciesName} life restoration`,
    `${cleanGenus} life restoration`,
    `${fullSpeciesName} reconstruction`,
    `${cleanGenus} reconstruction`,
    `${fullSpeciesName}`,
    `${cleanGenus}`
  ];

  for (const q of queries) {
    const apiUrl = `https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(q)}&gsrnamespace=6&gsrlimit=15&prop=imageinfo&iiprop=url|mime|extmetadata|user|size&format=json`;

    try {
      const res = await fetch(apiUrl, {
        headers: { 'User-Agent': 'PrehistoricaEncyclopedia/2.0 (Museum Educational App)' }
      });
      const json: any = await res.json();
      if (!json.query || !json.query.pages) continue;

      const pages = Object.values(json.query.pages) as any[];

      for (const p of pages) {
        if (!p.imageinfo || !p.imageinfo[0]) continue;
        const info = p.imageinfo[0];
        const mime = info.mime || '';
        if (!mime.startsWith('image/')) continue;

        const title = p.title || '';
        const rawUrl = info.url || '';
        const cleanUrl = rawUrl.split('?')[0];

        const ext = info.extmetadata || {};
        const description = String(ext.ImageDescription?.value || '').toLowerCase();
        const categories = String(ext.Categories?.value || '').toLowerCase();
        const rawArtist = ext.Artist?.value || info.user || 'Wikimedia Commons Contributor';
        const artistClean = String(rawArtist).replace(/<[^>]*>?/gm, '').trim();
        const rawLicense = ext.LicenseShortName?.value || ext.UsageTerms?.value || 'CC BY-SA';
        const licenseClean = String(rawLicense).replace(/<[^>]*>?/gm, '').trim();

        const lowerTitle = title.toLowerCase();
        const lowerDesc = description.toLowerCase();
        const lowerCats = categories.toLowerCase();
        const lowerArtist = artistClean.toLowerCase();

        // 1. FILTER AI ART
        if (AI_KEYWORDS.some(k => lowerTitle.includes(k) || lowerDesc.includes(k) || lowerCats.includes(k) || lowerArtist.includes(k))) {
          continue;
        }

        // 2. FILTER FOSSILS / DIAGRAMS / IRRELEVANT CITY LANDSCAPES
        if (EXCLUDE_KEYWORDS.some(k => lowerTitle.includes(k) || lowerCats.includes(k))) {
          continue;
        }

        // 3. VERIFY URL IS LIVE
        const isLive = await checkUrlLive(cleanUrl);
        if (!isLive) continue;

        const sourcePage = `https://commons.wikimedia.org/wiki/${encodeURIComponent(title.replace(/ /g, '_'))}`;
        const credit = `${artistClean || 'Wikimedia Contributor'} (${licenseClean || 'CC BY-SA'})`;

        return {
          url: cleanUrl,
          type: 'art',
          credit,
          sourceUrl: sourcePage
        };
      }
    } catch {
      // Continue next query
    }
  }

  return null;
}

async function auditAndFixAll() {
  console.log('Starting Deep HTTP & Content Audit across all 502 species...');

  const allSpecies = await prisma.species.findMany({
    orderBy: { id: 'asc' },
    select: { id: true, name: true, scientificName: true, media: true }
  });

  console.log(`Loaded ${allSpecies.length} species from Supabase DB.`);

  let liveCount = 0;
  let fixedCount = 0;
  let failedCount = 0;

  for (let i = 0; i < allSpecies.length; i++) {
    const s = allSpecies[i];
    let mediaArr: MediaItem[] = [];
    try {
      mediaArr = typeof s.media === 'string' ? JSON.parse(s.media) : (s.media || []);
    } catch (e) {}

    const artItem = mediaArr.find(m => m.type === 'art') || mediaArr[0];
    let needsFix = false;
    let fixReason = '';

    if (!artItem || !artItem.url) {
      needsFix = true;
      fixReason = 'Missing image URL';
    } else {
      const urlLower = artItem.url.toLowerCase();
      const creditLower = (artItem.credit || '').toLowerCase();
      const sourceLower = (artItem.sourceUrl || '').toLowerCase();

      // Check if URL is broken (HEAD/GET check)
      const isLive = await checkUrlLive(artItem.url);
      if (!isLive) {
        needsFix = true;
        fixReason = 'Broken URL (HTTP 404 / error)';
      } else if (urlLower.includes('unsplash')) {
        needsFix = true;
        fixReason = 'Unsplash stock image';
      } else if (EXCLUDE_KEYWORDS.some(k => urlLower.includes(k) || sourceLower.includes(k))) {
        needsFix = true;
        fixReason = 'Irrelevant / Fossil photo misclassified as art';
      }
    }

    if (!needsFix) {
      liveCount++;
      if ((i + 1) % 50 === 0) {
        console.log(`Progress: [${i + 1}/${allSpecies.length}] Checked...`);
      }
      continue;
    }

    console.log(`[${i + 1}/${allSpecies.length}] FIXING #${s.id} ${s.name} (${s.scientificName}) -> Reason: ${fixReason}`);

    const genus = s.name.split(' ')[0];
    const newArt = await findVerifiedWikimediaPaleoart(genus, s.scientificName || s.name);

    if (newArt) {
      const photoItem = mediaArr.find(m => m.type === 'photo');
      const updatedMedia = [newArt];
      if (photoItem) updatedMedia.push(photoItem);

      await prisma.species.update({
        where: { id: s.id },
        data: { media: JSON.stringify(updatedMedia) }
      });

      console.log(`  ✓ Updated DB for #${s.id} ${s.name}: ${newArt.url}`);
      console.log(`    Credit: ${newArt.credit}`);
      fixedCount++;
    } else {
      console.log(`  ⚠️ Could not find replacement for #${s.id} ${s.name}`);
      failedCount++;
    }

    await new Promise(r => setTimeout(r, 100));
  }

  console.log('\n==========================================');
  console.log('DEEP MEDIA AUDIT & REPAIR COMPLETE');
  console.log(`Total species: ${allSpecies.length}`);
  console.log(`Live Verified Paleoart: ${liveCount}`);
  console.log(`Successfully Repaired & Pushed: ${fixedCount}`);
  console.log(`Unresolved: ${failedCount}`);
  console.log('==========================================');

  // Export full updated database to JSON files
  const exportPath = path.join(__dirname, '..', 'prisma', 'species_full_export.json');
  const dbSpecies = await prisma.species.findMany({ orderBy: { id: 'asc' } });
  fs.writeFileSync(exportPath, JSON.stringify(dbSpecies, null, 2), 'utf8');

  const triassic = dbSpecies.filter(s => s.timePeriod?.toLowerCase().includes('triassic'));
  const jurassic = dbSpecies.filter(s => s.timePeriod?.toLowerCase().includes('jurassic'));
  const cretaceous = dbSpecies.filter(s => s.timePeriod?.toLowerCase().includes('cretaceous'));
  const others = dbSpecies.filter(s =>
    !s.timePeriod?.toLowerCase().includes('triassic') &&
    !s.timePeriod?.toLowerCase().includes('jurassic') &&
    !s.timePeriod?.toLowerCase().includes('cretaceous')
  );

  fs.writeFileSync(path.join(__dirname, '..', 'prisma', 'species_triassic.json'), JSON.stringify(triassic, null, 2), 'utf8');
  fs.writeFileSync(path.join(__dirname, '..', 'prisma', 'species_jurassic.json'), JSON.stringify(jurassic, null, 2), 'utf8');
  fs.writeFileSync(path.join(__dirname, '..', 'prisma', 'species_cretaceous.json'), JSON.stringify(cretaceous, null, 2), 'utf8');
  fs.writeFileSync(path.join(__dirname, '..', 'prisma', 'species_others.json'), JSON.stringify(others, null, 2), 'utf8');

  console.log('✓ Synced updated database records to local JSON files.');
}

auditAndFixAll()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
