import { PrismaClient } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const prisma = new PrismaClient();

interface MediaItem {
  url: string;
  type: 'art' | 'photo' | 'scale_diagram';
  credit: string;
  sourceUrl: string;
}

const AI_KEYWORDS = [
  'midjourney', 'stable diffusion', 'dall-e', 'dalle', 'ai generated',
  'ai art', 'generated by ai', 'ai-generated', 'bing image creator',
  'novelai', 'firefly', 'deepmind', 'artbreeder'
];

const EXCLUDE_KEYWORDS = [
  'skeletal', 'skeleton', 'fossil', 'skull', 'mount', 'map', 'diagram',
  'cladogram', 'phylogeny', 'size_comparison', 'holotype', 'paratype',
  'specimen', 'quarry', 'matrix', 'teeth', 'tooth', 'vertebra', 'bone'
];

async function isUrlLive(url: string): Promise<boolean> {
  if (!url || !url.startsWith('http')) return false;
  try {
    const res = await fetch(url, {
      method: 'HEAD',
      headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) PrehistoricaBot/2.0' }
    });
    if (res.status >= 200 && res.status < 400) return true;
    const getRes = await fetch(url, {
      method: 'GET',
      headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) PrehistoricaBot/2.0', 'Range': 'bytes=0-200' }
    });
    return getRes.status >= 200 && getRes.status < 400;
  } catch {
    return false;
  }
}

async function findPaleoartBroad(name: string, sciName: string, clade: string): Promise<MediaItem | null> {
  const genus = name.split(' ')[0];
  const searchQueries = [
    genus,
    sciName,
    `${genus} dinosaur`,
    `${genus} restoration`,
    `${genus} reconstruction`,
    `${sciName} restoration`,
    `${clade} life restoration`
  ];

  for (const q of searchQueries) {
    // 1. Wikimedia API Search
    const apiUrl = `https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(q)}&gsrnamespace=6&gsrlimit=20&prop=imageinfo&iiprop=url|mime|extmetadata|user|size&format=json`;

    try {
      const res = await fetch(apiUrl, {
        headers: { 'User-Agent': 'PrehistoricaBot/2.0 (Educational Paleontology Museum)' }
      });
      const json: any = await res.json();
      if (!json.query || !json.query.pages) continue;

      const pages = Object.values(json.query.pages) as any[];

      for (const p of pages) {
        if (!p.imageinfo || !p.imageinfo[0]) continue;
        const info = p.imageinfo[0];
        const mime = info.mime || '';
        if (!mime.startsWith('image/')) continue;

        const title = p.title || '';
        const rawUrl = info.url || '';
        const cleanUrl = rawUrl.split('?')[0];

        const ext = info.extmetadata || {};
        const description = String(ext.ImageDescription?.value || '').toLowerCase();
        const categories = String(ext.Categories?.value || '').toLowerCase();
        const rawArtist = ext.Artist?.value || info.user || 'Wikimedia Commons Contributor';
        const artistClean = String(rawArtist).replace(/<[^>]*>?/gm, '').trim();
        const rawLicense = ext.LicenseShortName?.value || ext.UsageTerms?.value || 'CC BY-SA';
        const licenseClean = String(rawLicense).replace(/<[^>]*>?/gm, '').trim();

        const lowerTitle = title.toLowerCase();
        const lowerDesc = description.toLowerCase();
        const lowerCats = categories.toLowerCase();
        const lowerArtist = artistClean.toLowerCase();

        // FILTER AI ART
        if (AI_KEYWORDS.some(k => lowerTitle.includes(k) || lowerDesc.includes(k) || lowerCats.includes(k) || lowerArtist.includes(k))) {
          continue;
        }

        // FILTER FOSSIL SKELETONS
        if (EXCLUDE_KEYWORDS.some(k => lowerTitle.includes(k) || lowerCats.includes(k))) {
          continue;
        }

        // VERIFY LIVE URL
        const live = await isUrlLive(cleanUrl);
        if (!live) continue;

        const sourcePage = `https://commons.wikimedia.org/wiki/${encodeURIComponent(title.replace(/ /g, '_'))}`;
        const credit = `${artistClean || 'Wikimedia Contributor'} (${licenseClean || 'CC BY-SA'})`;

        return {
          url: cleanUrl,
          type: 'art',
          credit,
          sourceUrl: sourcePage
        };
      }
    } catch {
      // Continue next query
    }
  }

  return null;
}

async function resolveBatch() {
  console.log('Resolving missing/broken paleoart for all remaining batch species...');

  const allSpecies = await prisma.species.findMany({
    orderBy: { id: 'asc' },
    select: { id: true, name: true, scientificName: true, clade: true, media: true }
  });

  let fixed = 0;
  let remaining = 0;

  for (const s of allSpecies) {
    let mediaArr: MediaItem[] = [];
    try {
      mediaArr = typeof s.media === 'string' ? JSON.parse(s.media) : (s.media || []);
    } catch (e) {}

    const artItem = mediaArr.find(m => m.type === 'art') || mediaArr[0];
    const live = artItem?.url ? await isUrlLive(artItem.url) : false;

    if (live) continue; // Already live & valid!

    console.log(`\nResolving #${s.id} ${s.name} (${s.scientificName})...`);

    const newArt = await findPaleoartBroad(s.name, s.scientificName, s.clade);

    if (newArt) {
      await prisma.species.update({
        where: { id: s.id },
        data: { media: JSON.stringify([newArt]) }
      });
      console.log(`  ✓ REPAIRED & PUSHED TO SUPABASE: ${newArt.url}`);
      console.log(`    Credit: ${newArt.credit}`);
      fixed++;
    } else {
      console.log(`  ⚠️ Still missing live replacement for #${s.id} ${s.name}`);
      remaining++;
    }

    await new Promise(r => setTimeout(r, 100));
  }

  console.log('\n==========================================');
  console.log(`RESOLVE COMPLETE`);
  console.log(`Repaired & Pushed: ${fixed}`);
  console.log(`Unresolved Remaining: ${remaining}`);
  console.log('==========================================');

  // Export full updated database to JSON files
  const exportPath = path.join(__dirname, '..', 'prisma', 'species_full_export.json');
  const dbSpecies = await prisma.species.findMany({ orderBy: { id: 'asc' } });
  fs.writeFileSync(exportPath, JSON.stringify(dbSpecies, null, 2), 'utf8');

  const triassic = dbSpecies.filter(s => s.timePeriod?.toLowerCase().includes('triassic'));
  const jurassic = dbSpecies.filter(s => s.timePeriod?.toLowerCase().includes('jurassic'));
  const cretaceous = dbSpecies.filter(s => s.timePeriod?.toLowerCase().includes('cretaceous'));
  const others = dbSpecies.filter(s =>
    !s.timePeriod?.toLowerCase().includes('triassic') &&
    !s.timePeriod?.toLowerCase().includes('jurassic') &&
    !s.timePeriod?.toLowerCase().includes('cretaceous')
  );

  fs.writeFileSync(path.join(__dirname, '..', 'prisma', 'species_triassic.json'), JSON.stringify(triassic, null, 2), 'utf8');
  fs.writeFileSync(path.join(__dirname, '..', 'prisma', 'species_jurassic.json'), JSON.stringify(jurassic, null, 2), 'utf8');
  fs.writeFileSync(path.join(__dirname, '..', 'prisma', 'species_cretaceous.json'), JSON.stringify(cretaceous, null, 2), 'utf8');
  fs.writeFileSync(path.join(__dirname, '..', 'prisma', 'species_others.json'), JSON.stringify(others, null, 2), 'utf8');

  console.log('✓ Synced updated database records to local JSON files.');
}

resolveBatch()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
