async function testWikimediaApi(speciesName: string) {
  const cleanName = speciesName.split(' ')[0]; // Genus
  const searchQueries = [
    `${speciesName} life restoration`,
    `${cleanName} reconstruction`,
    `${speciesName}`,
    `${cleanName}`
  ];

  for (const q of searchQueries) {
    const url = `https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(q)}&gsrnamespace=6&gsrlimit=10&prop=imageinfo&iiprop=url|mime|extmetadata|user|size&format=json`;
    
    try {
      const res = await fetch(url, { headers: { 'User-Agent': 'PrehistoricaBot/1.0 (educational museum app)' } });
      const json: any = await res.json();
      
      if (!json.query || !json.query.pages) continue;
      
      const pages = Object.values(json.query.pages) as any[];
      
      for (const p of pages) {
        if (!p.imageinfo || !p.imageinfo[0]) continue;
        const info = p.imageinfo[0];
        const mime = info.mime || '';
        if (!mime.startsWith('image/')) continue;
        
        const title = p.title || '';
        const imgUrl = info.url || '';
        const ext = info.extmetadata || {};
        const description = (ext.ImageDescription?.value || '').toLowerCase();
        const categories = (ext.Categories?.value || '').toLowerCase();
        const artist = ext.Artist?.value || info.user || 'Wikimedia Commons contributor';
        const license = ext.LicenseShortName?.value || ext.UsageTerms?.value || 'CC BY-SA / Public Domain';
        
        // Filter out skeletal diagrams, fossil mounts, cladograms, maps, and AI art
        const lowerTitle = title.toLowerCase();
        const lowerArt = String(artist).toLowerCase();
        const lowerCats = categories.toLowerCase();
        
        const isFossilOrDiagram = ['skeletal', 'skeleton', 'fossil', 'skull', 'mount', 'map', 'diagram', 'cladogram', 'phylogeny', 'size_comparison'].some(k => lowerTitle.includes(k) || description.includes(k));
        const isAI = ['midjourney', 'stable diffusion', 'dall-e', 'dalle', 'ai generated', 'ai art', 'generated by ai', 'ai-generated'].some(k => lowerTitle.includes(k) || description.includes(k) || lowerCats.includes(k) || lowerArt.includes(k));
        
        if (isFossilOrDiagram || isAI) continue;
        
        console.log(`Found candidate for ${speciesName} [query: "${q}"]:`);
        console.log(`  Title: ${title}`);
        console.log(`  Url: ${imgUrl}`);
        console.log(`  Artist: ${artist.replace(/<[^>]*>?/gm, '')}`);
        console.log(`  License: ${license}`);
        console.log(`  Description: ${description.slice(0, 100)}...`);
        return {
          url: imgUrl,
          type: 'art',
          credit: `${artist.replace(/<[^>]*>?/gm, '').trim()} (${license})`,
          sourceUrl: `https://commons.wikimedia.org/wiki/${encodeURIComponent(title.replace(/ /g, '_'))}`
        };
      }
    } catch (err) {
      console.error(`Error searching "${q}":`, err);
    }
  }
  return null;
}

testWikimediaApi('Araripesuchus')
  .then(res => console.log('Result:', res))
  .catch(console.error);
